### ISSUE TITLE
[Bug]: RuntimeError: 不能正常加载ChatGLM的参数！

### ISSUE THREAD

**Issue by mudashi33** [binary-husky/gpt_academic#1016]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

报错提示"NotADirectoryError: [WinError 267] 目录名称无效。: 'D:\\VISUAL STUDIO\\VC\\AUXILIARY\\BUILD\\VCVARS64.BAT'"以及"RuntimeError: 不能正常加载ChatGLM的参数！",按教程卸载了torch+cpu版安装了torch+cuda版还是报一样错,然后又按教程将bridge_chatglm.py里的"chatglm-6b"改成了"chatglm-6b-int4"还是报一样的错.

报错信息如下:
D:\Anaconda3\envs\gpt_academic (master -> origin)
(gptac) λ python main.py
如果浏览器没有自动打开，请复制并转到以下URL：
        （亮色主题）: http://localhost:54094
        （暗色主题）: http://localhost:54094/?__theme=dark
正在执行一些模块的预热...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
自动更新程序：已禁用。建议排查：代理网络配置。
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
Running on local URL:  http://0.0.0.0:54094

To create a public link, set `share=True` in `launch()`.
Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████| 243/243 [00:00<?, ?B/s] Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Downloading (…)enization_chatglm.py: 100%|█████████████████████████████████████████████████████████████████| 10.0k/10.0k [00:00<?, ?B/s] Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Downloading tokenizer.model: 100%|█████████████████████████████████████████████████████████████████| 1.02M/1.02M [00:00<00:00, 1.43MB/s] Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████████████████| 1.17k/1.17k [00:00<00:00, 1.14MB/s] Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Downloading (…)iguration_chatglm.py: 100%|█████████████████████████████████████████████████████████████████| 2.25k/2.25k [00:00<?, ?B/s] Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Downloading (…)/modeling_chatglm.py: 100%|█████████████████████████████████████████████████████████| 50.7k/50.7k [00:00<00:00, 1.45MB/s] Downloading (…)main/quantization.py: 100%|█████████████████████████████████████████████████████████| 2.61M/2.61M [00:01<00:00, 1.52MB/s] Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Process GetGLMHandle-2:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\gpt_academic\request_llm\bridge_chatglm.py", line 54, in run
    self.chatglm_model = AutoModel.from_pretrained(_model_name_, trust_remote_code=True).float()
  File "D:\Anaconda3\envs\gptac\lib\site-packages\transformers\models\auto\auto_factory.py", line 462, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "D:\Anaconda3\envs\gptac\lib\site-packages\transformers\dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "D:\Anaconda3\envs\gptac\lib\site-packages\transformers\dynamic_module_utils.py", line 299, in get_cached_module_file
    get_cached_module_file(
  File "D:\Anaconda3\envs\gptac\lib\site-packages\transformers\dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "D:\Anaconda3\envs\gptac\lib\site-packages\transformers\dynamic_module_utils.py", line 134, in check_imports
    importlib.import_module(imp)
  File "D:\Anaconda3\envs\gptac\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Anaconda3\envs\gptac\lib\site-packages\cpm_kernels\__init__.py", line 1, in <module>
    from . import library
  File "D:\Anaconda3\envs\gptac\lib\site-packages\cpm_kernels\library\__init__.py", line 2, in <module>
    from . import cuda
  File "D:\Anaconda3\envs\gptac\lib\site-packages\cpm_kernels\library\cuda.py", line 7, in <module>
    cuda = Lib.from_lib("cuda", ctypes.WinDLL("nvcuda.dll"))
  File "D:\Anaconda3\envs\gptac\lib\site-packages\cpm_kernels\library\base.py", line 63, in from_lib
    ret = Lib(name)
  File "D:\Anaconda3\envs\gptac\lib\site-packages\cpm_kernels\library\base.py", line 45, in __init__
    lib_path = windows_find_lib(self.__name)
  File "D:\Anaconda3\envs\gptac\lib\site-packages\cpm_kernels\library\base.py", line 39, in windows_find_lib
    return lookup_dll(lib_name)
  File "D:\Anaconda3\envs\gptac\lib\site-packages\cpm_kernels\library\base.py", line 16, in lookup_dll
    for name in os.listdir(path):
NotADirectoryError: [WinError 267] 目录名称无效。: 'D:\\VISUAL STUDIO\\VC\\AUXILIARY\\BUILD\\VCVARS64.BAT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\gptac\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Anaconda3\envs\gpt_academic\request_llm\bridge_chatglm.py", line 65, in run
    raise RuntimeError("不能正常加载ChatGLM的参数！")
RuntimeError: 不能正常加载ChatGLM的参数！

### Screen Shot | 有帮助的截图

.

**Comment by mudashi33** [comment]
已解决,系统环境变量中有条"D:\VISUAL STUDIO\VC\AUXILIARY\BUILD\VCVARS64.BAT"是以前自动生成的,程序会读取环境变量且只能是目录,所以读取到VCVARS64.BAT文件时就报错了
