### ISSUE TITLE
[Feature]: 通义千问的模型开源了,建议加入.

### ISSUE THREAD

**Issue by maxadc** [binary-husky/gpt_academic#1021]
### Class | 类型

None

### Feature Request | 功能请求

附：开源地址

魔搭ModelScope：

https://modelscope.cn/models/qwen/Qwen-7B/summary

https://modelscope.cn/models/qwen/Qwen-7B-Chat/summary

Hugging Face：https://huggingface.co/Qwen

GitHub：https://github.com/QwenLM/Qwen-7B

**Comment by binary-husky** [comment]
已支持https://github.com/binary-husky/gpt_academic/commit/c17fc2a9b55b1c7447718a06a3eac4378828bb22

**Comment by binary-husky** [comment]
请反馈

**Comment by maxadc** [comment]
Traceback (most recent call last):
  File "/data/github/gpt_academic/request_llm/local_llm_class.py", line 77, in run
    self._model, self._tokenizer = self.load_model_and_tokenizer()
  File "/data/github/gpt_academic/request_llm/bridge_qwen.py", line 37, in load_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto", revision=revision, trust_remote_code=True, fp16=True).eval()
  File "/data/soft/miniconda3/envs/gpt/lib/python3.9/site-packages/modelscope/utils/hf_util.py", line 98, in from_pretrained
    model = module_class.from_pretrained(model_dir, *model_args,
  File "/data/soft/miniconda3/envs/gpt/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 462, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/data/soft/miniconda3/envs/gpt/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/data/soft/miniconda3/envs/gpt/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/data/soft/miniconda3/envs/gpt/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 139, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/soft/miniconda3/envs/gpt/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/github/gpt_academic/request_llm/local_llm_class.py", line 83, in run
    raise RuntimeError(f"不能正常加载{self.model_name}的参数！")
RuntimeError: 不能正常加载Qwen的参数！

**Comment by maxadc** [comment]
建议把代码中的congfig.py改个名字,用户本地要用,改配置.改完之后,git不会更新,都不知道哪些信息有变更了. 这也是为何我不知道加了通义千问的原因.
此外,运行通义千问运行报错
