### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by medicialcoder** [binary-husky/gpt_academic#1034]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

ImportError: cannot import name 'HashTrieMap' from 'rpds' (D:\anaconda3\envs\gpt_academic\Lib\site-packages\rpds\__init__.py)

### Screen Shot | 有帮助的截图

<img width="1041" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/131216222/41269020-570b-4b6f-ac71-80615331a24a">

**Comment by binary-husky** [comment]
不应该呀，我前天才试过，anaconda安装没问题的。确定用了requirement.txt？一键安装试过没？

**Comment by gabdrz** [comment]
I'm having this issue as well with error code:

`Traceback (most recent call last):
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\src\main.py", line 11, in <module>
    from utils import *
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\src\utils.py", line 31, in <module>
    import gradio as gr
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\gradio\components.py", line 21, in <module>
    import altair as alt
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\__init__.py", line 616, in <module>
    from .vegalite import *
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\__init__.py", line 2, in <module>
    from .v5 import *
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\v5\__init__.py", line 2, in <module>
    from .schema import *
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\v5\schema\__init__.py", line 2, in <module>
    from .core import *
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\v5\schema\core.py", line 4, in <module>
    from altair.utils.schemapi import SchemaBase, Undefined, _subclasses
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\utils\__init__.py", line 1, in <module>
    from .core import (
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\utils\core.py", line 26, in <module>
    import jsonschema
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\jsonschema\__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\jsonschema\_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\jsonschema\exceptions.py", line 15, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\referencing\__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\referencing\_core.py", line 8, in <module>
    from rpds import HashTrieMap, HashTrieSet, List
ImportError: cannot import name 'HashTrieMap' from 'rpds' (C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\rpds\__init__.py)`

**Comment by binary-husky** [comment]
can you provide `pip freeze` output, there must be a package that has incompatible version
________________________________
发件人: Gabriel Zafra ***@***.***>
发送时间: 2023年9月26日 01:14
收件人: binary-husky/gpt_academic ***@***.***>
抄送: binary-husky ***@***.***>; State change ***@***.***>
主题: Re: [binary-husky/gpt_academic] [Bug]: (Issue #1034)


I'm having this issue as well with error code:

Traceback (most recent call last): File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\src\main.py", line 11, in <module> from utils import * File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\src\utils.py", line 31, in <module> import gradio as gr File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\gradio\__init__.py", line 3, in <module> import gradio.components as components File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\gradio\components.py", line 21, in <module> import altair as alt File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\__init__.py", line 616, in <module> from .vegalite import * File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\__init__.py", line 2, in <module> from .v5 import * File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\v5\__init__.py", line 2, in <module> from .schema import * File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\v5\schema\__init__.py", line 2, in <module> from .core import * File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\vegalite\v5\schema\core.py", line 4, in <module> from altair.utils.schemapi import SchemaBase, Undefined, _subclasses File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\utils\__init__.py", line 1, in <module> from .core import ( File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\altair\utils\core.py", line 26, in <module> import jsonschema File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\jsonschema\__init__.py", line 13, in <module> from jsonschema._format import FormatChecker File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\jsonschema\_format.py", line 11, in <module> from jsonschema.exceptions import FormatError File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\jsonschema\exceptions.py", line 15, in <module> from referencing.exceptions import Unresolvable as _Unresolvable File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\referencing\__init__.py", line 4, in <module> from referencing._core import Anchor, Registry, Resource, Specification File "C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\referencing\_core.py", line 8, in <module> from rpds import HashTrieMap, HashTrieSet, List ImportError: cannot import name 'HashTrieMap' from 'rpds' (C:\Users\gabdr\Desktop\Denouement\ai-voice-cloning\venv\lib\site-packages\rpds\__init__.py)

―
