### ISSUE TITLE
[Feature]:  通义千问应该如何接入

### ISSUE THREAD

**Issue by for3ever3** [binary-husky/gpt_academic#1056]
### Class | 类型

大语言模型

### Feature Request | 功能请求

接入了通义， 但是我在config.py里没看到通义的选项（比如apikey或者是使用cookie这种在线服务），请问是需要本地去部署通义-7B吗？然后再去调用本地的模型

**Comment by binary-husky** [comment]
qwen就是通义千问的名字😂

**Comment by binary-husky** [comment]
LLM_MODEL="qwen"即可

**Comment by for3ever3** [comment]
> 



> qwen就是通义千问的名字😂

**Comment by for3ever3** [comment]
> LLM_MODEL="qwen"即可

是的，我之前是这样子填写配置的，但是我出现了下面的问题
`To create a public link, set `share=True` in `launch()`.
2023-08-24 19:10:42,901 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-08-24 19:10:42,903 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2023-08-24 19:10:42,952 - modelscope - INFO - Loading done! Current index file version is 1.8.4, with md5 1fca8867f75fa4450365c611d40386d8 and a total number of 902 components indexed
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\gpt_academic-master\toolbox.py", line 67, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "C:\Users\Administrator\Desktop\gpt_academic-master\request_llm\bridge_all.py", line 511, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\gpt_academic-master\request_llm\local_llm_class.py", line 153, in predict
    _llm_handle = LLMSingletonClass()
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\gpt_academic-master\request_llm\local_llm_class.py", line 15, in _singleton
    _instance[cls] = cls(*args, **kargs)
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\gpt_academic-master\request_llm\local_llm_class.py", line 36, in __init__
    self.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'request_llm.bridge_qwen.GetONNXGLMHandle'>: it's not the same object as request_llm.bridge_qwen.GetONNXGLMHandle
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\spawn.py", line 130, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input`

**Comment by for3ever3** [comment]
> Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\context.py", line 224, in _Popen return _default_context.get_context().Process._Popen(process_obj) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File

没有填写gpt的api，proxy是false

**Comment by luciffer** [comment]
显然是不支持通义千问api
