### ISSUE TITLE
请问遇到chatgpt 学术优化遇到 Json Error应该怎么解决

### ISSUE THREAD

**Issue by NIHENDUOROU** [binary-husky/gpt_academic#1062]
[Local Message] Json Error
Traceback (most recent call last):
File "C:\Users\MI\Desktopchatgpt academic-masterchatgpt academic-master predict,py", line 114, in predictif len(json.loads(chunk.decode()[6:])['choices’][0]["delta"]) == 0:File "C:\Users\MI AppData Local Programs Python Python38 lib json init .py", line 357, in loadsreturn default decoder.decode(s)
File "C:Users\MIAppData LocalPrograms Python Python38 lib json decoder,py", line 337, in decodeobj, end = self.raw decode(s, idx=_w(s, 0).end
File "C:Users\MIAppData LocalPrograms(Python Python38 lib jsondecoder,py", line 355, in raw decoderaise JSONDecodeError(Expecting value”, s, err.value) from Nonejson.decoderJSONDecodeError: Expecting value: line 1 column 1 (char 0)error": ( "message': "You exceeded your current quota, please check your plan and billing details.", "type"insufficient quota", "param": null, "code": "insufficient quota" )

**Comment by binary-husky** [comment]
You exceeded your current quota, please check your plan and billing details.
