### ISSUE TITLE
[Bug]:  实验性函数调用出错

### ISSUE THREAD

**Issue by Dr-Joseph-Zhou** [binary-husky/gpt_academic#1079]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

已通过docker方式安装了LaTex，并使用docker compose up启动，但是目前仍然存在问题。

初始跳出的提示是：

[Local Message] 分析结果：该项目的Latex主文件是/root/arxiv_cache/1707.01495/extract/main.tex, 如果分析错误, 请立即终止程序, 删除或修改歧义文件, 然后重试。主程序即将开始, 请稍候。

### Screen Shot | 有帮助的截图

截图如下：
![image](https://github.com/binary-husky/gpt_academic/assets/66234152/1b96899b-b33a-4e41-bd34-27a6255a2bae)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "./toolbox.py", line 122, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/Latex输出PDF结果.py", line 279, in Latex翻译中文并重新编译PDF
    yield from Latex精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs,
  File "./crazy_functions/latex_fns/latex_actions.py", line 228, in Latex精细分解与转化
    merged_content = merge_tex_files(project_folder, content, mode)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./crazy_functions/latex_fns/latex_toolbox.py", line 340, in merge_tex_files
    assert (match_opt1 is not None) or (match_opt2 is not None), "Cannot find paper abstract section!"
                                        ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot find paper abstract section!

**Comment by Dr-Joseph-Zhou** [comment]
使用的论文: https://arxiv.org/abs/1707.01495

**Comment by Dr-Joseph-Zhou** [comment]
已在win系统等其他系统尝试，似乎是论文本身的问题。更换论文后不报错。
