### ISSUE TITLE
[Feature]: 精准翻译PDF论文时报错，存储空间不足，无法处理此命令。

### ISSUE THREAD

**Issue by tibiwzzz** [binary-husky/gpt_academic#1107]
### Class | 类型

函数插件

### Feature Request | 功能请求

Traceback (most recent call last):
  File ".\toolbox.py", line 122, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\批量翻译PDF文档_多线程.py", line 53, in 批量翻译PDF文档
    yield from 解析PDF_基于GROBID(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt, grobid_url)
  File ".\crazy_functions\批量翻译PDF文档_多线程.py", line 69, in 解析PDF_基于GROBID
    print(article_dict)
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 205, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "F:\Anaconda3\envs\gpt_academic\lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
OSError: [WinError 8] 存储空间不足，无法处理此命令。

部署好了用了没几次，前两天用还正常，今天用就不行了，请大佬们指点

**Comment by binary-husky** [comment]
有没有可能，就是硬盘满了

**Comment by binary-husky** [comment]
但，存储空间不足这种错误，绝对不会无缘无故地跳出来

**Comment by TonyHuang0711** [comment]
能否提供下版本信息？是不是用的32位版本导致内存不足？

**Comment by tibiwzzz** [comment]
> 能否提供下版本信息？是不是用的32位版本导致内存不足？

不知道怎么过了两天就好了，谢谢您
