### ISSUE TITLE
[Bug]: 不能正常加载ChatGLM的参数！

### ISSUE THREAD

**Issue by wales-z** [binary-husky/gpt_academic#1124]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

这两天因为huggingface又上不去了，不得已去镜像站下载了chatglm2-6b-int4的权重，然后我也将 request_llm/bridge_chatglm.py 里模型加载部分（int4这一项）做了以下修改，试图以本地模型权重方式加载模型：
```python
        if LOCAL_MODEL_QUANT == "INT4":         # INT4
            _model_name_ = "/home/zxl/gpt_academic/dataroot/models/THUDM/chatglm2-6b-int4"
        elif LOCAL_MODEL_QUANT == "INT8":       # INT8
            _model_name_ = "THUDM/chatglm2-6b-int8"
        else:
            _model_name_ = "THUDM/chatglm2-6b"  # FP16
```
但是遇到以下报错：
```
Process GetGLMHandle-1:
Traceback (most recent call last):
  File "/home/zxl/gpt_academic/request_llm/bridge_chatglm.py", line 56, in run
    self.chatglm_model = AutoModel.from_pretrained(_model_name_, trust_remote_code=True).half().cuda()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2054, in cuda
    return super().cuda(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                                 ^^^^^^^^^^^^^^
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zxl/miniconda3/envs/gptac/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/zxl/gpt_academic/request_llm/bridge_chatglm.py", line 65, in run
    raise RuntimeError("不能正常加载ChatGLM的参数！")
RuntimeError: 不能正常加载ChatGLM的参数！
```
查看主要报错那行，似乎是多线程使用cuda出错。

p.s. 由于默认的torch环境是cpu的，我重新装了cuda版的，相关环境依赖如下：
```
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cuda-version              11.7                 h67201e3_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cudatoolkit               11.7.1              h4bc3d14_12    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cudnn                     8.8.0.121            h838ba91_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
...
pytorch                   2.0.1           py3.8_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
...
```

### Screen Shot | 有帮助的截图

![屏幕截图 2023-09-22 160925](https://github.com/binary-husky/gpt_academic/assets/54798466/1bd967a2-b33b-43ba-8728-5c32c7d7573f)

**Comment by binary-husky** [comment]
该问题正在验证……

**Comment by binary-husky** [comment]
@wales-z 验证发现我们的代码不能复现此问题

你一定是在主进程进行了运行了cuda什么的，把对应的代码删除，或者移动到子进程即可

**Comment by wales-z** [comment]
> @wales-z 验证发现我们的代码不能复现此问题
> 
> 你一定是在主进程进行了运行了cuda什么的，把对应的代码删除，或者移动到子进程即可

很神奇，我跟之前一样直接启动，但是这次就可以成功运行了。其实我自己并没有对主进程做什么改动。

这一次与之前运行报错的主要区别是，上次0号卡有人在运行TensorRT推理（只是load了模型，占用了部分显存，但没有做运算，因为GPU-Util一直是0），这次没有，我猜测是这个因素导致的报错。也就是说，应该在一张空显卡上运行程序。

为了再避免这个情况，我又尝试了指定显卡启动进程：`CUDA_VISIBLE_DEVICES=1 python main.py` ，用1号卡运行，也是能成功运行的，希望能帮到遇到这类报错的人。
