### ISSUE TITLE
[Bug]: tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by IcyFeather233** [binary-husky/gpt_academic#1130]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用插件为：插件[Arixv论文精细翻译（输入arxivID）
arxiv序号为：2009.01417
报错如下
```
[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File ".\toolbox.py", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF结果.py", line 250, in Latex翻译中文并重新编译PDF
    txt, arxiv_id = yield from arxiv_download(chatbot, history, txt, allow_cache)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\Latex输出PDF结果.py", line 139, in arxiv_download
    extract_archive(file_path=dst, dest_dir=extract_dst)
  File ".\toolbox.py", line 461, in extract_archive
    with tarfile.open(file_path, 'r:*') as tarobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Miniconda3\envs\gptac_venv\Lib\tarfile.py", line 1811, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')
```

### Screen Shot | 有帮助的截图

![图片](https://github.com/binary-husky/gpt_academic/assets/56245435/09bfa282-2c4d-4a4a-8721-cee89f391a40)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

`C:\Users\Lenovo\arxiv_cache`中对应样本：
[2009.01417.zip](https://github.com/binary-husky/gpt_academic/files/12716896/2009.01417.zip)

**Comment by binary-husky** [comment]
你好，这个arxiv论文没有上传latex源码，这是少数情况，很遗憾

**Comment by shanhaiying** [comment]
最近好多次遇到这个情况， 并不一定是论文没提供源代码。 而是tar没能解压。 用系统中的app有时可正常解压出tex源代码。 有时用app打开也会报错。 还没弄清原因。
