### ISSUE TITLE
[Bug]: Json异常

### ISSUE THREAD

**Issue by jadechjin** [binary-husky/gpt_academic#1138]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

报错：Json异常
烦请作者大大解答

### Screen Shot | 有帮助的截图

<img width="1117" alt="屏幕截图 2023-10-01 013113" src="https://github.com/binary-husky/gpt_academic/assets/146434195/c2a111cb-2ba6-4fc7-8537-8127847387c4">

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 202, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\chatgpt\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\chatgpt\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\chatgpt\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jadechjin** [comment]
找到问题了，我把url重定向了，api key 和 url 改回来就没事了
