### ISSUE TITLE
[Feature]: 当输入论文并非标准格式会出现报错

### ISSUE THREAD

**Issue by Q-uassia** [binary-husky/gpt_academic#1158]
### Class | 类型

None

### Feature Request | 功能请求

当传入论文不包含abstract时，Arxiv论文精细翻译功能无法正常使用
例，[arXiv:2208.11173v3](https://arxiv.org/abs/2208.11173v3)
报错信息如下：
[Local Message] 实验性函数调用出错:
Traceback (most recent call last):
  File ".\toolbox.py", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF结果.py", line 282, in Latex翻译中文并重新编译PDF
    yield from Latex精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs,
  File ".\crazy_functions\latex_fns\latex_actions.py", line 228, in Latex精细分解与转化
    merged_content = merge_tex_files(project_folder, content, mode)
  File ".\crazy_functions\latex_fns\latex_toolbox.py", line 345, in merge_tex_files
    assert (match_opt1 is not None) or (match_opt2 is not None), "Cannot find paper abstract section!"
AssertionError: Cannot find paper abstract section!

**Comment by binary-husky** [comment]
这个文献的格式极端特殊，已修复，下个版本merge，您可以到frontier分支抢先体验

**Comment by binary-husky** [comment]
[2023-10-18-08-41-08-comparison.pdf](https://github.com/binary-husky/gpt_academic/files/12999431/2023-10-18-08-41-08-comparison.pdf)


@Q-uassia
