### ISSUE TITLE
[Bug]: 精准翻译提示出错。

### ISSUE THREAD

**Issue by gqc1129** [binary-husky/gpt_academic#1163]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用精准翻译，直接报错。
网页端错误代码：
Traceback (most recent call last):
  File ".\toolbox.py", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\批量翻译PDF文档_NOUGAT.py", line 88, in 批量翻译PDF文档
    yield from 解析PDF_基于NOUGAT(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File ".\crazy_functions\批量翻译PDF文档_NOUGAT.py", line 104, in 解析PDF_基于NOUGAT
    fpp = yield from nougat_handle.NOUGAT_parse_pdf(fp, chatbot, history)
  File ".\crazy_functions\crazy_utils.py", line 747, in NOUGAT_parse_pdf
    raise RuntimeError("Nougat解析论文失败。")
RuntimeError: Nougat解析论文失败。
命令行终端错误代码：
Running on local URL:  http://0.0.0.0:54687
WARNING:root:No GPU found. Conversion on CPU is very slow.
downloading nougat checkpoint version 0.1.0-small to path C:\Users\zua\.cache\torch\hub\nougat-0.1.0-small
Traceback (most recent call last):
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\chatgpt\installer_files\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\chatgpt\installer_files\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\chatgpt\installer_files\env\Scripts\nougat.exe\__main__.py", line 7, in <module>
  File "D:\chatgpt\installer_files\env\lib\site-packages\predict.py", line 126, in main
    args = get_args()
  File "D:\chatgpt\installer_files\env\lib\site-packages\predict.py", line 88, in get_args
    args.checkpoint = get_checkpoint(args.checkpoint, model_tag=args.model)
  File "D:\chatgpt\installer_files\env\lib\site-packages\nougat\utils\checkpoint.py", line 114, in get_checkpoint
    download_checkpoint(checkpoint, model_tag=model_tag or MODEL_TAG)
  File "D:\chatgpt\installer_files\env\lib\site-packages\nougat\utils\checkpoint.py", line 69, in download_checkpoint
    binary_file = download_as_bytes_with_progress(download_url, file)
  File "D:\chatgpt\installer_files\env\lib\site-packages\nougat\utils\checkpoint.py", line 31, in download_as_bytes_with_progress
    resp = requests.get(url, stream=True, allow_redirects=True)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
代理配置 http://127.0.0.1:7890, 代理所在地：Japan - Cloudflare, Inc.

### Screen Shot | 有帮助的截图

![截图](https://github.com/binary-husky/gpt_academic/assets/23094731/4082c68c-596b-4a12-80e5-928dd7e3a9ff)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Running on local URL:  http://0.0.0.0:54687
WARNING:root:No GPU found. Conversion on CPU is very slow.
downloading nougat checkpoint version 0.1.0-small to path C:\Users\zua\.cache\torch\hub\nougat-0.1.0-small
Traceback (most recent call last):
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\chatgpt\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\chatgpt\installer_files\env\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\chatgpt\installer_files\env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\chatgpt\installer_files\env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\chatgpt\installer_files\env\Scripts\nougat.exe\__main__.py", line 7, in <module>
  File "D:\chatgpt\installer_files\env\lib\site-packages\predict.py", line 126, in main
    args = get_args()
  File "D:\chatgpt\installer_files\env\lib\site-packages\predict.py", line 88, in get_args
    args.checkpoint = get_checkpoint(args.checkpoint, model_tag=args.model)
  File "D:\chatgpt\installer_files\env\lib\site-packages\nougat\utils\checkpoint.py", line 114, in get_checkpoint
    download_checkpoint(checkpoint, model_tag=model_tag or MODEL_TAG)
  File "D:\chatgpt\installer_files\env\lib\site-packages\nougat\utils\checkpoint.py", line 69, in download_checkpoint
    binary_file = download_as_bytes_with_progress(download_url, file)
  File "D:\chatgpt\installer_files\env\lib\site-packages\nougat\utils\checkpoint.py", line 31, in download_as_bytes_with_progress
    resp = requests.get(url, stream=True, allow_redirects=True)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\chatgpt\installer_files\env\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
代理配置 http://127.0.0.1:7890, 代理所在地：Japan - Cloudflare, Inc.

**Comment by binary-husky** [comment]
中国特色网络体验

目前nougat尚未应用代理，未来版本会加上的，首次运行nougat您可以手动安装并下载参数

**Comment by jadechjin** [comment]
> 中国特色网络体验
> 
> 目前nougat尚未应用代理，未来版本会加上的，首次运行nougat您可以手动安装并下载参数

我安装了nougat，能跑，但是他一直在用cpu而不用gpu，有点慢，实际翻译一篇论文时还会出现很多其他报错
报错代码有：WARNING:root:No GPU found. Conversion on CPU is very slow.
D:\Anaconda\envs\chatgpt\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)

    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "Rate limit reached for gpt-3.5-turbo in organization org-pQjELa4drlqjZZvsDCAGrQUi on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",        "type": "requests",        "param": null,        "code": "rate_limit_exceeded"    }}

ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)

**Comment by gqc1129** [comment]
THX!

多谢大佬！

坐等更新！




future.gao
***@***.***







                       
Original
                       
                     

From:"jadechjin"< ***@***.*** &gt;;

Date:2023/10/13 9:40

To:"binary-husky/gpt_academic"< ***@***.*** &gt;;

CC:"gqc1129"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [binary-husky/gpt_academic] [Bug]: 精准翻译提示出错。 (Issue #1163)




  
中国特色网络体验
 
目前nougat尚未应用代理，未来版本会加上的，首次运行nougat您可以手动安装并下载参数
  
我安装了nougat，能跑，但是他一直在用cpu而不用gpu，有点慢，实际翻译一篇论文时还会出现很多其他报错
 报错代码有：WARNING:root:No GPU found. Conversion on CPU is very slow.
 D:\Anaconda\envs\chatgpt\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)
 raise RuntimeError("OpenAI拒绝了请求：" + error_msg)  
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "Rate limit reached for gpt-3.5-turbo in organization org-pQjELa4drlqjZZvsDCAGrQUi on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",        "type": "requests",        "param": null,        "code": "rate_limit_exceeded"    }}
 
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992)

**Comment by leoleelxh** [comment]
> THX! 多谢大佬！ 坐等更新！ future.gao ***@***.*** Original From:"jadechjin"< ***@***.*** &gt;; Date:2023/10/13 9:40 To:"binary-husky/gpt_academic"< ***@***.*** &gt;; CC:"gqc1129"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;; Subject:Re: [binary-husky/gpt_academic] [Bug]: 精准翻译提示出错。 (Issue #1163) 中国特色网络体验 目前nougat尚未应用代理，未来版本会加上的，首次运行nougat您可以手动安装并下载参数 我安装了nougat，能跑，但是他一直在用cpu而不用gpu，有点慢，实际翻译一篇论文时还会出现很多其他报错 报错代码有：WARNING:root:No GPU found. Conversion on CPU is very slow. D:\Anaconda\envs\chatgpt\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.) raise RuntimeError("OpenAI拒绝了请求：" + error_msg) RuntimeError: OpenAI拒绝了请求：{ "error": { "message": "Rate limit reached for gpt-3.5-turbo in organization org-pQjELa4drlqjZZvsDCAGrQUi on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.", "type": "requests", "param": null, "code": "rate_limit_exceeded" }} ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:992) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问如何手动安装呢？

**Comment by binary-husky** [comment]
刚追加了nougat参数下载的代理设置，分支frontier

https://github.com/binary-husky/gpt_academic/commit/70c7daeeebfde341e0ce34a6194875bfc34579de

**Comment by binary-husky** [comment]
不久后汇入主分支
