### ISSUE TITLE
写入markdown文档时出现以下报错，请看以下

### ISSUE THREAD

**Issue by EvelynCarter** [binary-husky/gpt_academic#119]
[Local Message] 实验性函数调用出错:

Traceback (most recent call last):

File "D:\aaaaa\Chatgpt\toolbox.py", line 81, in decorated

yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)

File "D:\aaaaaaaaaa\Chatgpt\crazy_functions\解析项目源代码.py", line 107, in 解析一个Python项目

yield from 解析源代码(file_manifest, project_folder, top_p, temperature, chatbot, history, systemPromptTxt)

File "D:\tianyiyun\Chatgpt\crazy_functions\解析项目源代码.py", line 42, in 解析源代码

res = write_results_to_file(history)

      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "D:\tiaaaaaaan\Chatgpt\toolbox.py", line 59, in write_results_to_file

f.write(content)

TypeError: write() argument must be str, not None

**Comment by Slipstream-Max** [comment]
一样的问题

**Comment by Slipstream-Max** [comment]
我找到我的问题了 我是因为文件编码没调整 好 他要utf8的

**Comment by EvelynCarter** [comment]
能解决项目过大的问题了吗

**Comment by Slipstream-Max** [comment]
这个就不清楚了 我扔给他我自己写的一个东东
：）
