### ISSUE TITLE
[Bug]: 知识库问答报错

### ISSUE THREAD

**Issue by cao888** [binary-husky/gpt_academic#1192]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

知识库问答报错
使用了api重定向，没有配置代理
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.com.cn/v1/chat/completions"}

报错内容：
`Traceback (most recent call last):
  File ".\toolbox.py", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Langchain知识库.py", line 96, in 读取知识库作答
    resp, prompt = kai.answer_with_archive_by_id(txt, kai_id)
  File ".\crazy_functions\crazy_utils.py", line 705, in answer_with_archive_by_id
    resp, prompt = self.qa_handle.get_knowledge_based_conent_test(
  File "C:\Users\aa\AppData\Roaming\Python\Python310\site-packages\zh_langchain\chains\local_doc_qa.py", line 238, in get_knowledge_based_conent_test
    embedding = self.vector_store.embedding_function(query)
TypeError: 'HuggingFaceEmbeddings' object is not callable`

### Screen Shot | 有帮助的截图

![微信截图_20231024235123](https://github.com/binary-husky/gpt_academic/assets/36356389/2041e41a-0f34-415c-b42d-af4de33ab14c)
![微信截图_20231024235109](https://github.com/binary-husky/gpt_academic/assets/36356389/dfeda05c-f6f0-44e9-b812-0d95b74c2100)

**Comment by 9p6p** [comment]
问题同

**Comment by samxiaowastaken** [comment]
同问题

**Comment by cmcccopy** [comment]
也出现同样问题，代理使用V2RayN，使用了api重定向

**Comment by yanmengxiang1** [comment]
请问有进展吗
同样的问题

**Comment by xiao-yuling** [comment]
和代理没有关系,肉身一样有问题

**Comment by danfouer** [comment]
I met exactly the same problem:

Traceback (most recent call last):
  File ".\toolbox.py", line 156, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Langchain知识库.py", line 96, in 读取知识库作答
    resp, prompt = kai.answer_with_archive_by_id(txt, kai_id)
  File ".\crazy_functions\crazy_utils.py", line 706, in answer_with_archive_by_id
    resp, prompt = self.qa_handle.get_knowledge_based_conent_test(
  File "D:\ProgramData\anaconda3\envs\gptac\lib\site-packages\zh_langchain\chains\local_doc_qa.py", line 238, in get_knowledge_based_conent_test
    embedding = self.vector_store.embedding_function(query)
TypeError: 'HuggingFaceEmbeddings' object is not callable

文件加载完毕，正在生成向量库
Batches: 100%|██████████| 42/42 [00:06<00:00,  6.13it/s]
代理配置 http://127.0.0.1:7890, 代理所在地：Japan - Google LLC
 gpt-3.5-turbo : 0 : 'HuggingFaceEmbeddings' object is not callable ..........
 gpt-3.5-turbo : 1 :  File "D:\ProgramData\anaconda3\envs\gptac\lib\site-packages\zh_langchain\chains\local_doc_qa.py", l ..........
 gpt-3.5-turbo : 2 : Traceback (most recent call last):
  File ".\toolbox.py", line 156, in decorated
    yield from f(ma ..........
