### ISSUE TITLE
[Bug]: chatglm不能正常加载到cuda

### ISSUE THREAD

**Issue by liugangg** [binary-husky/gpt_academic#1194]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

chatglm调用cuda报错

### Screen Shot | 有帮助的截图

![图片](https://github.com/binary-husky/gpt_academic/assets/128766922/2100e3b2-fe41-4c97-b3d6-8c36b3006799)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lgg/anaconda3/envs/gptac_venv/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/lgg/Downloads/chatgpt_academic/request_llm/bridge_chatglm.py", line 66, in run
    raise RuntimeError("不能正常加载ChatGLM的参数！")
RuntimeError: 不能正常加载ChatGLM的参数！

**Comment by Dolphin4mi** [comment]
俺也一样
