### ISSUE TITLE
[Bug]: cannot import name 'RootModel' from 'pydantic'

### ISSUE THREAD

**Issue by zougang123** [binary-husky/gpt_academic#1237]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Windows

### Describe the bug | 简述

我安装了pydantic==1.10.11
C:\WINDOWS\system32>pip install pydantic==1.10.11
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pydantic==1.10.11 in d:\python\python3.10.4\lib\site-packages (1.10.11)
Requirement already satisfied: typing-extensions>=4.2.0 in d:\python\python3.10.4\lib\site-packages (from pydantic==1.10.11) (4.8.0)
可是运行main.py后，出现如下问题：
D:\python\python3.10.4\python.exe I:\program_file\python\gptacademic\main.py 
Traceback (most recent call last):
  File "I:\program_file\python\gptacademic\main.py", line 448, in <module>
    main()
  File "I:\program_file\python\gptacademic\main.py", line 7, in main
    import gradio as gr
  File "D:\python\python3.10.4\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\python\python3.10.4\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\python\python3.10.4\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "D:\python\python3.10.4\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\python\python3.10.4\lib\site-packages\gradio\components\annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "D:\python\python3.10.4\lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "D:\python\python3.10.4\lib\site-packages\gradio\data_classes.py", line 14, in <module>
    from pydantic import BaseModel, RootModel, ValidationError
ImportError: cannot import name 'RootModel' from 'pydantic' (D:\python\python3.10.4\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)

进程已结束，退出代码为 1

### Screen Shot | 有帮助的截图

from pydantic import BaseModel, RootModel, ValidationError
ImportError: cannot import name 'RootModel' from 'pydantic' (D:\python\python3.10.4\lib\site-packages\pydantic\__init__.cp310-win_amd64.pyd)

进程已结束，退出代码为 1

**Comment by zougang123** [comment]
请问这个问题该怎么解决，我已经试过pydantic和gradio的多个版本，还是没法解决这个问题

**Comment by tuzeao-tal** [comment]
我也刚刚碰到了，我只是简单卸载再重装一下就解决了
gradio一直是3.39.0
我发现websocket版本变了，可能对你有用

**Comment by binary-husky** [comment]
gradio版本和pydantic版本不对应导致的，请参考readme第一行：
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/04600547-38e8-4c73-ab71-76fa8d93a9ba)

**Comment by rkuo2000** [comment]
Yes, it start working after you pip uninstall gradio pydantic, then pip install gradio pydantic

**Comment by BlackSiao** [comment]
> Yes, it start working after you pip uninstall gradio pydantic, then pip install gradio pydantic

very useful, thank you
