### ISSUE TITLE
本地加载不了chatGLM3报错[Bug]: 

### ISSUE THREAD

**Issue by kakabai** [binary-husky/gpt_academic#1246]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

一输入就报错，也不能加载模型：
(academic) D:\projact\gpt_academic-master>python main.py
 [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
代理配置 无, 代理所在地：China
 [API_KEY] 本项目现已支持OpenAI和Azure的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,azure-key3"
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。
 [API_KEY] 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。
如果浏览器没有自动打开，请复制并转到以下URL：
        「暗色主题已启用（支持动态切换主题）」: http://localhost:3585
自动更新程序：已禁用。建议排查：代理网络配置。
正在执行一些模块的预热...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
Running on local URL:  http://0.0.0.0:3585
Traceback (most recent call last):
  File "D:\anaconda3\envs\academic\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\academic\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\anaconda3\envs\academic\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\anaconda3\envs\academic\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\anaconda3\envs\academic\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\anaconda3\envs\academic\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\anaconda3\envs\academic\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda3\envs\academic\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\anaconda3\envs\academic\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\projact\gpt_academic-master\toolbox.py", line 89, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "D:\projact\gpt_academic-master\request_llms\bridge_all.py", line 641, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "D:\projact\gpt_academic-master\request_llms\local_llm_class.py", line 271, in predict
    _llm_handle = LLMSingletonClass()
  File "D:\projact\gpt_academic-master\request_llms\local_llm_class.py", line 37, in _singleton
    _instance[cls] = cls(*args, **kargs)
  File "D:\projact\gpt_academic-master\request_llms\local_llm_class.py", line 86, in __init__
    self.start()
  File "D:\anaconda3\envs\academic\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\anaconda3\envs\academic\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda3\envs\academic\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\anaconda3\envs\academic\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda3\envs\academic\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'request_llms.bridge_chatglm3.GetGLM3Handle'>: it's not the same object as request_llms.bridge_chatglm3.GetGLM3Handle
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda3\envs\academic\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\anaconda3\envs\academic\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

### Screen Shot | 有帮助的截图

config.py已经修修改为chatGLM3

**Comment by binary-husky** [comment]
似乎是windows的兼容有点问题，加上todo标签定位一下

**Comment by 2catycm** [comment]
我也遇到同样问题

**Comment by danfouer** [comment]
我是window10系统 只用gpt-3.5-turbo可以正常工作，单独使用chatglm3也是可以通过http://127.0.0.1:8000/访问的，但是安装了python -m pip install -r request_llms/requirements_chatglm.txt 就开始报：
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (D:\ProgramData\anaconda3\envs\gptac\Lib\site-packages\charset_normalizer\constant.py)

**Comment by danfouer** [comment]
正在同时咨询gpt-3.5-turbo&chatglm3：
Traceback (most recent call last):
  File ".\request_llms\bridge_all.py", line 543, in decorated
    return f(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\local_llm_class.py", line 223, in predict_no_ui_long_connection
    _llm_handle = LLMSingletonClass()
                  ^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\local_llm_class.py", line 37, in _singleton
    _instance[cls] = cls(*args, **kargs)
                     ^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\local_llm_class.py", line 86, in __init__
    self.start()
  File "D:\ProgramData\anaconda3\envs\gptac\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\gptac\Lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\gptac\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\gptac\Lib\multiprocessing\popen_spawn_win32.py", line 94, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\ProgramData\anaconda3\envs\gptac\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'request_llms.bridge_chatglm3.GetGLM3Handle'>: it's not the same object as request_llms.bridge_chatglm3.GetGLM3Handle

**Comment by danfouer** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/4875770/2b13603e-f04b-4798-bcbb-c4e95bfba022)
LLM_MODEL = "gpt-3.5-turbo"
API_KEY = 'sk-PjDisw70wxoSRoiFB4A6B11693614251A6C59825D06631E0'   # 随意设定一个key
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"http://127.0.0.1:8000/v1/chat/completions"}  # 注意端口号
我理解这么干就是骗过gpt-3.5-turbo，让它从http://127.0.0.1:8000/v1/chat/completions进行交流，但是没有输出

**Comment by binary-husky** [comment]
问题已经定位，需要测试几天

**Comment by binary-husky** [comment]
frontier分支已更新，请试一下，如果还存在问题，请重开issue

**Comment by kakabai** [comment]
问题解决可以加载chatGLM3了，感谢作者！

**Comment by 2catycm** [comment]
果然能用了，感谢
