### ISSUE TITLE
[Bug]: 在使用“自定义菜单”时遇到问题

### ISSUE THREAD

**Issue by guobao888** [binary-husky/gpt_academic#1247]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在“自定义菜单”界面，点击“加载已保存”出现下面错误：

加载tokenizer完毕
Running on local URL:  http://0.0.0.0:57135
Traceback (most recent call last):
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "f:\gpt_academic\gpt_academic-master\main.py", line 251, in reflesh_btn
    else: ret.update({predefined_btns[k]: gr.update(visible=True, value=v['Title'])})
KeyError: '找图片'

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/98642716/2a09829d-76af-4af3-8120-f5626cbdab39)
![image](https://github.com/binary-husky/gpt_academic/assets/98642716/74644d08-dcef-47d7-9fc1-5c4f78d62c9e)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Running on local URL:  http://0.0.0.0:57135
Traceback (most recent call last):
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\gpt_academic\gpt_academic-master\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "f:\gpt_academic\gpt_academic-master\main.py", line 251, in reflesh_btn
    else: ret.update({predefined_btns[k]: gr.update(visible=True, value=v['Title'])})
KeyError: '找图片'

**Comment by binary-husky** [comment]
谢谢反馈，正在定位问题

**Comment by guobao888** [comment]
> 谢谢反馈，正在定位问题

另外，自定义的按钮是不能永久保存的吗？刷新页面即失效？
