### ISSUE TITLE
[Bug]: 2202.12193论文精细翻译时出现Tex源文件缺失！错误，不知具体原因为何

### ISSUE THREAD

**Issue by qu3t2alc0atl** [binary-husky/gpt_academic#1248]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

定位主Latex文件
[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File ".\toolbox.py", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF结果.py", line 282, in Latex翻译中文并重新编译PDF
    yield from Latex精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs,
  File ".\crazy_functions\latex_fns\latex_actions.py", line 228, in Latex精细分解与转化
    merged_content = merge_tex_files(project_folder, content, mode)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\latex_fns\latex_toolbox.py", line 327, in merge_tex_files
    """

  File ".\crazy_functions\latex_fns\latex_toolbox.py", line 317, in merge_tex_files_
    raise RuntimeError(f'找不到{fp}，Tex源文件缺失！')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\latex_fns\latex_toolbox.py", line 316, in merge_tex_files_
    else:
        ^^
RuntimeError: 找不到C:\Users\Administrator/arxiv_cache/2202.12193\workfolder\#1，Tex源文件缺失！
 
当前代理可用性:

代理配置 socks5h://localhost:10793, 代理所在地：United States

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/63992677/6bd2a4c9-c91e-4903-a924-ff6b4c65ea57)
![image](https://github.com/binary-husky/gpt_academic/assets/63992677/07039744-6eff-48a4-b04c-f03f196cdfdb)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

https://arxiv.org/format/2202.12193

**Comment by binary-husky** [comment]
请您确认一下latex源码里面有没有带奇异符号的文件名，然后重新打包-上传-翻译本地arxiv论文即可
