### ISSUE TITLE
[Bug]: gpt官网可以正常打开使用 项目提示网络错误

### ISSUE THREAD

**Issue by aw1d6xx** [binary-husky/gpt_academic#1263]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

 gpt-3.5-turbo : 0 : 你好 ..........
urllib3.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OneKeyInstallerForWindowsAndMacOS\gpt_academic\request_llms\bridge_chatgpt.py", line 199, in predict
    response = requests.post(endpoint, headers=headers, proxies=proxies,
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\OneKeyInstallerForWindowsAndMacOS\gpt_academic\toolbox.py", line 89, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "D:\OneKeyInstallerForWindowsAndMacOS\gpt_academic\request_llms\bridge_all.py", line 677, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "D:\OneKeyInstallerForWindowsAndMacOS\gpt_academic\request_llms\bridge_chatgpt.py", line 206, in predict
    if retry > MAX_RETRY: raise TimeoutError
TimeoutError

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/66401917/108be840-0376-48da-ba14-bc71aee3b833)
![image](https://github.com/binary-husky/gpt_academic/assets/66401917/c28587f9-59ab-468d-815b-c7f1559e41a9)

**Comment by binary-husky** [comment]
#1

**Comment by aw1d6xx** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
