### ISSUE TITLE
未部署成功，报错：AttributeError: module 'config' has no attribute 'API_ORG'

### ISSUE THREAD

**Issue by stone00789** [binary-husky/gpt_academic#1292]
### Class | 类型

None

### Feature Request | 功能请求

Traceback (most recent call last):
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\toolbox.py", line 800, in read_single_conf_with_lru_cache
    default_ref = getattr(importlib.import_module('config'), arg)   # 读取默认值作为数据类型转换的参考
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'API_ORG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\toolbox.py", line 805, in read_single_conf_with_lru_cache        
    r = getattr(importlib.import_module('config_private'), arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config_private' has no attribute 'API_ORG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\main.py", line 448, in <module>
    main()
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\main.py", line 9, in main
    from request_llms.bridge_all import predict
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\request_llms\bridge_all.py", line 16, in <module>
    from .bridge_chatgpt import predict_no_ui_long_connection as chatgpt_noui
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\request_llms\bridge_chatgpt.py", line 26, in <module>
    get_conf('proxies', 'TIMEOUT_SECONDS', 'MAX_RETRY', 'API_ORG', 'AZURE_CFG_ARRAY')
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\toolbox.py", line 838, in get_conf
    r = read_single_conf_with_lru_cache(arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\Documents\WPSDrive\gpt_academic-master\toolbox.py", line 808, in read_single_conf_with_lru_cache        
    r = getattr(importlib.import_module('config'), arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'API_ORG'

**Comment by binary-husky** [comment]
更新代码
