### ISSUE TITLE
[Bug]:  has no attribute 'CUSTOM_API_KEY_PATTERN'

### ISSUE THREAD

**Issue by Aleix-Chen** [binary-husky/gpt_academic#1308]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

module 'config' has no attribute 'CUSTOM_API_KEY_PATTERN'

### Screen Shot | 有帮助的截图

<img width="1004" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/58615825/ca246469-ac40-4eb1-9cd9-94d3dd1ceae8">

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "/Users/chenlei/gpt_academic/toolbox.py", line 824, in read_single_conf_with_lru_cache
    default_ref = getattr(importlib.import_module('config'), arg)   # 读取默认值作为数据类型转换的参考
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'CUSTOM_API_KEY_PATTERN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenlei/gpt_academic/toolbox.py", line 829, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config_private'), arg)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config_private'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chenlei/gpt_academic/main.py", line 448, in <module>
    main()
  File "/Users/chenlei/gpt_academic/main.py", line 79, in main
    cookies = gr.State(load_chat_cookies())
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/chenlei/gpt_academic/toolbox.py", line 672, in load_chat_cookies
    API_KEY, LLM_MODEL, AZURE_API_KEY = get_conf('API_KEY', 'LLM_MODEL', 'AZURE_API_KEY')
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenlei/gpt_academic/toolbox.py", line 862, in get_conf
    r = read_single_conf_with_lru_cache(arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenlei/gpt_academic/toolbox.py", line 843, in read_single_conf_with_lru_cache
    if is_any_api_key(r):
       ^^^^^^^^^^^^^^^^^
  File "/Users/chenlei/gpt_academic/toolbox.py", line 722, in is_any_api_key
    return is_openai_api_key(key) or is_api2d_key(key) or is_azure_api_key(key)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenlei/gpt_academic/toolbox.py", line 700, in is_openai_api_key
    CUSTOM_API_KEY_PATTERN = get_conf('CUSTOM_API_KEY_PATTERN')
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenlei/gpt_academic/toolbox.py", line 862, in get_conf
    r = read_single_conf_with_lru_cache(arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chenlei/gpt_academic/toolbox.py", line 832, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config'), arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'config' has no attribute 'CUSTOM_API_KEY_PATTERN'

**Comment by Aleix-Chen** [comment]
已解决，在config.py文件中添加自定义APi即可
CUSTOM_API_KEY_PATTERN = ""
