### ISSUE TITLE
[Bug]: Mac一键安装的问题

### ISSUE THREAD

**Issue by cyx951211** [binary-husky/gpt_academic#1314]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-mac)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

Traceback (most recent call last):
  File "/Users/tim/Downloads/GPTAcademic/gpt_academic/main.py", line 448, in <module>
    main()
  File "/Users/tim/Downloads/GPTAcademic/gpt_academic/main.py", line 6, in main
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Screen Shot | 有帮助的截图

<img width="570" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/56212264/c6b375e2-e6a5-4873-8986-748a5e175a6b">

**Comment by binary-husky** [comment]
重新安装
