### ISSUE TITLE
[Bug]: 理解pdf的奇怪错误

### ISSUE THREAD

**Issue by forever-lwy** [binary-husky/gpt_academic#1327]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

运行时每总结一段内容，就会报下面的错误一次，但重试过后下面一段又能继续总结，总结完后又会出现下面的错误，这样一直重复。但是最后能完成任务，非常奇怪。

### Screen Shot | 有帮助的截图

Traceback (most recent call last):
  File ".\crazy_functions\crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\bridge_all.py", line 626, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\bridge_chatgpt.py", line 132, in predict_no_ui_long_connection
    else: raise RuntimeError("意外Json结构："+delta)
                             ~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "dict") to str

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binary-husky** [comment]
也许是第三方的兼容性问题，可把第三方样本api发我测试一下 qq505030475
