### ISSUE TITLE
[Bug]: 精准翻译PDF文档(NOUGAT)功能出错，

### ISSUE THREAD

**Issue by bengizh** [binary-husky/gpt_academic#1328]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

测试服务器，精准翻译PDF文档(NOUGAT)功能出错，但是可以使用精准翻译PDF的功能

![image](https://github.com/binary-husky/gpt_academic/assets/51499671/b9a0db8c-282a-4e02-a527-97fcf63eaaa0)

报错信息如下
![image](https://github.com/binary-husky/gpt_academic/assets/51499671/b40e4d8b-ade9-4e27-86e5-75f6027fbbb0)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/51499671/ac4995d5-0a68-433b-aa44-2b3c82bbc1e3)
Traceback (most recent call last):
  File "./toolbox.py", line 159, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/批量翻译PDF文档_NOUGAT.py", line 93, in 批量翻译PDF文档
    yield from 解析PDF_基于NOUGAT(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File "./crazy_functions/批量翻译PDF文档_NOUGAT.py", line 111, in 解析PDF_基于NOUGAT
    fpp = yield from nougat_handle.NOUGAT_parse_pdf(fp, chatbot, history)
  File "./crazy_functions/crazy_utils.py", line 761, in NOUGAT_parse_pdf
    raise RuntimeError("Nougat解析论文失败。")
RuntimeError: Nougat解析论文失败。

**Comment by yupenggit** [comment]
我也遇到了，是因为用了cpu卷积比较慢，超时了。去/crazy_functions/crazy_utils.py", line 723，line752，把3600（一小时）改大。
