### ISSUE TITLE
[Bug]: 知识库插件异常

### ISSUE THREAD

**Issue by xiao-yuling** [binary-husky/gpt_academic#1334]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

知识库问答
TypeError: 'HuggingFaceEmbeddings' object is not callable

 [Local Message] 插件调用出错:

Traceback (most recent call last):
  File ".\toolbox.py", line 156, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Langchain知识库.py", line 96, in 读取知识库作答
    resp, prompt = kai.answer_with_archive_by_id(txt, kai_id)
  File ".\crazy_functions\crazy_utils.py", line 706, in answer_with_archive_by_id
    resp, prompt = self.qa_handle.get_knowledge_based_conent_test(
  File "C:\Users\pc\AppData\Roaming\Python\Python310\site-packages\zh_langchain\chains\local_doc_qa.py", line 238, in get_knowledge_based_conent_test
    embedding = self.vector_store.embedding_function(query)
TypeError: 'HuggingFaceEmbeddings' object is not callable

 

当前代理可用性:

代理配置 无, 代理所在地：Japan

### Screen Shot | 有帮助的截图

![QQ图片20231128132359](https://github.com/binary-husky/gpt_academic/assets/110828598/973c25eb-7379-4b20-b677-14f66086e42d)

**Comment by danfouer** [comment]
I met exactly the same problem:
```
Traceback (most recent call last):
  File ".\toolbox.py", line 156, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Langchain知识库.py", line 96, in 读取知识库作答
    resp, prompt = kai.answer_with_archive_by_id(txt, kai_id)
  File ".\crazy_functions\crazy_utils.py", line 706, in answer_with_archive_by_id
    resp, prompt = self.qa_handle.get_knowledge_based_conent_test(
  File "D:\ProgramData\anaconda3\envs\gptac\lib\site-packages\zh_langchain\chains\local_doc_qa.py", line 238, in get_knowledge_based_conent_test
    embedding = self.vector_store.embedding_function(query)
TypeError: 'HuggingFaceEmbeddings' object is not callable
```
```
文件加载完毕，正在生成向量库
Batches: 100%|██████████| 42/42 [00:06<00:00,  6.13it/s]
代理配置 http://127.0.0.1:7890, 代理所在地：Japan - Google LLC
 gpt-3.5-turbo : 0 : 'HuggingFaceEmbeddings' object is not callable ..........
 gpt-3.5-turbo : 1 :  File "D:\ProgramData\anaconda3\envs\gptac\lib\site-packages\zh_langchain\chains\local_doc_qa.py", l ..........
 gpt-3.5-turbo : 2 : Traceback (most recent call last):
  File ".\toolbox.py", line 156, in decorated
    yield from f(ma ..........
```

**Comment by SonixLegend** [comment]
from langchain_core.embeddings import Embeddings
if isinstance(self.vector_store.embedding_function, Embeddings):
    embedding = self.vector_store.embedding_function.embed_query(s)
else:
    embedding = self.vector_store.embedding_function(s)

**Comment by xiao-yuling** [comment]
@binary-husky
