### ISSUE TITLE
[Bug]: gpt_academic使用的"内部优化gradio"不支持share link到gradio.live的功能

### ISSUE THREAD

**Issue by 2catycm** [binary-husky/gpt_academic#1346]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

需求的背景：
我在Linux服务器（没有UI）上运行服务，然后使用ssh端口转发（Vscode自带功能），来让Windows笔记本可以访问，然而这样是不行的，这是gradio在这个3.x版本的一个bug，访问localhost文件会加载不出来，会有网络错误（gradio已知显示loading，使用f12开发工具可以看到）。
这个不是你们魔改版gradio的问题，而是这个时期的gradio包都有的问题，我在很多项目都遇到了。
所以折中办法一般是使用share=True。这样gradio会生成一个公网连接，就可以成功访问了。

在main.py, 修改
demo.queue(concurrency_count=CONCURRENT_COUNT).launch(
        quiet=True,
        server_name="0.0.0.0", 
        ssl_keyfile=None if SSL_KEYFILE == "" else SSL_KEYFILE,
        ssl_certfile=None if SSL_CERTFILE == "" else SSL_CERTFILE,
        ssl_verify=False,
        server_port=PORT,
        favicon_path=os.path.join(os.path.dirname(__file__), "docs/logo.png"), 
        auth=AUTHENTICATION if len(AUTHENTICATION) != 0 else None,
        blocked_paths=["config.py","config_private.py","docker-compose.yml","Dockerfile",f"{PATH_LOGGING}/admin"])

加上参数 share=True

然而，由于你们的是魔改版gradio，所以不支持这个操作。

### Screen Shot | 有帮助的截图

在修改了share=True后重新运行，
首先出现报错（见终端traceback），然后如果打开url，会出现如下截图
![image](https://github.com/binary-husky/gpt_academic/assets/41530341/9ff46c3a-e9bd-4913-97fc-364fea1e558a)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

完整报错如下：
```bash
如果浏览器没有自动打开，请复制并转到以下URL：
        「暗色主题已启用（支持动态切换主题）」: http://localhost:42645
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/repos/gpt_academic/themes/default.py", line 73, in gradio_new_template_fn
    res = gradio_original_template_fn(*args, **kwargs)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/repos/gpt_academic/themes/default.py", line 73, in gradio_new_template_fn
    res = gradio_original_template_fn(*args, **kwargs)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/repos/gpt_academic/themes/default.py", line 73, in gradio_new_template_fn
    res = gradio_original_template_fn(*args, **kwargs)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/repos/gpt_academic/themes/default.py", line 73, in gradio_new_template_fn
    res = gradio_original_template_fn(*args, **kwargs)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/repos/gpt_academic/themes/default.py", line 73, in gradio_new_template_fn
    res = gradio_original_template_fn(*args, **kwargs)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
Running on local URL:  http://0.0.0.0:42645
正在执行一些模块的预热...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 251, in main
    return templates.TemplateResponse(
  File "/repos/gpt_academic/themes/default.py", line 73, in gradio_new_template_fn
    res = gradio_original_template_fn(*args, **kwargs)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 112, in TemplateResponse
    template = self.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/templating.py", line 94, in get_template
    return self.env.get_template(name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: frontend/share.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/miniconda3/envs/my_env/lib/python3.9/site-packages/gradio/routes.py", line 257, in main
    raise ValueError(
ValueError: Did you install Gradio from source files? Share mode only works when Gradio is installed through the pip package.
自动更新程序：已禁用。建议排查：代理网络配置。
Running on public URL: https://ed43ac62029b73ade1.gradio.live
```

**Comment by binary-husky** [comment]
“我在Linux服务器（没有UI）上运行服务，然后使用ssh端口转发（Vscode自带功能），来让Windows笔记本可以访问”

我们一直以来都是相同方法开发的，没遇到任何问题。请提供具体的信息吧。建议检查下vscode的port forwarding是否正确。你重启下电脑试试

**Comment by binary-husky** [comment]
please re-open this issue if you have further problems
