### ISSUE TITLE
[Bug]: AssertionError: Cannot find documentclass statement!

### ISSUE THREAD

**Issue by Smother1** [binary-husky/gpt_academic#1393]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

使用Arxiv论文原生翻译出现错误

[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "./toolbox.py", line 163, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/Latex输出PDF结果.py", line 285, in Latex翻译中文并重新编译PDF
    yield from Latex精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs,
  File "./crazy_functions/latex_fns/latex_actions.py", line 230, in Latex精细分解与转化
    merged_content = merge_tex_files(project_folder, content, mode)
  File "./crazy_functions/latex_fns/latex_toolbox.py", line 331, in merge_tex_files
    assert match is not None, "Cannot find documentclass statement!"
AssertionError: Cannot find documentclass statement!

### Screen Shot | 有帮助的截图

-

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

https://arxiv.org/abs/2201.02767

**Comment by sihaoo1** [comment]
我也遇到了这个问题，是找错了主文件导致的。在find_main_tex_file里找主文件的方法不能cover所有的情况，
<img width="852" alt="image" src="https://github.com/user-attachments/assets/35a08d1b-aabd-4e5f-8b83-fe72c40a68a3">

我这里第二个才是主文件
<img width="803" alt="Screenshot 2024-10-02 at 4 30 19 PM" src="https://github.com/user-attachments/assets/65ae04bf-3b49-4f8e-bf3a-b1c291015c65">

<img width="799" alt="image" src="https://github.com/user-attachments/assets/8e454b90-b081-47c5-a421-a84dc728bcc7">

**所以是不是可以考虑找失败的情况下允许输入主文件名称？**
