### ISSUE TITLE
[Bug]: 我刚刚已经运行起来了 但是把网页关了之后 在运行他又显示我的gradio模块没装好....我之前已经把他装好了并且可以成功运行请问大家之后应该怎么操作      感谢！！

### ISSUE THREAD

**Issue by Nixizfan** [binary-husky/gpt_academic#1406]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

 我刚刚已经运行起来了 但是把网页关了之后 在运行他又显示我的gradio模块没装好....我之前已经把他装好了并且可以成功运行。但是关掉网页之后还是显示

Traceback (most recent call last):
  File "D:\gpt_academic-master\main.py", line 407, in <module>
    main()
  File "D:\gpt_academic-master\main.py", line 17, in main
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Screen Shot | 有帮助的截图

Traceback (most recent call last):
  File "D:\gpt_academic-master\main.py", line 407, in <module>
    main()
  File "D:\gpt_academic-master\main.py", line 17, in main
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

麻烦大家了   感谢！！

**Comment by binary-husky** [comment]
重复issue 1403
