### ISSUE TITLE
[Bug]: [Local Message] 插件调用出错:

### ISSUE THREAD

**Issue by 19zhs19** [binary-husky/gpt_academic#1407]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用翻译pdf的时候一开始可以正常翻译，翻译开始一段时间后就报错
ValueError: not enough values to unpack (expected 2, got 1)

### Screen Shot | 有帮助的截图

[Local Message] 插件调用出错:

Traceback (most recent call last):
  File ".\toolbox.py", line 158, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\批量翻译PDF文档_多线程.py", line 51, in 批量翻译PDF文档
    yield from 解析PDF_基于GROBID(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt, grobid_url)
  File ".\crazy_functions\批量翻译PDF文档_多线程.py", line 73, in 解析PDF_基于GROBID
    yield from translate_pdf(article_dict, llm_kwargs, chatbot, fp, generated_conclusion_files, TOKEN_LIMIT_PER_FRAGMENT, DST_LANG)
  File ".\crazy_functions\pdf_fns\parse_pdf.py", line 123, in translate_pdf
    section_frags = break_down(section['text'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\pdf_fns\parse_pdf.py", line 111, in break_down
    raw_token_num = get_token_num(txt)
                    ^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\pdf_fns\parse_pdf.py", line 108, in get_token_num
    def get_token_num(txt): return len(enc.encode(txt, disallowed_special=()))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\bridge_all.py", line 46, in encode
    encoder = self.get_encoder(self.model)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\bridge_all.py", line 41, in get_encoder
    tmp = tiktoken.encoding_for_model(model)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\tiktoken\model.py", line 97, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\tiktoken\registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\tiktoken\load.py", line 124, in load_tiktoken_bpe
    return {
           ^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\tiktoken\load.py", line 126, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
        ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

 

当前代理可用性:

代理配置 无, 代理所在地：China - CERNET2 IX at University of Electronic Science and Technology of China

**Comment by binary-husky** [comment]
似乎与本项目无关
https://github.com/langchain-ai/langchain/issues/3351
https://github.com/openai/tiktoken/issues/114

**Comment by 19zhs19** [comment]
> 似乎与本项目无关 [langchain-ai/langchain#3351](https://github.com/langchain-ai/langchain/issues/3351) [openai/tiktoken#114](https://github.com/openai/tiktoken/issues/114)

函数调用失败，能够正常问答但是想要使用任何函数插件就会出现这个问题，我除了改了代理地址其他代码都没有动过了
![D$7U)K9CHG2RXJXMBFJD6FO](https://github.com/binary-husky/gpt_academic/assets/138569812/5f005be2-e841-47a4-b8ee-bee472b7b674)
