### ISSUE TITLE
[Bug]: 运行不了

### ISSUE THREAD

**Issue by Nixizfan** [binary-husky/gpt_academic#1408]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

运行不了麻烦大佬们救救孩子谢谢！！

### Screen Shot | 有帮助的截图

D:\gpt_academic-master>python main.py
Traceback (most recent call last):
  File "D:\gpt_academic-master\main.py", line 407, in <module>
    main()
  File "D:\gpt_academic-master\main.py", line 17, in main
    import gradio as gr
  File "D:\anaconda2\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\anaconda2\Lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\anaconda2\Lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "D:\anaconda2\Lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\anaconda2\Lib\site-packages\gradio\components\annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "D:\anaconda2\Lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "D:\anaconda2\Lib\site-packages\gradio\data_classes.py", line 19, in <module>
    from pydantic import BaseModel, RootModel, ValidationError  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'RootModel' from 'pydantic' (D:\anaconda2\Lib\site-packages\pydantic\__init__.cp311-win_amd64.pyd)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

D:\gpt_academic-master>python main.py
Traceback (most recent call last):
  File "D:\gpt_academic-master\main.py", line 407, in <module>
    main()
  File "D:\gpt_academic-master\main.py", line 17, in main
    import gradio as gr
  File "D:\anaconda2\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\anaconda2\Lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\anaconda2\Lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "D:\anaconda2\Lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\anaconda2\Lib\site-packages\gradio\components\annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "D:\anaconda2\Lib\site-packages\gradio\processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "D:\anaconda2\Lib\site-packages\gradio\data_classes.py", line 19, in <module>
    from pydantic import BaseModel, RootModel, ValidationError  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'RootModel' from 'pydantic' (D:\anaconda2\Lib\site-packages\pydantic\__init__.cp311-win_amd64.pyd)

**Comment by Nixizfan** [comment]
大佬救命

**Comment by binary-husky** [comment]
先试试一键安装脚本

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/releases/download/version3.64-1/OneKeyInstallerForWindowsAndMacOS.zip

**Comment by Nixizfan** [comment]
哥们这个怎么装有教程吗
