### ISSUE TITLE
[Bug]: 配置环境按教程来但是最后运行不起来

### ISSUE THREAD

**Issue by Nixizfan** [binary-husky/gpt_academic#1434]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

东西都安上了但是运行不起来

### Screen Shot | 有帮助的截图

Traceback (most recent call last):
  File "D:\OneKeyInstallerForWindowsAndMacOS\gpt_academic\main.py", line 407, in <module>
    main()
  File "D:\OneKeyInstallerForWindowsAndMacOS\gpt_academic\main.py", line 19, in main
    raise ModuleNotFoundError("使用项目内置Gradio获取最优体验! 请运行 `pip install -r requirements.txt` 指令安装内置Gradio及其他依赖, 详情信息见requirements.txt.")
ModuleNotFoundError: 使用项目内置Gradio获取最优体验! 请运行 `pip install -r requirements.txt` 指令安装内置Gradio及其他依赖, 详情信息见requirements.txt.

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

这个是运行后的报错

**Comment by Nixizfan** [comment]
麻烦各位看一下！感谢！！

**Comment by Nixizfan** [comment]
输入了 pip install -r requirements.txt 之后报错是这样的ImportError: cannot import name 'RootModel' from 'pydantic' (D:\1anaconda\Lib\site-packages\pydantic\__init__.cp311-win_amd64.pyd)

**Comment by binary-husky** [comment]
无法用一键安装脚本复现此问题

**Comment by Nixizfan** [comment]
已解决感谢！！

**Comment by seacatchit** [comment]
怎么解决的
