### ISSUE TITLE
[Bug]: 页面布局出错

### ISSUE THREAD

**Issue by Nari-J** [binary-husky/gpt_academic#1435]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

反复尝试了一键安装和下载项目后自己安装，都会出现如图现象。切换使用了google和edge浏览器的无痕模式，无法解决。功能似乎可以正常使用，但是整个页面布局十分混乱。
自己安装运行后有一段如下报错信息：（一键安装运行时不报错
Traceback (most recent call last):
  File "D:\gpt_academic\venv\Lib\site-packages\gradio\routes.py", line 421, in run_predict
    with utils.MatplotlibBackendMananger():
  File "D:\gpt_academic\venv\Lib\site-packages\gradio\utils.py", line 785, in __exit__
    matplotlib.use(self._original_backend)
  File "D:\gpt_academic\venv\Lib\site-packages\matplotlib\__init__.py", line 1262, in use
    plt.switch_backend(name)
  File "D:\gpt_academic\venv\Lib\site-packages\matplotlib\pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/60738844/da57f21f-d96c-4d49-ae4c-1dfa4bfd2d9a)
![image](https://github.com/binary-husky/gpt_academic/assets/60738844/c4343c0d-2cbb-42f1-853f-12ad5de301cc)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

[PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。 
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
代理配置 无, 代理所在地：China
 [API_KEY] 本项目现已支持OpenAI和Azure的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,azure-key3" 
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。 
 [API_KEY] 您的 API_KEY 是: sk-98nWBLeCxEg*** API_KEY 导入成功 
如果浏览器没有自动打开，请复制并转到以下URL：
	「暗色主题已启用（支持动态切换主题）」: http://localhost:51660
自动更新程序：已禁用。建议排查：代理网络配置。
Running on local URL:  http://0.0.0.0:51660
Traceback (most recent call last):
  File "D:\gpt_academic\venv\Lib\site-packages\gradio\routes.py", line 421, in run_predict
    with utils.MatplotlibBackendMananger():
  File "D:\gpt_academic\venv\Lib\site-packages\gradio\utils.py", line 785, in __exit__
    matplotlib.use(self._original_backend)
  File "D:\gpt_academic\venv\Lib\site-packages\matplotlib\__init__.py", line 1262, in use
    plt.switch_backend(name)
  File "D:\gpt_academic\venv\Lib\site-packages\matplotlib\pyplot.py", line 343, in switch_backend
    canvas_class = module.FigureCanvas
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
正在执行一些模块的预热 ...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
 gpt-3.5-turbo : 0 : 1+1== ..........

**Comment by yy306525121** [comment]
我也报了这个错，把matplotlib降到3.5.0之后没报错了
