### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问。: 'gpt_log'[Bug]: 

### ISSUE THREAD

**Issue by yooyoo1988** [binary-husky/gpt_academic#1453]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

[PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'http://127.0.0.1:8889', 'https': 'http://127.0.0.1:8889'}
Traceback (most recent call last):
  File "D:\Program Files (x86)\gpt_academic-master\main.py", line 406, in <module>
    main()
  File "D:\Program Files (x86)\gpt_academic-master\main.py", line 39, in main
    os.makedirs(PATH_LOGGING, exist_ok=True)
  File "D:\anaconda\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] 拒绝访问。: 'gpt_log'

### Screen Shot | 有帮助的截图

[PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'http://127.0.0.1:8889', 'https': 'http://127.0.0.1:8889'}
Traceback (most recent call last):
  File "D:\Program Files (x86)\gpt_academic-master\main.py", line 406, in <module>
    main()
  File "D:\Program Files (x86)\gpt_academic-master\main.py", line 39, in main
    os.makedirs(PATH_LOGGING, exist_ok=True)
  File "D:\anaconda\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] 拒绝访问。: 'gpt_log'

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

[PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'http://127.0.0.1:8889', 'https': 'http://127.0.0.1:8889'}
Traceback (most recent call last):
  File "D:\Program Files (x86)\gpt_academic-master\main.py", line 406, in <module>
    main()
  File "D:\Program Files (x86)\gpt_academic-master\main.py", line 39, in main
    os.makedirs(PATH_LOGGING, exist_ok=True)
  File "D:\anaconda\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] 拒绝访问。: 'gpt_log'

**Comment by binary-husky** [comment]
修改文件夹权限即可
