### ISSUE TITLE
[Bug]: 精确翻译PDF文档（NOUGAT）功能失效

### ISSUE THREAD

**Issue by August-L-J** [binary-husky/gpt_academic#1479]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Others | 非最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

gpt_academic版本是：3.64
使用```精确翻译PDF文档（NOUGAT）```的时候很慢，说我没有GPU，在CPU上面跑很慢？我电脑是轻薄本，不过是能跑深度学习的代码，虽然只能进行比较简单的推理代码，但是也是有GPU的

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/75567677/d506c085-338d-449e-8537-72faea7398d2)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

终端的报错信息如下：
```[PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'} 
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
代理配置 http://127.0.0.1:7890, 代理所在地：未知，IP查询频率受限
 [API_KEY] 本项目现已支持OpenAI和Azure的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,azure-key3" 
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。 
 [API_KEY] 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。 
如果浏览器没有自动打开，请复制并转到以下URL：
	「暗色主题已启用（支持动态切换主题）」: http://localhost:53729
 
新版本可用。新版本:3.65，当前版本:3.64。新功能：支持Gemini-pro <-> 支持直接拖拽文件到上传区 <-> 支持将图片粘贴到输入区 <-> 修复若干隐蔽的内存BUG <-> 修复多用户冲突问题 <-> 接入Deepseek Coder <-> AutoGen多智能体插件测试版 
（1）Github更新地址:
https://github.com/binary-husky/chatgpt_academic
（2）是否一键更新代码（Y+回车=确认，输入其他/无输入+回车=不更新）？Running on local URL:  http://0.0.0.0:53729
正在执行一些模块的预热 ...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
 gpt-3.5-turbo : 0 : bninih  ..........
WARNING:root:No GPU found. Conversion on CPU is very slow.
D:\Anaconda\envs\gptac_venv_1\Lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|          | 0/10 [00:00<?, ?it/s]>? 
自动更新程序：已禁用
INFO:root:Processing file D:\Python_Code\gpt_academic-master\gpt_academic-master\private_upload\default_user\2024-01-16-14-47-29\Liu 等 - Low-Light Image Enhancement with Multi-Stage Residue Quantization and Brightness-Aware Attention.pdf with 10 pages
 10%|█         | 1/10 [04:57<44:34, 297.15s/it][nltk_data] Downloading package words to
[nltk_data]     C:\Users\Jack\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\words.zip.
 80%|████████  | 8/10 [57:41<13:53, 416.53s/it]Process timed out!
代理配置 http://127.0.0.1:7890, 代理所在地：未知，IP查询频率受限
100%|██████████| 10/10 [1:17:21<00:00, 464.14s/it]
-> Cannot close object, library is destroyed. This may cause a memory leak!

```

gpt_academic的报错信息如下：
```
Traceback (most recent call last):
  File ".\toolbox.py", line 158, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\批量翻译PDF文档_NOUGAT.py", line 93, in 批量翻译PDF文档
    yield from 解析PDF_基于NOUGAT(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File ".\crazy_functions\批量翻译PDF文档_NOUGAT.py", line 111, in 解析PDF_基于NOUGAT
    fpp = yield from nougat_handle.NOUGAT_parse_pdf(fp, chatbot, history)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\crazy_utils.py", line 588, in NOUGAT_parse_pdf
    raise RuntimeError("Nougat解析论文失败。")
RuntimeError: Nougat解析论文失败。
```

**Comment by binary-husky** [comment]
NOUGAT是需要用GPU跑的

**Comment by Jack-Liu0227** [comment]
请问怎么用GPU跑呢

**Comment by RexLeeGrey** [comment]
我4090都报错

**Comment by longxiaotian799** [comment]
> 请问怎么用GPU跑呢

用Google colab，一般的笔记本GPU都不太行
