### ISSUE TITLE
[Bug]: 一直无法成功运行

### ISSUE THREAD

**Issue by lxqHolly** [binary-husky/gpt_academic#1542]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

一键安装，无法成功运行

### Screen Shot | 有帮助的截图

Traceback (most recent call last):
  File "F:\GPT\OneKeyInstallerForWindowsAndMacOS\gpt_academic\main.py", line 406, in <module>
    main()
  File "F:\GPT\OneKeyInstallerForWindowsAndMacOS\gpt_academic\main.py", line 17, in main
    import gradio as gr
  File "F:\GPT\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "F:\GPT\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio\components.py", line 37, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (F:\GPT\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\site-packages\gradio_client\documentation.py)

**Comment by cy190928** [comment]
我也遇到了同样的问题

Traceback (most recent call last):
  File "D:\gpt_academic-version3.70\main.py", line 406, in <module>
    main()
  File "D:\gpt_academic-version3.70\main.py", line 17, in main
    import gradio as gr
  File "D:\gpt_academic-version3.70\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\gpt_academic-version3.70\venv\lib\site-packages\gradio\components.py", line 37, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (D:\gpt_academic-version3.70\venv\lib\site-packages\gradio_client\documentation.py)

**Comment by hong-xu-king** [comment]
Traceback (most recent call last):
  File "E:\project\python_project\gpt_academic-version3.56\gpt_academic-version3.56\main.py", line 448, in <module>
    main()
  File "E:\project\python_project\gpt_academic-version3.56\gpt_academic-version3.56\main.py", line 6, in main
    import gradio as gr
  File "C:\Users\jinhongxu\.conda\envs\chatgpt\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\jinhongxu\.conda\envs\chatgpt\Lib\site-packages\gradio\components.py", line 37, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation'
我也是 换了三个版本都不行

**Comment by liangxx29** [comment]
我换了版本就报错，用requirements的版本又报错。到底怎么解决？给各位大佬磕头了

**Comment by pepperbubble** [comment]
版本问题
pip install gradio_client==0.8.1

**Comment by LiangSiyv** [comment]
> 版本问题 pip install gradio_client==0.8.1

太及时了

**Comment by t7946** [comment]
太感谢了！！一直报这个错误，重装几次都不行，这下解决了！

**Comment by binary-husky** [comment]
谢谢提醒 ，与前天发的gradio-client更新有关

https://github.com/binary-husky/gpt_academic/pull/1548

**Comment by binary-husky** [comment]
请测试是否修复？
