### ISSUE TITLE
[Bug]: localhost访问被拒绝

### ISSUE THREAD

**Issue by 91mrhu** [binary-husky/gpt_academic#1567]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

安装完成后运行无法打开网页 显示访问被拒绝
换成localhost或127.0.0.1都不行
edge Firefox Chrome都不行
按其他回答内设置隐私模式也不行

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/49473595/017130ea-c752-4739-9589-f70a69ad03b8)
![image](https://github.com/binary-husky/gpt_academic/assets/49473595/bab42514-1e79-4380-b545-2c44c58dc3a1)
![image](https://github.com/binary-husky/gpt_academic/assets/49473595/c271c7a4-0f0c-4892-bc34-dd68eeaff723)
![image](https://github.com/binary-husky/gpt_academic/assets/49473595/a60ceb3c-4c0f-49e9-a9a4-cfee37f4307c)

**Comment by 91mrhu** [comment]
2024-02-21 15:39:48 ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=2020, family=2, type=1, proto=6, laddr=('0.0.0.0', 64107)>
Traceback (most recent call last):
  File "C:\Users\36971\.conda\envs\gptac4\Lib\asyncio\proactor_events.py", line 843, in loop
    conn, addr = f.result()
                 ^^^^^^^^^^
  File "C:\Users\36971\.conda\envs\gptac4\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\36971\.conda\envs\gptac4\Lib\asyncio\windows_events.py", line 595, in finish_accept
    return conn, conn.getpeername()
                 ^^^^^^^^^^^^^^^^^^
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
2024-02-21 15:39:48 ERROR    Task exception was never retrieved
future: <Task finished name='Task-7' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at C:\Users\36971\.conda\envs\gptac4\Lib\asyncio\windows_events.py:597> exception=OSError(14, '系统检测到在一个调用中尝试使用指针参数时的无效指针地址。', None, 10014, None)>
Traceback (most recent call last):
  File "C:\Users\36971\.conda\envs\gptac4\Lib\asyncio\windows_events.py", line 600, in accept_coro
    await future
OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

**Comment by binary-husky** [comment]
无法复现，请尝试一键安装脚本
