### ISSUE TITLE
[Bug]: 使用 `copilot-gpt4-service` 第三方 GPT4 API 时出现 `UnboundLocalError` 错误

### ISSUE THREAD

**Issue by WindowsSov8forUs** [binary-husky/gpt_academic#1638]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在使用由项目 `Copilot-GPT4-Service` 构建的第三方 GPT4 时出现问题
在问题出现之前更新到的 3.73 版本，且当时并未出现这种问题
从 Copilot-GPT4-Service 记录的日志来看根本没有接收到来自 gpt-academic 的请求

应该可以排除由于端口指定错误或 key 指定错误导致的情况

### Screen Shot | 有帮助的截图

![T1QM{M}FD8UX6)}I$) CX$8](https://github.com/binary-husky/gpt_academic/assets/68172940/bf4e75f9-9f4e-4db0-9852-60565be097b4)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

```bash
Traceback (most recent call last):
  File "D:\gpt_academic\request_llms\bridge_chatgpt.py", line 224, in predict
    chunk = next(stream_response)
            ^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qwert\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\gpt_academic\toolbox.py", line 122, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "D:\gpt_academic\request_llms\bridge_all.py", line 870, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "D:\gpt_academic\request_llms\bridge_chatgpt.py", line 227, in predict
    chunk_decoded = chunk.decode()
                    ^^^^^
UnboundLocalError: cannot access local variable 'chunk' where it is not associated with a value
```

**Comment by WindowsSov8forUs** [comment]
所有的 gpt 模型都试过了，无一例外，所以应该也可以排除 gpt 模型选择的问题

**Comment by WindowsSov8forUs** [comment]
问题似乎得到了解决

目前查到的原因是，使用的代理 `Clash for Windows` 的配置似乎并不能很好地处理使用代理服务器访问本地服务器地址的情况，导致当我通过 `4096` 端口代理服务器访问本地 `5000` 端口 `Copilot-GPT4-Service` 服务时，请求并没有正确地被转发给 `Copilot-GPT4-Service` 服务，导致请求收到了空白的响应，使得 `chunk = next(stream_response)` 在第一次迭代就抛出了 `StopIteration` 错误，而此时 `chunk` 并没有被赋值，导致出现了 `UnboundLocalError`

我对 `request_llms/bridge_chatgpt.py` 的 `predict` 函数进行了修改，添加了一个函数判断是否为本地服务器请求
```python
def _is_local_url(url: str) -> bool:
    _url = urlparse(url)
    return _url.hostname in ('localhost', '127.0.0.1')
````

并修改了函数中发送请求的语句
```python
# make a POST request to the API endpoint, stream=True
# 尝试判断是否为本地连接
if _is_local_url(endpoint):
    response = requests.post(endpoint, headers=headers,
    json=payload, stream=True, timeout=TIMEOUT_SECONDS);break
else:
    response = requests.post(endpoint, headers=headers, proxies=proxies,
    json=payload, stream=True, timeout=TIMEOUT_SECONDS);break
```

通过这种方式临时地解决了问题，但是并不确定是否从根本上解决了问题的源头
问题的本质还是在于 `Clash for Windows`

**Comment by AppleRiven** [comment]
请问如何配置接入copilot模型呀？
