### ISSUE TITLE
[Bug]: OpenAI拒绝了请求

### ISSUE THREAD

**Issue by SSR-Qian** [binary-husky/gpt_academic#1655]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

配置采用的是第三方API-KEY接入 能正常进入界面  但是无法使用 
错误显示：
Traceback (most recent call last):
  File ".\crazy_functions\crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\bridge_all.py", line 826, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llms\bridge_chatgpt.py", line 120, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{"error":{"message":"bad response status code 402 (request id: 20240325184728649695482DeAGrzBU)","type":"upstream_error","param":"402","code":"bad_response_status_code"}}

### Screen Shot | 有帮助的截图

![微信截图_20240325185256](https://github.com/binary-husky/gpt_academic/assets/67669621/85e60e6f-c3f1-4527-8b43-94f5c665db49)

**Comment by Zhuo-ruishuang** [comment]
请问你的问题解决了吗？

**Comment by binaryYuki** [comment]
设置 redirect_url了吗？第三方中转 key 不能直接向openai 发送请求的
