### ISSUE TITLE
[Bug]: zhipuai相关："temperature参数非法。请检查文档。"

### ISSUE THREAD

**Issue by wl223600** [binary-husky/gpt_academic#1684]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

## 症状
在更改temperature值为(0,1)之间的小数时，会出现如下报错。
````
Traceback (most recent call last):
  File "./crazy_functions/crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_all.py", line 826, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_zhipu.py", line 36, in predict_no_ui_long_connection
    for chunk, response in zhipu_bro_init.generate_chat(inputs, llm_kwargs, history, sys_prompt):
  File "./request_llms/com_zhipuglm.py", line 77, in generate_chat
    response = self.__conversation_message_payload(inputs, llm_kwargs, history, system_prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/com_zhipuglm.py", line 67, in __conversation_message_payload
    response = self.zhipu_bro.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fatshibainu/.local/lib/python3.11/site-packages/zhipuai/api_resource/chat/completions.py", line 48, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/fatshibainu/.local/lib/python3.11/site-packages/zhipuai/core/_http_client.py", line 292, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "/home/fatshibainu/.local/lib/python3.11/site-packages/zhipuai/core/_http_client.py", line 251, in request
    raise self._make_status_error(err.response) from None
zhipuai.core._errors.APIRequestFailedError: Error code: 400, with error text {"error":{"code":"1214","message":"temperature参数非法。请检查文档。"}}
````

## 思考
原代码如下所示（com_zhipuglm.py）
````
# (line 67)
        response = self.zhipu_bro.chat.completions.create(
            model=self.model, messages=messages, stream=True,
            temperature=llm_kwargs.get('temperature', 0.95) * 0.95,  # 只能传默认的 temperature 和 top_p
            top_p=llm_kwargs.get('top_p', 0.7) * 0.7,
            max_tokens=llm_kwargs.get('max_tokens', 1024 * 4),  # 最大输出模型的一半
        )
````
官方文档内的````temperature````和````top_p````允许传入(0, 1)内的任意数值（注意为开区间），但个人猜测不允许传入三位以上小数。可以通过在UI内指定````temperature````为0.5（实际代码运算后应该为0.475）来复现此问题。
## 可能的解决方案
最直接的解决方法是使用````round()````。
如果直接去掉后面的````*0.95````和````*0.7````，则由于现有版本默认````temperature````和````top_p````默认值均为1（为非法值），导致直接与zhipuai对话时必然报错。
另外可能存在其他~~更优雅~~的解决办法。
````
# 非程序员，未实际检验过，可能存在逻辑错误
def preprocess_param(param, min_val=0.01, max_val=0.99):
    if param <= 0:
        return min_val
    elif param >= 1:
        return max_val
    else:
        return param

temperature = preprocess_param(llm_kwargs.get('temperature', 0.95))
top_p = preprocess_param(llm_kwargs.get('top_p', 0.7))
````

### Screen Shot | 有帮助的截图

~~None~~

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

~~见Description~~

**Comment by binary-husky** [comment]
#1687 
感谢反馈，pr已经merge
