### ISSUE TITLE
[Bug]: qianfan官方接口在22日都更新了，现在连接都失败了

### ISSUE THREAD

**Issue by zhoujianmin** [binary-husky/gpt_academic#1735]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Traceback (most recent call last):
  File ".\request_llms\bridge_qianfan.py", line 110, in generate_from_baidu_qianfan
    incoming = dec['result']
               ~~~^^^^^^^^^^
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\request_llms\bridge_qianfan.py", line 151, in predict
    for response in generate_from_baidu_qianfan(inputs, llm_kwargs, history, system_prompt):
  File ".\request_llms\bridge_qianfan.py", line 117, in generate_from_baidu_qianfan
    raise RuntimeError(dec['error_msg'])
RuntimeError: Open api daily request limit reached

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/25032690/ad6bb7f4-bce3-493a-82f0-0022d8046680)


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by wl223600** [comment]
## 提示
- 最新版gpt学术优化无法复现此问题
- 建议抓取最新版的源代码，根据提示重新安装依赖再试一次
## 测试平台与API
- gpt academic 3.74（20240427抓取，最近数个小版本有更新但是没改版本号）
- Debian 12
- 文心一言4
## 截图
![image](https://github.com/binary-husky/gpt_academic/assets/11728850/c27682fc-a458-4850-a0d3-6328b6aaf845)

**Comment by MuffinQAQ** [comment]
@wl223600 大神，没看明白你说的这个，能详细点吗？
