### ISSUE TITLE
[Bug]: DOC2X服务不可用。

### ISSUE THREAD

**Issue by xiaoWay** [binary-husky/gpt_academic#1767]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

按照配置说明配置了DOC2X的API KEY，然后出错了。有没有解决办法。
错误详情：
Traceback (most recent call last):
  File "./crazy_functions/PDF批量翻译.py", line 52, in 批量翻译PDF文档
    yield from 解析PDF_DOC2X(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt, DOC2X_API_KEY, user_request)
  File "./crazy_functions/PDF批量翻译.py", line 201, in 解析PDF_DOC2X
    yield from 解析PDF_DOC2X_单文件(fp, *args)
  File "./crazy_functions/PDF批量翻译.py", line 196, in 解析PDF_DOC2X_单文件
    md_zip_path = yield from pdf2markdown(fp)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./crazy_functions/PDF批量翻译.py", line 101, in pdf2markdown
    raise RuntimeError(format("[ERROR] status code: %d, body: %s" % (res.status_code, res.text)))
RuntimeError: [ERROR] status code: 401, body: {"code":"unauthorized","msg":"jwt expired or invalid"}

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/44190995/606cd912-952c-45cb-809b-ca257e081375)

**Comment by xiaoWay** [comment]
鉴权问题，官方希望更新一下docker拉取包：https://github.com/binary-husky/gpt_academic/pull/1766 这个PR第一种方法很好。
