### ISSUE TITLE
[BUG]将openai的链接重定向到本地部署报错SSL: UNEXPECTED_EOF_WHILE_READING

### ISSUE THREAD

**Issue by wwjCMP** [binary-husky/gpt_academic#1783]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

**Comment by wwjCMP** [comment]
2024-05-14 19:05:12 Traceback (most recent call last):
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
2024-05-14 19:05:12     self._validate_conn(conn)
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
2024-05-14 19:05:12     conn.connect()
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 653, in connect
2024-05-14 19:05:12     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
2024-05-14 19:05:12                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
2024-05-14 19:05:12     ssl_sock = ssl_wrap_socket(
2024-05-14 19:05:12                ^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
2024-05-14 19:05:12     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
2024-05-14 19:05:12                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
2024-05-14 19:05:12     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
2024-05-14 19:05:12     return self.sslsocket_class._create(
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/ssl.py", line 1104, in _create
2024-05-14 19:05:12     self.do_handshake()
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/ssl.py", line 1382, in do_handshake
2024-05-14 19:05:12     self._sslobj.do_handshake()
2024-05-14 19:05:12 ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
2024-05-14 19:05:12 
2024-05-14 19:05:12 During handling of the above exception, another exception occurred:
2024-05-14 19:05:12 
2024-05-14 19:05:12 Traceback (most recent call last):
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
2024-05-14 19:05:12     response = self._make_request(
2024-05-14 19:05:12                ^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
2024-05-14 19:05:12     raise new_e
2024-05-14 19:05:12 urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
2024-05-14 19:05:12 
2024-05-14 19:05:12 The above exception was the direct cause of the following exception:
2024-05-14 19:05:12 
2024-05-14 19:05:12 Traceback (most recent call last):
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
2024-05-14 19:05:12     resp = conn.urlopen(
2024-05-14 19:05:12            ^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
2024-05-14 19:05:12     retries = retries.increment(
2024-05-14 19:05:12               ^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
2024-05-14 19:05:12     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
2024-05-14 19:05:12     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.101.5', port=8006): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))
2024-05-14 19:05:12 
2024-05-14 19:05:12 During handling of the above exception, another exception occurred:
2024-05-14 19:05:12 
2024-05-14 19:05:12 Traceback (most recent call last):
2024-05-14 19:05:12   File "/gpt/request_llms/bridge_chatgpt.py", line 211, in predict
2024-05-14 19:05:12     response = requests.post(endpoint, headers=headers, proxies=proxies,
2024-05-14 19:05:12                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
2024-05-14 19:05:12     return request("post", url, data=data, json=json, **kwargs)
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
2024-05-14 19:05:12     return session.request(method=method, url=url, **kwargs)
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
2024-05-14 19:05:12     resp = self.send(prep, **send_kwargs)
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
2024-05-14 19:05:12     r = adapter.send(request, **kwargs)
2024-05-14 19:05:12         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
2024-05-14 19:05:12     raise SSLError(e, request=request)
2024-05-14 19:05:12 requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.101.5', port=8006): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)')))
2024-05-14 19:05:12 
2024-05-14 19:05:12 During handling of the above exception, another exception occurred:
2024-05-14 19:05:12 
2024-05-14 19:05:12 Traceback (most recent call last):
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 422, in run_predict
2024-05-14 19:05:12     output = await app.get_blocks().process_api(
2024-05-14 19:05:12              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1323, in process_api
2024-05-14 19:05:12     result = await self.call_function(
2024-05-14 19:05:12              ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1067, in call_function
2024-05-14 19:05:12     prediction = await utils.async_iteration(iterator)
2024-05-14 19:05:12                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 336, in async_iteration
2024-05-14 19:05:12     return await iterator.__anext__()
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 329, in __anext__
2024-05-14 19:05:12     return await anyio.to_thread.run_sync(
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-05-14 19:05:12     return await get_async_backend().run_sync_in_worker_thread(
2024-05-14 19:05:12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
2024-05-14 19:05:12     return await future
2024-05-14 19:05:12            ^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-05-14 19:05:12     result = context.run(func, *args)
2024-05-14 19:05:12              ^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
2024-05-14 19:05:12     return next(iterator)
2024-05-14 19:05:12            ^^^^^^^^^^^^^^
2024-05-14 19:05:12   File "/gpt/toolbox.py", line 128, in decorated
2024-05-14 19:05:12     yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
2024-05-14 19:05:12   File "/gpt/request_llms/bridge_all.py", line 1007, in predict
2024-05-14 19:05:12     yield from method(inputs, llm_kwargs, *args, **kwargs)
2024-05-14 19:05:12   File "/gpt/request_llms/bridge_chatgpt.py", line 218, in predict
2024-05-14 19:05:12     if retry > MAX_RETRY: raise TimeoutError
2024-05-14 19:05:12                           ^^^^^^^^^^^^^^^^^^
2024-05-14 19:05:12 TimeoutError
