### ISSUE TITLE
[Bug]: 在使用自定义菜单时出现问题

### ISSUE THREAD

**Issue by lingyezhixing** [binary-husky/gpt_academic#1804]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

自定义的按键无法使用，报错：KeyError: '自定义按钮1'。部署环境使用了python的venv。

### Screen Shot | 有帮助的截图

![屏幕截图 2024-05-18 135658](https://github.com/binary-husky/gpt_academic/assets/144504450/38d5e657-70b6-476f-978e-40d7b033b4b8)
![屏幕截图 2024-05-18 135712](https://github.com/binary-husky/gpt_academic/assets/144504450/4e6ce2d4-ad2c-4f63-b19f-4a78e0c09010)
![屏幕截图 2024-05-18 135842](https://github.com/binary-husky/gpt_academic/assets/144504450/def8bd08-1271-4021-a108-1eb702432511)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\LLM\gpt_academic\runtime\lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
  File "D:\LLM\gpt_academic\toolbox.py", line 128, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "D:\LLM\gpt_academic\request_llms\bridge_all.py", line 1051, in predict
    llm_kwargs, additional_fn, method = execute_model_override(llm_kwargs, additional_fn, method)
  File "D:\LLM\gpt_academic\request_llms\bridge_all.py", line 1014, in execute_model_override
    if 'ModelOverride' in functional[additional_fn]:
KeyError: '自定义按钮1'

**Comment by binary-husky** [comment]
谢谢反馈，已修复https://github.com/binary-husky/gpt_academic/commit/2ce448214663dba1dcdcae81c917cb2ea247d40c
