### ISSUE TITLE
[Bug]: 图片生产dall-

### ISSUE THREAD

**Issue by 626xiange714** [binary-husky/gpt_academic#1894]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Traceback (most recent call last):
  File ".\crazy_functions\图片生成.py", line 35, in gen_image
    image_url = json.loads(response.content.decode('utf8'))['data'][0]['url']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\toolbox.py", line 221, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\图片生成.py", line 146, in 图片生成_DALLE3
    image_url, image_path = gen_image(llm_kwargs, prompt, resolution, model="dall-e-3", quality=quality, style=style)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\图片生成.py", line 37, in gen_image
    raise RuntimeError(response.content.decode())
RuntimeError: {"error":{"message":"当前分组 default 下对于模型 dall-e-3 无可用渠道 (request id: 202407162049254826370154UyrQH96) (request id: 20240716204924128676952yzz2G407)","type":"503","param":"","code":null}}

### Screen Shot | 有帮助的截图

![Uploading 屏幕截图 2024-07-16 211204.png…]()


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binaryYuki** [comment]
您好 您用的第三方中转 请联系服务提供商 非本项目错误
