### ISSUE TITLE
python main.py 不能运行[Bug]: 

### ISSUE THREAD

**Issue by Huaichao2018** [binary-husky/gpt_academic#1897]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

网络代理状态：运行。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log，请注意自我隐私保护哦！
Traceback (most recent call last):
  File "/Users/mac/Downloads/chatgpt_academic-master/main.py", line 34, in <module>
    chatbot.style(height=1000)
    ^^^^^^^^^^^^^
AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?

### Screen Shot | 有帮助的截图

网络代理状态：运行。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log，请注意自我隐私保护哦！
Traceback (most recent call last):
  File "/Users/mac/Downloads/chatgpt_academic-master/main.py", line 34, in <module>
    chatbot.style(height=1000)
    ^^^^^^^^^^^^^
AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

网络代理状态：运行。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log，请注意自我隐私保护哦！
Traceback (most recent call last):
  File "/Users/mac/Downloads/chatgpt_academic-master/main.py", line 34, in <module>
    chatbot.style(height=1000)
    ^^^^^^^^^^^^^
AttributeError: 'Chatbot' object has no attribute 'style'. Did you mean: 'scale'?

**Comment by Huaichao2018** [comment]
我最后是这样解决的，python -m pip install gradio==3.28.3，之后再运行就可以了，应该是版本的问题，不要问我怎么发现的，看了很多问题后，悟到了
