### ISSUE TITLE
[Bug]: 您提供的api-key不满足要求，不包含任何可用于internvl2-40b的api-key。您可能选择了错误的模型或请求源。

### ISSUE THREAD

**Issue by lianqi1998** [binary-husky/gpt_academic#1933]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

使用第三方部署平台在本地搭建服务，接口地址为：http://127.0.0.1:5000/v1/chat/completions
已修改config_private.py：

`API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"http://127.0.0.1:5000/v1/chat/completions"}`
`API_KEY = "Sample"` 
`CUSTOM_API_KEY_PATTERN = "EMPTY"`
```
LLM_MODEL = "internvl2-40b" # 可选 ↓↓↓
AVAIL_LLM_MODELS = ["gpt-4-1106-preview", "gpt-4-turbo-preview", "gpt-4-vision-preview",
                    "gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-4-turbo-2024-04-09",
                    "gpt-3.5-turbo-1106", "gpt-3.5-turbo-16k", "gpt-3.5-turbo", "azure-gpt-3.5",
                    "gpt-4", "gpt-4-32k", "azure-gpt-4", "glm-4", "glm-4v", "glm-3-turbo",
                    "gemini-pro", "chatglm3","internvl2-40b"
                    ]
```
报错：

> Traceback (most recent call last):
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
>     result = await self.call_function(
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/gradio/blocks.py", line 1067, in call_function
>     prediction = await utils.async_iteration(iterator)
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/gradio/utils.py", line 336, in async_iteration
>     return await iterator.__anext__()
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/gradio/utils.py", line 329, in __anext__
>     return await anyio.to_thread.run_sync(
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
>     return await get_async_backend().run_sync_in_worker_thread(
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
>     return await future
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
>     result = context.run(func, *args)
>   File "/home/lianqi/anaconda3/envs/gpt_academic/lib/python3.10/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
>     return next(iterator)
>   File "/media/lianqi/HD/gpt_academic/gpt_academic/toolbox.py", line 131, in decorated
>     yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
>   File "/media/lianqi/HD/gpt_academic/gpt_academic/request_llms/bridge_all.py", line 1217, in predict
>     method = model_info[llm_kwargs['llm_model']]["fn_with_ui"]  # 如果这里报错，检查config中的AVAIL_LLM_MODELS选项
> KeyError: 'internvl2-40b'

尝试修改：request_llms/bridge_all.py 
加入粗体部分
```
model_info = {
    # openai
    "gpt-3.5-turbo": {
        "fn_with_ui": chatgpt_ui,
        "fn_without_ui": chatgpt_noui,
        "endpoint": openai_endpoint,
        "max_token": 16385,
        "tokenizer": tokenizer_gpt35,
        "token_cnt": get_token_num_gpt35,
    },
    **"internvl2-40b": {
        "fn_with_ui": chatgpt_ui,
        "fn_without_ui": chatgpt_noui,
        "endpoint": openai_endpoint,
        "max_token": 16385,
        "tokenizer": tokenizer_gpt35,
        "token_cnt": get_token_num_gpt35,
    },**
```
后提示：您提供的api-key不满足要求，不包含任何可用于internvl2-40b的api-key。您可能选择了错误的模型或请求源。

### Screen Shot | 有帮助的截图

第一部分报错：控制台有提示，如上⬆
![image](https://github.com/user-attachments/assets/173b3146-2f55-4030-b19b-241ce25e7351)
第二部分报错：控制台无提示
![image](https://github.com/user-attachments/assets/898a6d2e-f90d-457a-9a54-1433fd706c1e)

**Comment by SakuraPuare** [comment]
https://github.com/binary-husky/gpt_academic/blob/0458590a776616112191752f267cf5acd7791298/shared_utils/key_pattern_manager.py#L12-L61
