### ISSUE TITLE
[Bug]: Traceback (most recent call last):   File ".\request_llms\bridge_chatgpt.py", line 316, in predict     raise ValueError(f'无法读取以下数据，请检查配置。\n\n{chunk_decoded}') ValueError: 无法读取以下数据，请检查配置。

### ISSUE THREAD

**Issue by YinyiE** [binary-husky/gpt_academic#1934]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

当回复文字过长时出现以下报错（token长度设置正常）
Traceback (most recent call last):
  File ".\request_llms\bridge_chatgpt.py", line 316, in predict
    raise ValueError(f'无法读取以下数据，请检查配置。\n\n{chunk_decoded}')
ValueError: 无法读取以下数据，请检查配置。

: ping - 2024-08-11 11:59:38.557353

出现问题后先出现解析不和常规的错误，之后炸出一大串json文本，其中包含回复的内容但被分散到了每一个json中，
我看到issues里有一个类似的但因为我的模型是本地部署运行的不存在网络连接问题，并且较短回复是正常的，

### Screen Shot | 有帮助的截图

![23f57df7-d617-4903-98ab-90fae15495f5](https://github.com/user-attachments/assets/e06bc000-f8a0-4e92-9dc2-6d3906ae6136)
![39866e1f-0e22-44e2-a8c4-d51704530143](https://github.com/user-attachments/assets/ec95672c-24e2-4e91-9dbf-3f8fdec5a907)
（2图这里是部分）

**Comment by BoBo-YunYun** [comment]
我解决了哥们，还是我那个第三方API的URL写的有问题

**Comment by YinyiE** [comment]
> 我解决了哥们，还是我那个第三方API的URL写的有问题

是更新后就能正常使用了吗？

**Comment by 2645405109** [comment]
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"https://xxxx.yyyy.zzzz/v1/chat/completions"}
你在url后边要加上/v1/chat/completions
