### ISSUE TITLE
[Feature]: 联网搜索报错

### ISSUE THREAD

**Issue by raypenper** [binary-husky/gpt_academic#1941]
### Class | 类型

函数插件

### Feature Request | 功能请求

已配置代理，报错信息如下：

[Local Message] 插件调用出错:

Traceback (most recent call last):
  File ".\toolbox.py", line 221, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Internet_GPT.py", line 211, in 连接网络回答问题
    urls = searxng_request(txt, proxies, categories, searxng_url, engines=engines)
  File ".\crazy_functions\Internet_GPT.py", line 165, in searxng_request
    raise ValueError("在线搜索失败，状态码: " + str(response.status_code) + '\t' + response.content.decode('utf-8'))
ValueError: 在线搜索失败，状态码: 405 <html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.11.2</center>
</body>
</html>

**Comment by daxiavpm** [comment]
我也是这个问题
一模一样

**Comment by pfjiang537** [comment]
+1

**Comment by jiangangoddog** [comment]
+1
