### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Raymond-9527** [binary-husky/gpt_academic#2053]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

启动后显示错误代码:KeyError: 'https’ ,且无法弹出浏览器窗口，此现象出现于配置完毕config.py之后

### Screen Shot | 有帮助的截图

09:38 | ..up_logging:60  | 所有对话记录将自动保存在本地目录gpt_log\admin\chat_secrets.log, 请注意自我隐私保护哦！
09:38 | .._lru_cache:97  | [PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'http://127.0.0.1:7890'}
Traceback (most recent call last):
  File "C:\GPT-Academic\OneKeyInstallerForWindowsAndMacOS\gpt_academic\main.py", line 358, in <module>
    main()
  File "C:\GPT-Academic\OneKeyInstallerForWindowsAndMacOS\gpt_academic\main.py", line 85, in main
    proxy_info = check_proxy(proxies)
  File "C:\GPT-Academic\OneKeyInstallerForWindowsAndMacOS\gpt_academic\check_proxy.py", line 15, in check_proxy
    proxies_https = proxies['https'] if proxies is not None else '无'
KeyError: 'https'

**Comment by binaryYuki** [comment]
建议检查一下您的 config.py 
```python
    proxies = {
        #          [协议]://  [地址]  :[端口]
        "http":  "socks5h://localhost:11284",  # 再例如  "http":  "http://127.0.0.1:7890",
        "https": "socks5h://localhost:11284",  # 再例如  "https": "http://127.0.0.1:7890",
    }
```
是否**同时**存在"http"和"https"协议
