### ISSUE TITLE
翻译pdf,在所有线程完成后出现错误，更换代理无效。

### ISSUE THREAD

**Issue by 1661021512** [binary-husky/gpt_academic#362]
Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 436, in _error_catcher
    yield
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 693, in _update_chunk_length
    line = self._fp.fp.readline()
  File "D:\anaconda\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "D:\anaconda\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\anaconda\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 792, in read_chunked
    self._original_response.close()
  File "D:\anaconda\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 441, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\toolbox.py", line 149, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\批量翻译PDF文档_多线程.py", line 138, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, top_p, temperature, chatbot, history, sys_prompt)
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\批量翻译PDF文档_多线程.py", line 170, in 解析PDF
    gpt_response_collection = yield from request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency(
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\crazy_utils.py", line 83, in request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency
    gpt_res = f.result()
  File "D:\anaconda\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\anaconda\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\anaconda\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\crazy_utils.py", line 46, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\request_llm\bridge_chatgpt.py", line 106, in predict_no_ui_long_connection
    try: chunk = next(stream_response).decode()
  File "D:\anaconda\lib\site-packages\requests\models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "D:\anaconda\lib\site-packages\requests\models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out.

**Comment by hugegedegege** [comment]
我也是这个错误，大哥解决了吗

**Comment by 1661021512** [comment]
openai后台显示是进行了翻译的，但是在每个线程翻译完成后，会出现这个错误，更换多个代理均无法解决。

**Comment by 1661021512** [comment]
出现了第二种错误

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 696, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 436, in _error_catcher
    yield
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 763, in read_chunked
    self._update_chunk_length()
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 700, in _update_chunk_length
    raise httplib.IncompleteRead(line)
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 792, in read_chunked
    self._original_response.close()
  File "D:\anaconda\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\anaconda\lib\site-packages\urllib3\response.py", line 454, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\toolbox.py", line 149, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\批量翻译PDF文档_多线程.py", line 138, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, top_p, temperature, chatbot, history, sys_prompt)
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\批量翻译PDF文档_多线程.py", line 170, in 解析PDF
    gpt_response_collection = yield from request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency(
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\crazy_utils.py", line 83, in request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency
    gpt_res = f.result()
  File "D:\anaconda\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\anaconda\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\anaconda\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\crazy_functions\crazy_utils.py", line 46, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
  File "C:\Users\lenovo\Desktop\chatgpt_academic-master\request_llm\bridge_chatgpt.py", line 106, in predict_no_ui_long_connection
    try: chunk = next(stream_response).decode()
  File "D:\anaconda\lib\site-packages\requests\models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "D:\anaconda\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by binary-husky** [comment]
从报错看，仅能看出来是网络问题 …… 需要更多线索

**Comment by 1661021512** [comment]
我使用的科学上网软件为clash, 基础功能均正常，在多线程翻译的过程中，每个线程都能完成翻译，也都可以正常输出，但是当将翻译内容汇总时，出现了这个错误，所有的翻译内容未能保存。这一点导致浪费了我不少API的费用了。

**Comment by binary-husky** [comment]
> 我使用的科学上网软件为clash, 基础功能均正常，在多线程翻译的过程中，每个线程都能完成翻译，也都可以正常输出，但是当将翻译内容汇总时，出现了这个错误，所有的翻译内容未能保存。这一点导致浪费了我不少API的费用了。

ff87aebc2971c81a8b0bec9e47f4f2c19808d2b1修改了网络故障时的处理逻辑

**Comment by krater11** [comment]
我第一个汇总弄出来了，之后就不行了
