### ISSUE TITLE
解释代码报错：ModuleNotFoundError: No module named 'mdx_math'

### ISSUE THREAD

**Issue by ylsislove** [binary-husky/gpt_academic#431]
**Describe the bug 简述**
用解释代码功能让ChatGPT帮我解释下一行shell代码`head -n 1 CHANGELOG.md|awk -F " " '{print $2}'`，输出到一半没有输出了，去控制台查看发现报错：
```bash
Running on local URL:  http://0.0.0.0:51262

To create a public link, set `share=True` in `launch()`.
 gpt-3.5-turbo : 0 : 请解释以下代码：
```用于本issue里占位，防止转义
head -n 1 CHANGELOG.md|awk -F " " '{print $2}'
```用于本issue里占位，防止转义
 ..........
Traceback (most recent call last):
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\site-packages\gradio\blocks.py", line 1111, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\site-packages\gradio\blocks.py", line 1045, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\code\python\chatgpt_academic\toolbox.py", line 345, in format_io
    None if gpt_reply is None else markdown_convertion(gpt_reply)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\code\python\chatgpt_academic\toolbox.py", line 295, in markdown_convertion
    convert_stage_1 = markdown.markdown(text=txt, extensions=['mdx_math', 'fenced_code', 'tables', 'sane_lists'], extension_configs=markdown_extension_configs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\site-packages\markdown\core.py", line 376, in markdown
    md = Markdown(**kwargs)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\site-packages\markdown\core.py", line 86, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\site-packages\markdown\core.py", line 113, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\site-packages\markdown\core.py", line 152, in build_extension
    module = importlib.import_module(ext_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aayu\scoop\apps\miniconda3\current\envs\gptac_venv\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mdx_math'
```

**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/41816449/231385315-ee52a49d-87de-486a-ae1a-cc71c90918c6.png)

**Terminal Traceback 终端traceback（如果有）**
![image](https://user-images.githubusercontent.com/41816449/231385412-a53b7779-cce4-44cb-8c5e-10b49c5672ff.png)

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
缺少依赖
![image](https://user-images.githubusercontent.com/96192199/231386952-5674a898-d47e-4595-84ba-f83659373971.png)

**Comment by ylsislove** [comment]
我去，有一段时间没关注`requirements.txt`了，居然添加了这么多依赖，这就去安装🤣

**Comment by ylsislove** [comment]
更新了依赖后没有报错啦，但结果被输出了两遍，比较奇怪，这里面也没有公式呀

![image](https://user-images.githubusercontent.com/41816449/231391372-3aa51e15-f223-4ac9-b9a3-aa7dbab99f38.png)

**Comment by binary-husky** [comment]
> 更新了依赖后没有报错啦，但结果被输出了两遍，比较奇怪，这里面也没有公式呀
> 
> ![image](https://user-images.githubusercontent.com/41816449/231391372-3aa51e15-f223-4ac9-b9a3-aa7dbab99f38.png)

识别了dollar符号😂，尴尬

不过幸好影响不太大（包含$的代码并不多），以后会慢慢修复
