### ISSUE TITLE
批量翻译PDF文档插件使用失败

### ISSUE THREAD

**Issue by yinjiashu** [binary-husky/gpt_academic#512]
[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "D:\chatgpt_academic\chatgpt_academic\toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "D:\chatgpt_academic\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 221, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
  File "D:\chatgpt_academic\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 232, in 解析PDF
    file_content, page_one = read_and_clean_pdf_text(fp)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 59, in read_and_clean_pdf_text
    pf = primary_ffsize(l)
         ^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 40, in primary_ffsize
    return max(fsize_statiscs, key=fsize_statiscs.get)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: max() arg is an empty sequence
当前代理可用性:

代理配置 socks5h://localhost:10808, 代理所在地：Hong Kong

2.68版本中出现该问题，回调2.67版本同样出现该问题

**Comment by binary-husky** [comment]
这个有点罕见，测试样本方便提供吗？

**Comment by yinjiashu** [comment]
如上个文件出现上述问题，同时测试过一个8M的pdf，虽然最后翻译失败但是程序正常运行。另有一27mb的ls-dyna说明书无法翻译，因大小超限无法上传。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "binary-husky/chatgpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 凌晨0:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/chatgpt_academic] 批量翻译PDF文档插件使用失败 (Issue #512)





 
这个有点罕见，测试样本方便提供吗？

**Comment by binary-husky** [comment]
@yinjiashu bug已修复

另附此pdf的翻译
[总结论文-1.pdf.trans (5).md](https://github.com/binary-husky/chatgpt_academic/files/11260222/-1.pdf.trans.5.md)
