### ISSUE TITLE
在调用GLM模型时默认CPU工作，怎样转为显卡调用？

### ISSUE THREAD

**Issue by MOLIZHU2023** [binary-husky/gpt_academic#534]
在调用GLM模型时默认CPU工作，怎样转为显卡调用？显卡GTX4090

**Comment by binary-husky** [comment]
`config.py`中改成cuda

**Comment by binary-husky** [comment]
另外使用gpu时，建议linux用户优先选择docker方案（见readme）

**Comment by MOLIZHU2023** [comment]
谢谢！感激！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月20日(星期四) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/chatgpt_academic] 在调用GLM模型时默认CPU工作，怎样转为显卡调用？ (Issue #534)





 
另外使用gpu时，建议linux用户优先选择docker方案（见readme）

**Comment by songkq** [comment]
@binary-husky Mac-M1 加载GLM失败，请问怎么解决？

Process GetGLMHandle-1:
```py
Traceback (most recent call last):
  File "/Users/chatgpt_academic/request_llm/bridge_chatglm.py", line 43, in run
    self.chatglm_model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).float()
  File "/Users/env/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 462, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/Users/env/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/Users/env/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 299, in get_cached_module_file
    get_cached_module_file(
  File "/Users/env/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/Users/env/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 134, in check_imports
    importlib.import_module(imp)
  File "/Users/env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/env/lib/python3.9/site-packages/cpm_kernels/__init__.py", line 1, in <module>
    from . import library
  File "/Users/env/lib/python3.9/site-packages/cpm_kernels/library/__init__.py", line 1, in <module>
    from . import nvrtc
  File "/Users/env/lib/python3.9/site-packages/cpm_kernels/library/nvrtc.py", line 5, in <module>
    nvrtc = Lib("nvrtc")
  File "/Users/env/lib/python3.9/site-packages/cpm_kernels/library/base.py", line 59, in __init__
    raise RuntimeError("Unknown platform: %s" % sys.platform)
RuntimeError: Unknown platform: darwin
```

**Comment by binary-husky** [comment]
> @binary-husky Mac-M1 加载GLM失败，请问怎么解决？
> 

cpu是arm架构的吧，我只在嵌入式里面接触过arm，没有相关知识

**Comment by leomsn** [comment]
@binary-husky Mac-Intel 加载GLM失败，跟这位M1架构的兄弟报错情况一样
