### ISSUE TITLE
服务器在海外但是要网络代理

### ISSUE THREAD

**Issue by KangtanC** [binary-husky/gpt_academic#583]
我人在英国，应该不用加网络代理吧
Traceback (most recent call last):
  File "/Users/aquaticdwarf/chatgpt_academic/toolbox.py", line 472, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config_private'), arg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config_private'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aquaticdwarf/chatgpt_academic/main.py", line 209, in <module>
    main()
  File "/Users/aquaticdwarf/chatgpt_academic/main.py", line 5, in main
    from request_llm.bridge_all import predict
  File "/Users/aquaticdwarf/chatgpt_academic/request_llm/bridge_all.py", line 48, in <module>
    API_URL_REDIRECT, = get_conf("API_URL_REDIRECT")
  File "/Users/aquaticdwarf/chatgpt_academic/toolbox.py", line 496, in get_conf
    r = read_single_conf_with_lru_cache(arg)
  File "/Users/aquaticdwarf/chatgpt_academic/toolbox.py", line 474, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config'), arg)
AttributeError: module 'config' has no attribute 'API_URL_REDIRECT'

**Comment by binary-husky** [comment]
不用~ config.py文件不完整，请下载新版程序

**Comment by KangtanC** [comment]
谢谢大佬
