### ISSUE TITLE
部署成功提交报bridge_chatgpt.py", line 181, in predict     if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):

### ISSUE THREAD

**Issue by AmmGo** [binary-husky/gpt_academic#606]
To create a public link, set `share=True` in `launch()`.
 gpt-3.5-turbo : 0 : hello ..........
Traceback (most recent call last):
  File "f:\other\chatgpt\chatgpt_academic\request_llm\bridge_chatgpt.py", line 181, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

**Comment by binary-husky** [comment]
报错不完整
