### ISSUE TITLE
请教一下，chatglm本地部署时 权重文件夹下载好并放在工程文件夹里，然后在bridge_chatglm.py里面改了路径，可是总是不能导入权重，bug如下，

### ISSUE THREAD

**Issue by dream-desktop** [binary-husky/gpt_academic#649]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed 
in a newer revision.
Process GetGLMHandle-1:
Traceback (most recent call last):
  File "e:\tensorflow-learning\github\chatgpt_academic-master\request_llm\bridge_chatglm.py", line 45, in run
    self.chatglm_model = AutoModel.from_pretrained(model_path, trust_remote_code=True).float()
  File "E:\python-practice\python_envs\Python38_novelAI\lib\site-packages\transformers\models\auto\auto_factory.py", line 440, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "E:\python-practice\python_envs\Python38_novelAI\lib\site-packages\transformers\dynamic_module_utils.py", line 384, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "E:\python-practice\python_envs\Python38_novelAI\lib\site-packages\transformers\dynamic_module_utils.py", line 154, in get_class_in_module
    module = importlib.import_module(module_path)
  File "E:\python-practice\python_envs\Python38_novelAI\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 30, in <module>      
    from transformers.generation.logits_process import LogitsProcessor
ModuleNotFoundError: No module named 'transformers.generation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python-practice\python_envs\Python38_novelAI\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "e:\tensorflow-learning\github\chatgpt_academic-master\request_llm\bridge_chatglm.py", line 56, in run
    raise RuntimeError("不能正常加载ChatGLM的参数！")
RuntimeError: 不能正常加载ChatGLM的参数！``

**Comment by binary-husky** [comment]
依赖问题？

**Comment by andylau004** [comment]
遇到同样问题。。
请问如何解决



(torch) @bxy-a6000:~/ChatGLM3/basic_demo$ /home/aa/anaconda3/bin/python3 web_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/home/aa/ChatGLM3/basic_demo/web_demo.py", line 17, in <module>
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True).cuda()
  File "/home/aa/anaconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/aa/anaconda3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/aa/anaconda3/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 147, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/home/aa/anaconda3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aa/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 25, in <module>
    import transformers.generation.logits_process
ModuleNotFoundError: No module named 'transformers.generation'
