### ISSUE TITLE
NewBing不能正常使用

### ISSUE THREAD

**Issue by EdisonWendy** [binary-husky/gpt_academic#653]
- **(1) Describe the bug 简述**
RuntimeError: 不能加载Newbing组件。NEWBING_COOKIES未填写或有格式错误。

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/120798970/235272376-a7eb8a1f-72a1-4694-aa90-255557836e81.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by Blackcf** [comment]
我的可以，你这是缺少依赖了把

**Comment by EdisonWendy** [comment]
> 我的可以，你这是缺少依赖了把

我按照网上的说法把Bing的cookie复制到config.py里面了，但还是不行
![image](https://user-images.githubusercontent.com/120798970/235284226-0a119bea-5d66-466a-a168-ad5d1c7e7b6d.png)

**Comment by EdisonWendy** [comment]
> 我的可以，你这是缺少依赖了把

你说的依赖是指？

**Comment by woshiwangyilei** [comment]
newbing不需要依赖，加个cookies就能用，但是需要代理改成true，并保持代理开启。

**Comment by StarCode000** [comment]
request_llm/requirements_newbing.txt
可以检查这些依赖是否已经安装

**Comment by EdisonWendy** [comment]
> request_llm/requirements_newbing.txt 可以检查这些依赖是否已经安装

依赖已经安装了，我怀疑是cookie的问题，但是没整明白咋弄

**Comment by StarCode000** [comment]
你检查一下你的cookie是不是json格式。如果是，那就重新获取一次cookie，之前的cookie可能失效了；如果不是，那问题就出在这……

**Comment by EdisonWendy** [comment]
> 你检查一下你的cookie是不是json格式。如果是，那就重新获取一次cookie，之前的cookie可能失效了；如果不是，那问题就出在这……

不是，我是直接把浏览器插件导出的那一大串复制到config.py对应位置里面的
![image](https://user-images.githubusercontent.com/120798970/235301892-c008509c-0158-4687-a3a6-d347cd8d3dd5.png)

**Comment by StarCode000** [comment]
那你检查一下你的项目根目录下有没有config_private.py，这个优先级更高

**Comment by EdisonWendy** [comment]
> 那你检查一下你的项目根目录下有没有config_private.py，这个优先级更高

有的，我就是在config_private.py里面修改的

**Comment by StarCode000** [comment]
为了提高效率，你把完整的报错信息发上来吧

**Comment by EdisonWendy** [comment]
> 为了提高效率，你把完整的报错信息发上来吧

[Local Message] Newbing失败 Traceback (most recent call last):
  File ".\request_llm\bridge_newbing.py", line 153, in run
    asyncio.run(self.async_run())
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File ".\request_llm\bridge_newbing.py", line 100, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File ".\request_llm\edge_gpt.py", line 387, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File ".\request_llm\edge_gpt.py", line 290, in ask_stream
    self.wss = await websockets.connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1090, in create_connection
    raise exceptions[0]
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edison\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 633, in finish_connect
    ov.getresult()
PermissionError: [WinError 5] 拒绝访问。

**Comment by StarCode000** [comment]
你直接去搜索一下PermissionError: [WinError 5] 拒绝访问
这问题我还没遇到过

**Comment by woshiwangyilei** [comment]
没权限的话，试试开管理员运行？

**Comment by binary-husky** [comment]
websockets模块的问题，查不到相关的解决方法。尝试用anaconda配置一个干净的python环境试试？

**Comment by yanghaies** [comment]
> * **（1） 描述 bug 简述** RuntimeError： 不能加载Newbing组件。NEWBING_COOKIES未填写或有格式错误。
> * **（2） 屏幕截图截图**
>   ![图像](https://user-images.githubusercontent.com/120798970/235272376-a7eb8a1f-72a1-4694-aa90-255557836e81.png)
> * **（3） 终端回落（如有）**
> * **（4） 帮助重现错误的材料 帮助我们复现的测试材料样本（如有）**
> 
> 提交问题之前 提交问题之前：
> 
> * 请尝试升级您的代码。如果您的代码不是最新的，建议您先尝试更新代码
> * 请查看项目wiki以获取常见问题解决方案.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法



> 

楼主，能否礼貌问下如何获得newbing的cookei😂
