### ISSUE TITLE
关于尝试用chatGLM时遇到的问题

### ISSUE THREAD

**Issue by majunyao** [binary-husky/gpt_academic#664]
- **(1) Describe the bug  具体来说我加载了chatGLM模型（不过是阉割版），经过我的测试模型是可以输出结果的，但是其结果没有反应到网页前端内。经过我的初步测试，我认为问题在bridge_chatglm.py中的第65行self.child.send(response)和第80行res = self.parent.recv()这里没有对接好。
- 
- 注：系统Windows 10，显卡GTX1660Ti，显存6G，chatGLM模型THUDM/chatglm-6b-int4**

- **(2) Screen Shot 
- 
![image](https://user-images.githubusercontent.com/63037841/235349719-fc8fbd8c-4f39-4711-b0d4-b332cb728f1c.png)
界面一直停留在这里，即便加载模型完成并计算完成也停留在这里

于是我开始测试哪里有问题。
![image](https://user-images.githubusercontent.com/63037841/235350235-c3e5e168-168b-4871-bbe9-dcbdafb322db.png)
![image](https://user-images.githubusercontent.com/63037841/235350205-a22fec74-ef2e-459d-af15-45cd9bd93540.png)
我在这三处加了输出，最后的输出结果为
![image](https://user-images.githubusercontent.com/63037841/235350417-13951ce5-6cd2-438a-9c18-a7f76f67efac.png)
界面一直停留在原来的地方，不变
这说明，
1，self.parent.recv()只接收到了第1次self.child.send()但是后面的信息没有接收。
2，由于后续的没有接收，主程序一直处在self.parent.recv()等待接收的状态？（我没接触过multiprocessing，这里是猜测的）
3，self.child.send()结束后，又回到循环内的kwargs = self.child.recv() 然而，主程序一直处在等待接收，自然没有新的数据传输回来。（我没接触过multiprocessing，这里是猜测的）

- **

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
这个跨进程使用了pipe（管道）通讯。截图中这种情况不能理解。这个bug是每次运行都触发吗，还是有什么触发条件

**Comment by binary-husky** [comment]
在windows上实验了一下，不能复现这个问题。
请问python版本是？

**Comment by majunyao** [comment]
目前没有跑通过，我的python版本为3.10.10&nbsp;


B19010509马均瑶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月1日(星期一) 晚上9:10
收件人: "binary-husky/gpt_academic";
抄送: "Author";
主题: Re: [binary-husky/gpt_academic] 关于尝试用chatGLM时遇到的问题 (Issue #664)





 
这个跨进程使用了pipe（管道）通讯。截图中这种情况不能理解。这个bug是每次运行都触发吗，还是有什么触发条件
 
&mdash;

**Comment by majunyao** [comment]
我的GLM，是把模型先下载到了本地，再在本地上加载。


B19010509马均瑶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月1日(星期一) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] 关于尝试用chatGLM时遇到的问题 (Issue #664)





 
这个跨进程使用了pipe（管道）通讯。截图中这种情况不能理解。这个bug是每次运行都触发吗，还是有什么触发条件

**Comment by majunyao** [comment]
> 这个跨进程使用了pipe（管道）通讯，逻辑是很简洁的。只看截图中这种情况，十分反常无法理解。
> 
> 这个bug是每次运行都触发吗，还是有什么触发条件？


刚才下载了最新版本的github代码，还是不能运行，错误情况和之前一摸一样。python版本3.10.10   torch版本2.0.0+cu117。

chatGLM加载的是本地的，为此我在bridge_chatglm.py中改了一部分代码，换成我自己的路径
![image](https://user-images.githubusercontent.com/63037841/235961591-e749bcdf-c380-4a6c-a481-f833de7acba7.png)
仅此而已。（除了为了找出错误的各种print，就只有这三行）

config.py中的LOCAL_MODEL_DEVICE已改成"cuda"

**Comment by codeofyu** [comment]
[Local Message] Call ChatGLM fail 不能正常加载ChatGLM的参数。

**Comment by codeofyu** [comment]
Process GetGLMHandle-1:
Traceback (most recent call last):
  File "F:\AI\chatgpt_academic\request_llm\bridge_chatglm.py", line 48, in run
    self.chatglm_model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                                 ^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
怎么修复

**Comment by majunyao** [comment]
> Process GetGLMHandle-1: Traceback (most recent call last): File "F:\AI\chatgpt_academic\request_llm\bridge_chatglm.py", line 48, in run self.chatglm_model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().cuda() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in cuda return self._apply(lambda t: t.cuda(device)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply module._apply(fn) File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply module._apply(fn) File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply param_applied = fn(param) ^^^^^^^^^ File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in return self._apply(lambda t: t.cuda(device)) ^^^^^^^^^^^^^^ File "E:\ProgramData\anaconda3\envs\gptac_venv\Lib\site-packages\torch\cuda__init__.py", line 239, in _lazy_init raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enabled 怎么修复

cuda没装好？你在那个环境下打开命令行依次输入
python
import torch
torch.cuda.is_available()
看看最后的结果是不是True。

**Comment by codeofyu** [comment]
(gptac_venv) F:\AI\chatgpt_academic>python -m pip install -r request_llm/requirements_newbing.txt
Looking in indexes: https://pypi.org/simple/
Requirement already satisfied: BingImageCreator in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_newbing.txt (line 1)) (0.1.3)
Requirement already satisfied: certifi in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_newbing.txt (line 2)) (2022.12.7)
Requirement already satisfied: httpx in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_newbing.txt (line 3)) (0.24.0)
Requirement already satisfied: prompt_toolkit in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_newbing.txt (line 4)) (3.0.38)
Requirement already satisfied: requests in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_newbing.txt (line 5)) (2.28.2)
Requirement already satisfied: rich in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_newbing.txt (line 6)) (13.3.4)
Requirement already satisfied: websockets in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_newbing.txt (line 7)) (11.0.1)
Requirement already satisfied: aiohttp in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (3.8.4)
Requirement already satisfied: regex in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (2023.3.23)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from httpx->-r request_llm/requirements_newbing.txt (line 3)) (0.17.0)
Requirement already satisfied: idna in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from httpx->-r request_llm/requirements_newbing.txt (line 3)) (3.4)
Requirement already satisfied: sniffio in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from httpx->-r request_llm/requirements_newbing.txt (line 3)) (1.3.0)
Requirement already satisfied: wcwidth in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from prompt_toolkit->-r request_llm/requirements_newbing.txt (line 4)) (0.2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from requests->-r request_llm/requirements_newbing.txt (line 5)) (3.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from requests->-r request_llm/requirements_newbing.txt (line 5)) (1.26.15)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from rich->-r request_llm/requirements_newbing.txt (line 6)) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from rich->-r request_llm/requirements_newbing.txt (line 6)) (2.15.0)
Requirement already satisfied: socksio==1.* in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from httpx->-r request_llm/requirements_newbing.txt (line 3)) (1.0.0)
Requirement already satisfied: h11<0.15,>=0.13 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->-r request_llm/requirements_newbing.txt (line 3)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx->-r request_llm/requirements_newbing.txt (line 3)) (3.6.2)
Requirement already satisfied: mdurl~=0.1 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->-r request_llm/requirements_newbing.txt (line 6)) (0.1.2)
Requirement already satisfied: attrs>=17.3.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from aiohttp->BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from aiohttp->BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from aiohttp->BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from aiohttp->BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from aiohttp->BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from aiohttp->BingImageCreator->-r request_llm/requirements_newbing.txt (line 1)) (1.3.1)

(gptac_venv) F:\AI\chatgpt_academic>python
Python 3.11.2 | packaged by Anaconda, Inc. | (main, Mar 27 2023, 23:35:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
>>>

**Comment by codeofyu** [comment]
(gptac_venv) F:\AI\chatgpt_academic>python -m pip install -r request_llm/requirements_chatglm.txt
Looking in indexes: https://pypi.org/simple/
Requirement already satisfied: protobuf in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_chatglm.txt (line 1)) (4.22.3)
Requirement already satisfied: transformers==4.27.1 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_chatglm.txt (line 2)) (4.27.1)
Requirement already satisfied: cpm_kernels in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_chatglm.txt (line 3)) (1.0.11)
Requirement already satisfied: torch>=1.10 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_chatglm.txt (line 4)) (2.0.0)
Requirement already satisfied: mdtex2html in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_chatglm.txt (line 5)) (1.2.0)
Requirement already satisfied: sentencepiece in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from -r request_llm/requirements_chatglm.txt (line 6)) (0.1.98)
Requirement already satisfied: filelock in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (3.11.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (0.13.4)
Requirement already satisfied: numpy>=1.17 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (1.24.2)
Requirement already satisfied: packaging>=20.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (23.1)
Requirement already satisfied: pyyaml>=5.1 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (6.0)
Requirement already satisfied: regex!=2019.12.17 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (2023.3.23)
Requirement already satisfied: requests in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (2.28.2)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (4.65.0)
Requirement already satisfied: typing-extensions in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from torch>=1.10->-r request_llm/requirements_chatglm.txt (line 4)) (4.5.0)
Requirement already satisfied: sympy in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from torch>=1.10->-r request_llm/requirements_chatglm.txt (line 4)) (1.11.1)
Requirement already satisfied: networkx in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from torch>=1.10->-r request_llm/requirements_chatglm.txt (line 4)) (3.1)
Requirement already satisfied: jinja2 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from torch>=1.10->-r request_llm/requirements_chatglm.txt (line 4)) (3.1.2)
Requirement already satisfied: markdown in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from mdtex2html->-r request_llm/requirements_chatglm.txt (line 5)) (3.4.3)
Requirement already satisfied: latex2mathml in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from mdtex2html->-r request_llm/requirements_chatglm.txt (line 5)) (3.75.2)
Requirement already satisfied: colorama in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from tqdm>=4.27->transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from jinja2->torch>=1.10->-r request_llm/requirements_chatglm.txt (line 4)) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from requests->transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from requests->transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from requests->transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from requests->transformers==4.27.1->-r request_llm/requirements_chatglm.txt (line 2)) (2022.12.7)
Requirement already satisfied: mpmath>=0.19 in e:\programdata\anaconda3\envs\gptac_venv\lib\site-packages (from sympy->torch>=1.10->-r request_llm/requirements_chatglm.txt (line 4)) (1.3.0)

**Comment by codeofyu** [comment]
![image](https://user-images.githubusercontent.com/28337592/236207431-aa0674ce-44ad-4df4-8870-eb6f01df2912.png)

**Comment by majunyao** [comment]
![image](https://user-images.githubusercontent.com/63037841/236207602-f46ef2c9-a61f-49f2-bd30-f048ca8d50fe.png)
这里不能调用cuda，要么把config.py里的参数改成"cpu"，要么安装相应的cuda和cudnn，确保torch能够调用cuda

**Comment by codeofyu** [comment]
好了，Input length of input_ids is 548, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 861, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
不过只能上传512能不能参数调整

**Comment by codeofyu** [comment]
Input length of input_ids is 548, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
Input length of input_ids is 861, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
WARNING:  Invalid HTTP request received.
Input length of input_ids is 524, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
随便发几句话就无法处理了
![image](https://user-images.githubusercontent.com/28337592/236289671-3076ff23-89da-4645-9eb2-4e3fee500817.png)

**Comment by majunyao** [comment]
> 好了，Input length of input_ids is 548, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`. Input length of input_ids is 861, but `max_length` is set to 512. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`. 不过只能上传512能不能参数调整


应该可以，但是我的GLM还没有跑起来。能问一下你的操作系统，python版本，torch版本，cuda版本，显卡型号。这些信息吗？我的一直出bug

**Comment by codeofyu** [comment]
显卡：3090
--------------------------------
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22621 暂缺 Build 22621
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     Microsoft
注册的组织:       YS
产品 ID:          00331-10000-00001-AA050
初始安装日期:     2022/5/7, 13:33:11
系统启动时间:     2023/5/5, 0:04:48
系统制造商:       GIGABYTE
系统型号:         C621-WD12-IPMI
系统类型:         x64-based PC
处理器:           安装了 2 个处理器。
                  [01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~3001 Mhz
                  [02]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~3001 Mhz
BIOS 版本:        American Megatrends Inc. R2, 2020/7/21
-------------------------------------------

Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
------------------------------------------

>>> import torch; print(torch.__version__)
1.13.1+cu117
------------------------------------------------

PS C:\Users\Administrator> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
希望对你有所帮助

**Comment by codeofyu** [comment]
https://github.com/Akegarasu/ChatGLM-webui
直接用这个环境吧，整合好了

**Comment by codeofyu** [comment]
这样只需要弄两个文件

---------- open.bat
echo 获取最新代码
git pull

set PYTHON=py310\\python.exe

%PYTHON% fast_open.py
pause
-----------
fast_open.py

import os
import sys
import subprocess

# 设置脚本
python_script = "main.py"

# 获取当前脚本所在的目录
current_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(current_dir)

# 安装 requirements.txt 中指定版本的依赖项
requirements_path = "requirements.txt"
aliyun_pypi_mirror = "https://mirrors.aliyun.com/pypi/simple/"
subprocess.run([sys.executable, "-m", "pip", "install", "-r", requirements_path, "-i", aliyun_pypi_mirror])

# 安装 request_llm/requirements_chatglm.txt 中的依赖项
requirements_chatglm_path = "request_llm/requirements_chatglm.txt"
subprocess.run([sys.executable, "-m", "pip", "install", "-r", requirements_chatglm_path])

# 安装 request_llm/requirements_newbing.txt 中的依赖项
requirements_newbing_path = "request_llm/requirements_newbing.txt"
subprocess.run([sys.executable, "-m", "pip", "install", "-r", requirements_newbing_path])

# 安装指定版本的 torch, torchvision 和 torchaudio
torch_stable_url = "https://download.pytorch.org/whl/cu121/torch_stable.html"
subprocess.run([sys.executable, "-m", "pip", "install", "torch", "torchvision", "torchaudio", "-f", torch_stable_url])

# 运行主 Python 脚本
subprocess.run([sys.executable, python_script])

**Comment by codeofyu** [comment]
我已经可以用了，不过我想用chat gpt 的网页因为充值了plus，解读lua文件，chatGLM现在代码解读质量太低根本看不了，api又会有一半会超时失败，没法做失败的文件增量解读，手动的话不知道上下文是怎么处理的，重新解读时间又长又贵，这个功能要是能稳定点以及可编程扩展的话，就好了，最好能支持与网页版的chat gpt 的网页，这样有账号都能体验你的工具啦

**Comment by majunyao** [comment]
> 

尴尬了，我不是开发者，只不过你之前的问题我恰好能够解决。建议找一下有没有论坛，或者直接私信作者

**Comment by majunyao** [comment]
> 

尴尬了，我不是开发者，只不过你之前的问题我恰好能够解决。建议找一下有没有论坛，或者直接私信作者
