### ISSUE TITLE
main.py运行不了

### ISSUE THREAD

**Issue by ambglh** [binary-husky/gpt_academic#692]
[PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
 [API_KEY] 本项目现已支持OpenAI和API2D的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,api2d-key3"
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
C:\Users\13534\.conda\envs\gptac_venv\Lib\site-packages\urllib3\connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
查询代理的地理位置，返回的结果是{'ip': '43.207.100.237', 'network': '43.206.0.0/15', 'version': 'IPv4', 'city': 'Tokyo', 'region': 'Tokyo', 'region_code': '13', 'country': 'JP', 'country_name': 'Japan', 'country_code': 'JP', 'country_code_iso3': 'JPN', 'country_capital': 'Tokyo', 'country_tld': '.jp', 'continent_code': 'AS', 'in_eu': False, 'postal': '140-0002', 'latitude': 35.616978, 'longitude': 139.745521, 'timezone': 'Asia/Tokyo', 'utc_offset': '+0900', 'country_calling_code': '+81', 'currency': 'JPY', 'currency_name': 'Yen', 'languages': 'ja', 'country_area': 377835.0, 'country_population': 126529100, 'asn': 'AS16509', 'org': 'AMAZON-02'}
代理配置 http://127.0.0.1:7890, 代理所在地：Japan
Traceback (most recent call last):
  File "D:\git\chatgpt_academic\main.py", line 208, in <module>
    main()
  File "D:\git\chatgpt_academic\main.py", line 54, in main
    with gr.Blocks(title="ChatGPT 学术优化", theme=set_theme, analytics_enabled=False, css=advanced_css) as demo:

  File "C:\Users\13534\.conda\envs\gptac_venv\Lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\13534\.conda\envs\gptac_venv\Lib\site-packages\gradio\blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\13534\.conda\envs\gptac_venv\Lib\site-packages\gradio_client\serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
            ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'serialized_input'

**Comment by pingplug** [comment]
我试了在`requirements.txt`里把gradio的版本改为3.26.0，就好了

**Comment by ambglh** [comment]
可以了，谢谢

**Comment by HanZhang-ZERO** [comment]
> 我试了在`requirements.txt`里把gradio的版本改为3.26.0，就好了

为什么改了还是出现同样的错误 （哭

**Comment by ambglh** [comment]
会不会是依赖没有安装完全，还有检查一下端口号



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZHANG ***@***.***&gt;; 
发送时间: 2023年5月6日(星期六) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/gpt_academic] main.py运行不了 (Issue #692)





  
我试了在requirements.txt里把gradio的版本改为3.26.0，就好了
  
为什么改了还是出现同样的错误 （哭

**Comment by HanZhang-ZERO** [comment]
> 会不会是依赖没有安装完全，还有检查一下端口号
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZHANG ***@***.***&gt;; 发送时间: 2023年5月6日(星期六) 下午4:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [binary-husky/gpt_academic] main.py运行不了 (Issue #692) 我试了在requirements.txt里把gradio的版本改为3.26.0，就好了 为什么改了还是出现同样的错误 （哭 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

哈对的，忘记了重新装一下依赖，现在可以了，感谢大佬～

**Comment by binary-husky** [comment]
python -m pip install gradio==3.28.3

**Comment by huayu-luo** [comment]
(chatgpt) D:\sofeware\gpt_academic-master>python main.py
Traceback (most recent call last):
  File "D:\sofeware\gpt_academic-master\main.py", line 345, in <module>
    main()
  File "D:\sofeware\gpt_academic-master\main.py", line 6, in main
    raise ModuleNotFoundError("使用项目内置Gradio获取最优体验! 请运行 `pip install -r requirements.txt` 指令安装内置Gradio及其他依赖, 详情信息见requirements.txt.")
ModuleNotFoundError: 使用项目内置Gradio获取最优体验! 请运行 `pip install -r requirements.txt` 指令安装内置Gradio及其他依赖, 详情信息见requirements.txt.
大佬们能帮我看一下我这个是啥情况吗，我运行了pip install -r requirements.txt这个指令和pip install gradio指令但是一直运行不出来

**Comment by luckycat1024** [comment]
Traceback (most recent call last):
  File "C:\Users\panda\Downloads\gpt_academic-master\main.py", line 406, in <module>
    main()
  File "C:\Users\panda\Downloads\gpt_academic-master\main.py", line 17, in main
    import gradio as gr
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 35, in <module>
    import matplotlib
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 272, in <module>
    _check_versions()
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 266, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: 找不到指定的模块。

各位大哥：
我上面的情况如何解决

**Comment by luckycat1024** [comment]
我运行了pip install -r requirements.txt这个指令和pip install gradio指令，但是一直运行不出来

Traceback (most recent call last):
  File "C:\Users\panda\Downloads\gpt_academic-master\main.py", line 406, in <module>
    main()
  File "C:\Users\panda\Downloads\gpt_academic-master\main.py", line 17, in main
    import gradio as gr
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\components.py", line 55, in <module>
    from gradio import processing_utils, utils
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 35, in <module>
    import matplotlib
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 272, in <module>
    _check_versions()
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\matplotlib\__init__.py", line 266, in _check_versions
    module = importlib.import_module(modname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\panda\AppData\Local\Programs\Python\Python311\Lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: 找不到指定的模块。

**Comment by luckycat1024** [comment]
> (chatgpt) D:\sofeware\gpt_academic-master>python main.py Traceback (most recent call last): File "D:\sofeware\gpt_academic-master\main.py", line 345, in main() File "D:\sofeware\gpt_academic-master\main.py", line 6, in main raise ModuleNotFoundError("使用项目内置Gradio获取最优体验! 请运行 `pip install -r requirements.txt` 指令安装内置Gradio及其他依赖, 详情信息见requirements.txt.") ModuleNotFoundError: 使用项目内置Gradio获取最优体验! 请运行 `pip install -r requirements.txt` 指令安装内置Gradio及其他依赖, 详情信息见requirements.txt. 大佬们能帮我看一下我这个是啥情况吗，我运行了pip install -r requirements.txt这个指令和pip install gradio指令但是一直运行不出来

你好呀，请问问题解决了吗？我也遇到一样的问题了

**Comment by shtlu06** [comment]
遇到  ImportError: DLL load failed while importing _cext: 找不到指定的模块”这个问题；
亲测通过pip install msvc-runtime可以解决。
