### ISSUE TITLE
main.py无法运行

### ISSUE THREAD

**Issue by Archergy** [binary-husky/gpt_academic#694]
**python -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/**

Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting gradio==3.25.0 (from -r requirements.txt (line 1))
  Using cached https://mirrors.aliyun.com/pypi/packages/6c/97/86beec51b54a4adb399dcb40b139082904f638746408af5241cdce01b671/gradio-3.25.0-py3-none-any.whl (17.5 MB)
Requirement already satisfied: tiktoken>=0.3.3 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (0.3.3)
Requirement already satisfied: requests[socks] in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.29.0)
Requirement already satisfied: transformers in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (4.28.1)
Requirement already satisfied: python-markdown-math in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (0.8)
Requirement already satisfied: beautifulsoup4 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (4.12.2)
Requirement already satisfied: latex2mathml in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.75.2)
Requirement already satisfied: python-docx in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (0.8.11)
Requirement already satisfied: mdtex2html in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (1.2.0)
Requirement already satisfied: colorama in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (0.4.6)
Requirement already satisfied: Markdown in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (3.4.3)
Requirement already satisfied: pygments in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2.15.1)
Requirement already satisfied: pymupdf in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (1.22.2)
Requirement already satisfied: openai in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (0.27.4)
Requirement already satisfied: numpy in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (1.23.5)
Requirement already satisfied: arxiv in /Users/plateau/anaconda3/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (1.4.7)
Requirement already satisfied: aiofiles in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (23.1.0)
Requirement already satisfied: aiohttp in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (3.8.4)
Requirement already satisfied: altair>=4.2.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (4.2.2)
Requirement already satisfied: fastapi in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.95.0)
Requirement already satisfied: ffmpy in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: gradio-client>=0.0.8 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.1.2)
Requirement already satisfied: httpx in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.23.3)
Requirement already satisfied: huggingface-hub>=0.13.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.13.4)
Requirement already satisfied: jinja2 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: markdown-it-py[linkify]>=2.0.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: markupsafe in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (2.1.2)
Requirement already satisfied: matplotlib in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (3.7.1)
Requirement already satisfied: mdit-py-plugins<=0.3.3 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.3.3)
Requirement already satisfied: orjson in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (3.8.9)
Requirement already satisfied: pandas in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (1.5.3)
Requirement already satisfied: pillow in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (9.4.0)
Requirement already satisfied: pydantic in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (1.10.7)
Requirement already satisfied: pydub in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.25.1)
Requirement already satisfied: python-multipart in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.0.6)
Requirement already satisfied: pyyaml in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (6.0)
Requirement already satisfied: semantic-version in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (2.10.0)
Requirement already satisfied: typing-extensions in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (4.5.0)
Requirement already satisfied: uvicorn in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (0.21.1)
Requirement already satisfied: websockets>=10.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio==3.25.0->-r requirements.txt (line 1)) (11.0.1)
Requirement already satisfied: regex>=2022.1.18 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from tiktoken>=0.3.3->-r requirements.txt (line 2)) (2023.5.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from requests[socks]->-r requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from requests[socks]->-r requirements.txt (line 3)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from requests[socks]->-r requirements.txt (line 3)) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from requests[socks]->-r requirements.txt (line 3)) (2022.12.7)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from requests[socks]->-r requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: filelock in /Users/plateau/anaconda3/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 4)) (3.12.0)
Requirement already satisfied: packaging>=20.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 4)) (23.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 4)) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from transformers->-r requirements.txt (line 4)) (4.65.0)
Requirement already satisfied: soupsieve>1.2 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from beautifulsoup4->-r requirements.txt (line 6)) (2.3.2.post1)
Requirement already satisfied: lxml>=2.3.2 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from python-docx->-r requirements.txt (line 8)) (4.9.2)
Requirement already satisfied: feedparser in /Users/plateau/anaconda3/lib/python3.10/site-packages (from arxiv->-r requirements.txt (line 16)) (6.0.10)
Requirement already satisfied: entrypoints in /Users/plateau/anaconda3/lib/python3.10/site-packages (from altair>=4.2.0->gradio==3.25.0->-r requirements.txt (line 1)) (0.4)
Requirement already satisfied: jsonschema>=3.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from altair>=4.2.0->gradio==3.25.0->-r requirements.txt (line 1)) (4.17.3)
Requirement already satisfied: toolz in /Users/plateau/anaconda3/lib/python3.10/site-packages (from altair>=4.2.0->gradio==3.25.0->-r requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: fsspec in /Users/plateau/anaconda3/lib/python3.10/site-packages (from gradio-client>=0.0.8->gradio==3.25.0->-r requirements.txt (line 1)) (2023.4.0)
Requirement already satisfied: mdurl~=0.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from markdown-it-py[linkify]>=2.0.0->gradio==3.25.0->-r requirements.txt (line 1)) (0.1.2)
Requirement already satisfied: linkify-it-py<3,>=1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from markdown-it-py[linkify]>=2.0.0->gradio==3.25.0->-r requirements.txt (line 1)) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from pandas->gradio==3.25.0->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from pandas->gradio==3.25.0->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: attrs>=17.3.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from aiohttp->gradio==3.25.0->-r requirements.txt (line 1)) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from aiohttp->gradio==3.25.0->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from aiohttp->gradio==3.25.0->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from aiohttp->gradio==3.25.0->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from aiohttp->gradio==3.25.0->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from aiohttp->gradio==3.25.0->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: starlette<0.27.0,>=0.26.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from fastapi->gradio==3.25.0->-r requirements.txt (line 1)) (0.26.1)
Requirement already satisfied: sgmllib3k in /Users/plateau/anaconda3/lib/python3.10/site-packages (from feedparser->arxiv->-r requirements.txt (line 16)) (1.0.0)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from httpx->gradio==3.25.0->-r requirements.txt (line 1)) (0.16.3)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from httpx->gradio==3.25.0->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: sniffio in /Users/plateau/anaconda3/lib/python3.10/site-packages (from httpx->gradio==3.25.0->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from matplotlib->gradio==3.25.0->-r requirements.txt (line 1)) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from matplotlib->gradio==3.25.0->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from matplotlib->gradio==3.25.0->-r requirements.txt (line 1)) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from matplotlib->gradio==3.25.0->-r requirements.txt (line 1)) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from matplotlib->gradio==3.25.0->-r requirements.txt (line 1)) (3.0.9)
Requirement already satisfied: click>=7.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from uvicorn->gradio==3.25.0->-r requirements.txt (line 1)) (8.1.3)
Requirement already satisfied: h11>=0.8 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from uvicorn->gradio==3.25.0->-r requirements.txt (line 1)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from httpcore<0.17.0,>=0.15.0->httpx->gradio==3.25.0->-r requirements.txt (line 1)) (3.6.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from jsonschema>=3.0->altair>=4.2.0->gradio==3.25.0->-r requirements.txt (line 1)) (0.19.3)
Requirement already satisfied: uc-micro-py in /Users/plateau/anaconda3/lib/python3.10/site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify]>=2.0.0->gradio==3.25.0->-r requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: six>=1.5 in /Users/plateau/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas->gradio==3.25.0->-r requirements.txt (line 1)) (1.16.0)
Installing collected packages: gradio
Successfully installed gradio-3.25.0

**python main.py**

Traceback (most recent call last):
  File "/Users/plateau/chatgpt_academic/main.py", line 208, in <module>
    main()
  File "/Users/plateau/chatgpt_academic/main.py", line 4, in main
    import gradio as gr
  File "/Users/plateau/anaconda3/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/plateau/anaconda3/lib/python3.10/site-packages/gradio/components.py", line 34, in <module>
    from gradio_client import utils as client_utils
  File "/Users/plateau/anaconda3/lib/python3.10/site-packages/gradio_client/__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "/Users/plateau/anaconda3/lib/python3.10/site-packages/gradio_client/client.py", line 18, in <module>
    import huggingface_hub
ModuleNotFoundError: No module named 'huggingface_hub'

按照readme安装还是不行

**Comment by Archergy** [comment]
Replacing the "gradio==3.25.0" with "gradio==3.26.0" in the requirement.txt solves the problem.
