### ISSUE TITLE
不能正常加载ChatGLM的参数！

### ISSUE THREAD

**Issue by codeofyu** [binary-husky/gpt_academic#710]
- **(1) Describe the bug 简述**
更新后，不管收否科学上网，都会出现这个报错无法使用

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/28337592/236689174-3e6ac1cb-8608-4143-b1ca-ac0b1361a8db.png)

- **(3) Terminal Traceback 终端traceback（如有）**
Traceback (most recent call last):
  File "F:\AI\chatgpt_academic\request_llm\bridge_chatglm.py", line 43, in run
    self.chatglm_tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\transformers\dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\transformers\dynamic_module_utils.py", line 286, in get_cached_module_file
    commit_hash = model_info(pretrained_model_name_or_path, revision=revision, token=use_auth_token).sha
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\huggingface_hub\hf_api.py", line 1623, in model_info
    r = requests.get(path, headers=headers, timeout=timeout, params=params)
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "F:\AI\chatgpt_academic\py310\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "F:\AI\chatgpt_academic\request_llm\bridge_chatglm.py", line 57, in run
    raise RuntimeError("不能正常加载ChatGLM的参数！")
RuntimeError: 不能正常加载ChatGLM的参数！

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
你好，上午试不行，下午好像好了

**Comment by ZacharyCao** [comment]
遇到了一样的问题

**Comment by Stanford2299** [comment]
遇到了这个问题不知道怎么解决
