### ISSUE TITLE
[Bug]:  部署成功以后，出现 JSON 解析错误的问题

### ISSUE THREAD

**Issue by rosrookie** [binary-husky/gpt_academic#715]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

部署环境：Ubuntu 18.04， python3.10
存在的问题：
当我在网页上输入“什么是斐波拉契数列”的时候，报如下错误。
```
 gpt-3.5-turbo : 0 : 什么是斐波拉契数列 ..........
Traceback (most recent call last):
  File "/root/chatgpt_academic/request_llm/bridge_chatgpt.py", line 181, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by binary-husky** [comment]
网页界面上应该清晰显示openai显示的报错呀？是没钱，key不对，还是什么别的
