### ISSUE TITLE
能否支持自建open api 的服务器 

### ISSUE THREAD

**Issue by aiastia** [binary-husky/gpt_academic#716]
https://github.com/songquanpeng/one-api

这个项目可以添加多个 api 然后 用自己网站的api  

尝试 修改 API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "[https://自己域名.com/v1/chat/completions"}]

视乎无效

**Comment by binary-husky** [comment]
非官方的api-key无法识别的问题？

**Comment by aiastia** [comment]
嗯 。

**Comment by reeink** [comment]
+1

**Comment by VectorZhao** [comment]
可以正常对话，但是我试了chatpdf，会报错。
```

你好
你好！有什么我可以帮助您的吗？

我上传了文件，请查收
[Local Message] 收到以下文件:

private_upload/vector/2023-11-21-08-29-03/Villanueva et al_2023_Nat Commun_A new era in solar system astronomy with JWST.pdf

调用路径参数已自动修正到:

private_upload/vector/2023-11-21-08-29-03

现在您点击任意函数插件时，以上文件将被作为输入参数

函数插件功能？
理解PDF论文内容，并且将结合上下文内容，进行学术解答。函数插件贡献者: Hanzoe, binary-husky

首先你在英文语境下通读整篇论文。
[Local Message] 收到。

[1/2] Read this section, recapitulate the content of this section with less than 2048 words: 

# The exploration of our solar system is being radically changed since the beginning of opera tions of the James Webb Space Telescope (JWST) in mid 2022. JWST’s extraordinary sensitivity and instrum
[Local Message] 警告，在执行过程中遭遇问题, Traceback：

Traceback (most recent call last):
  File "./crazy_functions/crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_all.py", line 610, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_chatgpt.py", line 117, in predict_no_ui_long_connection
    json_data = json.loads(chunk.lstrip('data:'))['choices'][0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[Local Message] 重试中，请稍等 1/2：

[Local Message] 警告，在执行过程中遭遇问题, Traceback：

Traceback (most recent call last):
  File "./crazy_functions/crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_all.py", line 610, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_chatgpt.py", line 117, in predict_no_ui_long_connection
    json_data = json.loads(chunk.lstrip('data:'))['choices'][0]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[Local Message] 重试中，请稍等 2/2：
```
