### ISSUE TITLE
[Bug]: 图标docs/logo.png无法显示

### ISSUE THREAD

**Issue by Saltsmart** [binary-husky/gpt_academic#722]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

客户端图标无法显示：
![image](https://github.com/binary-husky/gpt_academic/assets/40828952/3d85a40d-d179-4756-a5eb-fb5c417a93ee)

即使将logo.png移到根目录（即main.py）所在目录，并将main.py中
```python
demo.queue(concurrency_count=CONCURRENT_COUNT).launch(server_name="0.0.0.0", server_port=PORT, auth=AUTHENTICATION, favicon_path="docs/logo.png")
``` 
的`docs/`去掉，仍旧无法显示该图标。

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\responses.py", line 335, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'docs/logo.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__    raise e
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\ProgramData\Anaconda3\envs\tool\Lib\site-packages\starlette\responses.py", line 338, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path docs/logo.png does not exist.
```

**Comment by Saltsmart** [comment]
用快捷方式运行时，起始位置要选项目根目录而不是python根目录。大乌龙！

**Comment by ZacharyCao** [comment]
> 用快捷方式运行时，起始位置要选项目根目录而不是python根目录。大乌龙！

请问是什么意思啊，我也遇到了一样的问题

**Comment by Saltsmart** [comment]
快捷方式的属性中有“起始位置”一项，要选择本项目所在位置



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月24日 18:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [binary-husky/gpt_academic] [Bug]: 图标docs/logo.png无法显示 (Issue #722) |

用快捷方式运行时，起始位置要选项目根目录而不是python根目录。大乌龙！

请问是什么意思啊，我也遇到了一样的问题
