### ISSUE TITLE
[Bug]: 未知错误

### ISSUE THREAD

**Issue by dxh8286239** [binary-husky/gpt_academic#738]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

[Local Message] Json Error

Traceback (most recent call last):

File "D:\Program Files\中科院gpt\chatgpt_academic\predict.py", line 163, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "C:\Users\xh-du\AppData\Local\Programs\Python\Python310\lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)
File "C:\Users\xh-du\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\xh-du\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by binary-husky** [comment]
- 版本过于陈旧
