### ISSUE TITLE
[Bug]: 设置API_URL_REDIRECT 后报错 chunk = next(stream_response) StopIteration

### ISSUE THREAD

**Issue by fusang1337** [binary-husky/gpt_academic#743]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

报错：
```
gpt_academic_nolocalllms_1  | To create a public link, set `share=True` in `launch()`.
gpt_academic_nolocalllms_1  |  gpt-4 : 0 : nihao  ..........
gpt_academic_nolocalllms_1  | Traceback (most recent call last):
gpt_academic_nolocalllms_1  |   File "/gpt/request_llm/bridge_chatgpt.py", line 171, in predict
gpt_academic_nolocalllms_1  |     chunk = next(stream_response)
gpt_academic_nolocalllms_1  |             ^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms_1  | StopIteration
gpt_academic_nolocalllms_1  |
gpt_academic_nolocalllms_1  | The above exception was the direct cause of the following exception:
gpt_academic_nolocalllms_1  |
gpt_academic_nolocalllms_1  | Traceback (most recent call last):
gpt_academic_nolocalllms_1  |   File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 412, in run_predict
gpt_academic_nolocalllms_1  |     output = await app.get_blocks().process_api(
gpt_academic_nolocalllms_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms_1  |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1299, in process_api
gpt_academic_nolocalllms_1  |     result = await self.call_function(
gpt_academic_nolocalllms_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms_1  |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1035, in call_function
gpt_academic_nolocalllms_1  |     prediction = await anyio.to_thread.run_sync(
gpt_academic_nolocalllms_1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms_1  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
gpt_academic_nolocalllms_1  |     return await get_asynclib().run_sync_in_worker_thread(
gpt_academic_nolocalllms_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms_1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
gpt_academic_nolocalllms_1  |     return await future
gpt_academic_nolocalllms_1  |            ^^^^^^^^^^^^
gpt_academic_nolocalllms_1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
gpt_academic_nolocalllms_1  |     result = context.run(func, *args)
gpt_academic_nolocalllms_1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms_1  |   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 491, in async_iteration
gpt_academic_nolocalllms_1  |     return next(iterator)
gpt_academic_nolocalllms_1  |            ^^^^^^^^^^^^^^
gpt_academic_nolocalllms_1  |   File "/gpt/toolbox.py", line 62, in decorated
gpt_academic_nolocalllms_1  |     yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
gpt_academic_nolocalllms_1  |   File "/gpt/request_llm/bridge_all.py", line 296, in predict
gpt_academic_nolocalllms_1  |     yield from method(inputs, llm_kwargs, *args, **kwargs)
gpt_academic_nolocalllms_1  | RuntimeError: generator raised StopIteration
```

尝试在chunk = next(stream_response)这行代码之前加上
print(stream_response)
print(stream_response.content)
报错：
```
To create a public link, set `share=True` in `launch()`.
 gpt-4 : 0 : hello ..........
<generator object Response.iter_lines at 0x7ff9763fb940>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/gpt/toolbox.py", line 62, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "/gpt/request_llm/bridge_all.py", line 296, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "/gpt/request_llm/bridge_chatgpt.py", line 172, in predict
    print(stream_response.content)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'generator' object has no attribute 'content'
```

修改为：
```
        while True:
            print(stream_response)
            print(chunk.decode()[6:])
            chunk = next(stream_response)
            print(stream_response)
            print(stream_response.content)
```
报错
```
To create a public link, set `share=True` in `launch()`.
 gpt-4 : 0 : 你好 ..........
<generator object Response.iter_lines at 0x7f19661d9540>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/gpt/toolbox.py", line 62, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "/gpt/request_llm/bridge_all.py", line 296, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "/gpt/request_llm/bridge_chatgpt.py", line 172, in predict
    print(chunk.decode()[6:])
          ^^^^^
UnboundLocalError: cannot access local variable 'chunk' where it is not associated with a value
```

**Comment by fusang1337** [comment]
修改代码/gpt/request_llm/bridge_chatgpt.py为：
```
    if stream:
        stream_response =  response.iter_lines()
        while True:
            print("stream_response:",stream_response)
            if hasattr(stream_response, 'content'):
                print(stream_response.content)
            else:
                print("stream_response对象没有content属性")
            chunk = next(stream_response)
            if hasattr(stream_response, 'content'):
                print(stream_response.content)
            else:
                print("stream_response对象没有content属性")
            print(chunk.decode()[6:])
```

报错如下：
To create a public link, set `share=True` in `launch()`.
 gpt-4 : 0 : 你好 ..........
stream_response: <generator object Response.iter_lines at 0x7fd0fc2e6e40>
stream_response对象没有content属性
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/gpt/toolbox.py", line 62, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "/gpt/request_llm/bridge_all.py", line 296, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "/gpt/request_llm/bridge_chatgpt.py", line 176, in predict
    print("chunk.decode()[6:]",chunk.decode()[6:])
                               ^^^^^
UnboundLocalError: cannot access local variable 'chunk' where it is not associated with a value
 gpt-4 : 1 : 你好 ..........
stream_response: <generator object Response.iter_lines at 0x7fd0fd271f40>
stream_response对象没有content属性
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/gpt/toolbox.py", line 62, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "/gpt/request_llm/bridge_all.py", line 296, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "/gpt/request_llm/bridge_chatgpt.py", line 176, in predict
    chunk = next(stream_response)
                               ^^^
UnboundLocalError: cannot access local variable 'chunk' where it is not associated with a value

**Comment by binary-husky** [comment]
请问您API_URL_REDIRECT转发到了哪里呢？

**Comment by fusang1337** [comment]
> 

 API_URL_REDIRECT: '{"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.com.cn/v1/completions"}'

这是一个第三方自建的服务器

**Comment by binary-husky** [comment]
刚推了一个补丁，更新后再试试：
https://github.com/binary-husky/gpt_academic/commit/43e64782dc2fc8d4451aeb37f10d17063d6c76a1

**Comment by fusang1337** [comment]
你好

[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

**Comment by Ermaotie** [comment]
有一个临时解决办法，将 `bridge_all.py` 中的所有`api.openail.com`更换为第三方中转即可
