### ISSUE TITLE
[Bug]: 突然间无法使用

### ISSUE THREAD

**Issue by Eternal130** [binary-husky/gpt_academic#745]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

运行python main.py报错
之前稳定运行了很久，今天突然这样
Traceback (most recent call last):
  File "C:\Users\Eternal30\chatgpt_academic\main.py", line 208, in <module>
    main()
  File "C:\Users\Eternal30\chatgpt_academic\main.py", line 54, in main
    with gr.Blocks(title="ChatGPT 学术优化", theme=set_theme, analytics_enabled=False, css=advanced_css) as demo:
  File "E:\python\lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "E:\python\lib\site-packages\gradio\blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "E:\python\lib\site-packages\gradio_client\serializing.py", line 41, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'

**Comment by Eternal130** [comment]
可能是库版本问题，中午更新一下看看

**Comment by Eternal130** [comment]
解决了,更新库版本
