### ISSUE TITLE
更新后出现的错误，页面正常打开但提出一个问题后程序就崩溃[Bug]: 

### ISSUE THREAD

**Issue by inbengable1** [binary-husky/gpt_academic#749]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug | 简述

更新后出现的错误，页面正常打开但提出一个问题后程序就崩溃，本来能够正常使用
Traceback (most recent call last):
  File "C:\Users\Mr.W\gpt_academic-master\request_llm\bridge_chatgpt.py", line 171, in predict
    chunk = next(stream_response)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Mr.W\anaconda3\lib\site-packages\gradio\routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Mr.W\anaconda3\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\Mr.W\anaconda3\lib\site-packages\gradio\blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Mr.W\anaconda3\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Mr.W\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Mr.W\anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Mr.W\anaconda3\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "C:\Users\Mr.W\gpt_academic-master\toolbox.py", line 62, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "C:\Users\Mr.W\gpt_academic-master\request_llm\bridge_all.py", line 296, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
RuntimeError: generator raised StopIteration

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/131265099/80cdb43d-302e-4bd7-bfd2-55f857143287)
![image](https://github.com/binary-husky/gpt_academic/assets/131265099/2c7ba1c5-0a59-4409-ba77-4f5b764b1073)

**Comment by binary-husky** [comment]
请问是否修改了API_URL 或者 API_URL_REDIRECT ? 能否给出配置？

**Comment by binary-husky** [comment]
刚推了一个补丁，更新后再试试：
https://github.com/binary-husky/gpt_academic/commit/43e64782dc2fc8d4451aeb37f10d17063d6c76a1
