### ISSUE TITLE
[Bug]: M1 Mac 安装报错

### ISSUE THREAD

**Issue by phoeniiix1203** [binary-husky/gpt_academic#771]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt and python>=3.8)

### Describe the bug | 简述

按照说明操作，执行 python main.py 报错，最后用docker才安装成功
ImportError: dlopen(/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so, 0x0002): tried: '/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (no such file), '/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

### Screen Shot | 有帮助的截图

python main.py 
Traceback (most recent call last):
  File "/Users/phoenix/gpt_academic/main.py", line 210, in <module>
    main()
  File "/Users/phoenix/gpt_academic/main.py", line 4, in main
    import gradio as gr
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/blocks.py", line 25, in <module>
    from gradio import (
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/networking.py", line 17, in <module>
    from gradio.routes import App
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/routes.py", line 24, in <module>
    import orjson
  File "/Users/phoenix/.local/lib/python3.11/site-packages/orjson/__init__.py", line 3, in <module>
    from .orjson import *
ImportError: dlopen(/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so, 0x0002): tried: '/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (no such file), '/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

(gptac_venv) ➜  gpt_academic git:(master) ✗ python main.py 
Traceback (most recent call last):
  File "/Users/phoenix/gpt_academic/main.py", line 210, in <module>
    main()
  File "/Users/phoenix/gpt_academic/main.py", line 4, in main
    import gradio as gr
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/blocks.py", line 25, in <module>
    from gradio import (
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/networking.py", line 17, in <module>
    from gradio.routes import App
  File "/Users/phoenix/.local/lib/python3.11/site-packages/gradio/routes.py", line 24, in <module>
    import orjson
  File "/Users/phoenix/.local/lib/python3.11/site-packages/orjson/__init__.py", line 3, in <module>
    from .orjson import *
ImportError: dlopen(/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so, 0x0002): tried: '/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (no such file), '/Users/phoenix/.local/lib/python3.11/site-packages/orjson/orjson.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by binary-husky** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/issues/3455


CPU的架构特殊
