### ISSUE TITLE
请问newbing-free用法

### ISSUE THREAD

**Issue by wangyuchen333** [binary-husky/gpt_academic#788]
运行会有key error，请问怎么修改呢

**Comment by binary-husky** [comment]
贴一下报错？

**Comment by wangyuchen333** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/93700456/c6c026a3-97cc-490b-a572-80c2d1877051)

**Comment by binary-husky** [comment]
需要加到 AVAIL_LLM_MODELS 里面

**Comment by binary-husky** [comment]
LLM_MODEL 和 AVAIL_LLM_MODELS 都需要改

**Comment by wangyuchen333** [comment]
好的，现在edge_free有些问题
![image](https://github.com/binary-husky/gpt_academic/assets/93700456/351fc657-7333-4b47-b27f-85aa1bef104b)

**Comment by binary-husky** [comment]
python 版本过低

**Comment by binary-husky** [comment]
> 好的，现在edge_free有些问题 ![image](https://user-images.githubusercontent.com/93700456/240786746-351fc657-7333-4b47-b27f-85aa1bef104b.png)

@wangyuchen333  
python 版本过低

**Comment by zdevc** [comment]
@binary-husky 
python3.11.3报错如下：

[Local Message] Newbing失败

Traceback (most recent call last):
  File "./request_llm/bridge_newbingfree.py", line 143, in run
    asyncio.run(self.async_run())
  File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "./request_llm/bridge_newbingfree.py", line 101, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 567, in ask_stream
    raise Exception(
Exception: Throttled: Request is throttled.

.
