### ISSUE TITLE
多线程工作常常失败

### ISSUE THREAD

**Issue by ashinxtc** [binary-husky/gpt_academic#791]
不知道大家有没有遇到这样的问题，常常在多线程翻译pdf或markdown文件的时候，几个线程的工作失败了，导致翻译的文件不完整，重试好几遍也不会成功，完全靠运气。这样非常浪费额度，文件也一直翻不完整，请问有什么改善的办法。

**Comment by ashinxtc** [comment]
有试了一下，马上又失败了，附上错误信息：
gpt-4 : 0 : 你需要翻译以下内容：
Project Management in Supply Chain Management: A literature review    Abstract    This li ..........
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
                      ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 816, in read_chunked
    with self._error_catcher():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./crazy_functions/crazy_utils.py", line 201, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llm/bridge_all.py", line 256, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llm/bridge_chatgpt.py", line 76, in predict_no_ui_long_connection
    try: chunk = next(stream_response).decode()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```
 gpt-4 : 0 : 你需要翻译以下内容：
Project Management in Supply Chain Management: A literature review    Abstract    This li .....

**Comment by binary-husky** [comment]
网络问题，试试找个稳定的网络环境吧。一方面是本身网络，另一个是代理网络

尝试减小`DEFAULT_WORKER_NUM`也行
