### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by csf2022scut** [binary-husky/gpt_academic#799]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用claude的时候报错，报错内容如下：
Traceback (most recent call last):
  File "D:\python\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\python\lib\asyncio\base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "D:\python\lib\asyncio\base_events.py", line 1120, in _create_connection_transport
    await waiter
  File "D:\python\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "D:\python\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "D:\python\lib\ssl.py", line 945, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\request_llm\bridge_stackclaude.py", line 170, in run
    asyncio.run(self.async_run())
  File "D:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\python\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File ".\request_llm\bridge_stackclaude.py", line 109, in async_run
    await self.claude_model.open_channel()
  File ".\request_llm\bridge_stackclaude.py", line 39, in open_channel
    response = await self.conversations_open(users=get_conf('SLACK_CLAUDE_BOT_ID')[0])
  File "D:\python\lib\site-packages\slack_sdk\web\async_client.py", line 2684, in conversations_open
    return await self.api_call("conversations.open", params=kwargs)
  File "D:\python\lib\site-packages\slack_sdk\web\async_base_client.py", line 161, in api_call
    return await self._send(
  File "D:\python\lib\site-packages\slack_sdk\web\async_base_client.py", line 190, in _send
    res = await self._request(http_verb=http_verb, api_url=api_url, req_args=req_args)
  File "D:\python\lib\site-packages\slack_sdk\web\async_base_client.py", line 208, in _request
    return await _request_with_session(
  File "D:\python\lib\site-packages\slack_sdk\web\async_internal_utils.py", line 195, in _request_with_session
    raise last_error
  File "D:\python\lib\site-packages\slack_sdk\web\async_internal_utils.py", line 110, in _request_with_session
    async with session.request(http_verb, api_url, **req_args) as res:
  File "D:\python\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\python\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\python\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\python\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\python\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\python\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\python\lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.slack.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')]

### Screen Shot | 有帮助的截图

/

**Comment by lovelxc** [comment]
应该是代理软件的ssl问题
