### ISSUE TITLE
[Bug]: Json异常 “error”:

### ISSUE THREAD

**Issue by EonOvO** [binary-husky/gpt_academic#850]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

Traceback (most recent call last):
  File "./request_llm/bridge_chatgpt.py", line 189, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zihengli/anaconda3/envs/gptac_venv/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zihengli/anaconda3/envs/gptac_venv/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zihengli/anaconda3/envs/gptac_venv/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Json异常 “error”: { “message”: “”, “type”: “invalid_request_error”, “param”: null, “code”: “invalid_api_key” }}

### Screen Shot | 有帮助的截图

<img width="1341" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/125801419/c448d538-e762-4bbe-b76a-05d921c34ded">

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

gpt-3.5-turbo : 0 : 1 ..........
Traceback (most recent call last):
  File "/Users/zihengli/chatgpt_academic/request_llm/bridge_chatgpt.py", line 189, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zihengli/anaconda3/envs/gptac_venv/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zihengli/anaconda3/envs/gptac_venv/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zihengli/anaconda3/envs/gptac_venv/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/d5133306-b20e-4cc3-af52-d1b6c97f21a6)

**Comment by VNemo** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/244294134-d5133306-b20e-4cc3-af52-d1b6c97f21a6.png)

多数人不知道首先会加载config_private.py这个文件，应该仅仅更改了config.py。我同样的问题更改了config_private.py中的key就ok了，如果确保key可用的情况下，应该是config_private.py中包含了以前expire的key。
