### ISSUE TITLE
[Bug]: Latex翻译/Arixv翻译＋重构PDF失败

### ISSUE THREAD

**Issue by grothen** [binary-husky/gpt_academic#853]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

Latex翻译/Arixv翻译＋重构PDF出现bug

### Screen Shot | 有帮助的截图

Traceback (most recent call last):
  File "./toolbox.py", line 99, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "./crazy_functions/Latex输出PDF结果.py", line 226, in Latex翻译中文并重新编译PDF
    txt, arxiv_id = yield from arxiv_download(chatbot, history, txt)
  File "./crazy_functions/Latex输出PDF结果.py", line 129, in arxiv_download
    extract_archive(file_path=dst, dest_dir=extract_dst)
  File "./toolbox.py", line 381, in extract_archive
    tarobj.extractall(path=dest_dir)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2036, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2077, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2150, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 2199, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 247, in copyfileobj
    buf = src.read(bufsize)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/gzip.py", line 300, in read
    return self._buffer.read(size)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by grothen** [comment]
不好意思，应该是arixv源的问题

**Comment by git-fhl** [comment]
> 不好意思，应该是arixv源的问题

请问是怎么解决的呢
