### ISSUE TITLE
[Bug]: newbing free使用报错

### ISSUE THREAD

**Issue by mhpn** [binary-husky/gpt_academic#862]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

每次调用newbing-free都会报错，具体如下
Traceback (most recent call last):
  File ".\request_llm\bridge_newbingfree.py", line 143, in run
    asyncio.run(self.async_run())
  File "C:\Users\Shawn\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Shawn\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File ".\request_llm\bridge_newbingfree.py", line 101, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 567, in ask_stream
    raise Exception(
Exception: UnauthorizedRequest: Cannot retrieve user status.

### Screen Shot | 有帮助的截图

<img width="687" alt="捕获" src="https://github.com/binary-husky/gpt_academic/assets/8263264/8c25397a-1527-4476-b6d2-ab03fd5d2160">

**Comment by Sakura4036** [comment]
Installation Method | 安装方法与平台
Pip Install (I used latest requirements.txt)

Version | 版本
Latest | 最新版

OS | 操作系统
Windows

Screen Shot | 有帮助的截图
![image](https://github.com/binary-husky/gpt_academic/assets/42060616/8519001a-8f3f-4b27-b47c-70fd7c34f778)
