### ISSUE TITLE
[Feature]: 如何修改api調用地址

### ISSUE THREAD

**Issue by Esmety** [binary-husky/gpt_academic#876]
### Class | 类型

None

### Feature Request | 功能请求

因為我使用的代理無法連接到openai.com，所以我試圖通過cf worker反代api.openai.com，但不知道如何在原代碼修改api調用地址為worker的域名。

**Comment by Esmety** [comment]
我已經知道config.py中的重定向，但修改此處後仍無法使用(請求超時)，請問還需要甚麼步驟？

**Comment by Esmety** [comment]
已解決，我必須同時修改api_key如下圖，配合反代即使使用1.1.1.1也可以調用api，而對本地Ip要求降低。
![image](https://github.com/binary-husky/gpt_academic/assets/89382498/64df1264-94ae-4769-8635-669ba4ff4047)

**Comment by Esmety** [comment]
雖然我可以在對話時使用反代的api地址，但在處理文件時卻出現了如下問題，我似乎需要再修改反代的地址，麻煩告知一下步驟。Traceback (most recent call last):
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\connection.py", line 635, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\connection.py", line 776, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\util\ssl_.py", line 466, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\util\ssl_.py", line 510, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "F:\anaconda3\envs\gpt\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "F:\anaconda3\envs\gpt\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "F:\anaconda3\envs\gpt\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.openai.com'. (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.openai.com'. (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\anaconda3\envs\gpt\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "F:\anaconda3\envs\gpt\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.openai.com'. (_ssl.c:1007)")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\crazy_functions\crazy_utils.py", line 79, in _req_gpt
    result = predict_no_ui_long_connection(
  File ".\request_llm\bridge_all.py", line 268, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
  File ".\request_llm\bridge_chatgpt.py", line 65, in predict_no_ui_long_connection
    response = requests.post(endpoint, headers=headers, proxies=proxies,
  File "F:\anaconda3\envs\gpt\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "F:\anaconda3\envs\gpt\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\anaconda3\envs\gpt\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\anaconda3\envs\gpt\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "F:\anaconda3\envs\gpt\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'api.openai.com'. (_ssl.c:1007)")))

**Comment by mahusoso** [comment]
unsubscribe



在 2023-06-16 20:11:51，"Esmety" ***@***.***> 写道：

Reopened #876.
