### ISSUE TITLE
[Bug]: 安装后运行报错

### ISSUE THREAD

**Issue by seeninheoi** [binary-husky/gpt_academic#908]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

(chatgpt) D:\gpt_academic-master\gpt_academic-master>python main.py
Traceback (most recent call last):
  File "D:\gpt_academic-master\gpt_academic-master\main.py", line 215, in <module>
    main()
  File "D:\gpt_academic-master\gpt_academic-master\main.py", line 5, in main
    if gr.__version__ not in ['3.28.3','3.32.2']: assert False, "需要特殊依赖，请务必用 pip install -r requirements.txt 指令安装依赖，详情信息见requirements.txt"
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 需要特殊依赖，请务必用 pip install -r requirements.txt 指令安装依赖，详情信 息见requirements.txt

安装后运行时出现这个报错，但是已经安装过requirements.txt里的指令，并且单独安装了gradio

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/127479932/e66c62aa-bdf2-4930-a206-5f2532afff41)

**Comment by NCKDCOK** [comment]
我也是这样报错，请问您解决了吗

**Comment by xuxinlhl** [comment]
> 我也是这样报错，请问您解决了吗

在requirements.txt里面注释掉安装gradio那一行好像就解决了
