### ISSUE TITLE
[Bug]: arxiv 翻译插件出错文章ID汇总

### ISSUE THREAD

**Issue by binary-husky** [binary-husky/gpt_academic#914]
请您首先确保程序是最新版本

格式：

ArxivID: 2304.02643
Zip: 压缩包上传

**Comment by levin714** [comment]
ArxivID: 2302.00
Zip: [2023-09-12-14-58-02-2023-09-12-14-58-01-result.zip](https://github.com/binary-husky/gpt_academic/files/12583663/2023-09-12-14-58-02-2023-09-12-14-58-01-result.zip)
377

**Comment by GreyHuu** [comment]
ArxivID: 1909.01066
Zip: [1909.01066.zip](https://github.com/binary-husky/gpt_academic/files/12611372/1909.01066.zip)
```text
Traceback (most recent call last):
  File "./[toolbox.py](http://toolbox.py/)", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/Latex 输出 PDF 结果.py", line 279, in Latex 翻译中文并重新编译 PDF
    yield from Latex 精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs,
  File "./crazy_functions/latex_fns/latex_[actions.py](http://actions.py/)", line 228, in Latex 精细分解与转化
    merged_content = merge_tex_files(project_folder, content, mode)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./crazy_functions/latex_fns/latex_[toolbox.py](http://toolbox.py/)", line 341, in merge_tex_files
    assert (match_opt1 is not None) or (match_opt2 is not None), "Cannot find paper abstract section!"
                                        ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Cannot find paper abstract section!
```

**Comment by 3060516710** [comment]
ArxivID: 2005.01185
Zip: [2005.01185.zip](https://github.com/binary-husky/gpt_academic/files/13067096/2005.01185.zip)
`Traceback (most recent call last):
  File ".\toolbox.py", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF结果.py", line 282, in Latex翻译中文并重新编译PDF
    yield from Latex精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs,
  File ".\crazy_functions\latex_fns\latex_actions.py", line 228, in Latex精细分解与转化
    merged_content = merge_tex_files(project_folder, content, mode)
  File ".\crazy_functions\latex_fns\latex_toolbox.py", line 350, in merge_tex_files
    assert (match_opt1 is not None) or (match_opt2 is not None), "Cannot find paper abstract section!"
AssertionError: Cannot find paper abstract section!`

**Comment by awwaawwa** [comment]
ArxivID: 2401.10020
Zip: 
[2024-04-13-19-54-34-result.zip](https://github.com/binary-husky/gpt_academic/files/14967368/2024-04-13-19-54-34-result.zip)

手动尝试修复时发现：
1. 614行的`\caption`没有正确闭合
2. 120行的`\fi`失踪

但是在修复以上问题后仍然报错 `File ended while scanning use of \caption@dblarg.`，应该是还有`\caption`没有正确闭合。

`merge.tex`可以正常编译。
