### ISSUE TITLE
[Bug]: Azure Openai 函数功能区所有插件失效

### ISSUE THREAD

**Issue by zengqy3** [binary-husky/gpt_academic#920]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

基础功能区和输入区都是正常的，所有的插件都会卡在openai_object.py上的报错。是因为openai_object不兼容azure吗？
error：
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/openai/openai_object.py", line 59, in __getattr__
    return self[k]
           ~~~~^^^
KeyError: 'startswith'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./crazy_functions/crazy_utils.py", line 79, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llm/bridge_all.py", line 299, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llm/bridge_azure_test.py", line 169, in predict_no_ui_long_connection
    if not chunk.startswith('data:'):
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/openai_object.py", line 61, in __getattr__
    raise AttributeError(*err.args)
AttributeError: startswith

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/50572854/bd696147-e4d6-4a7e-bea6-e1d7cdf5df63)


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by K-JW** [comment]
在 PR #797 中有人给出了临时的解决方案：https://github.com/binary-husky/gpt_academic/pull/797#issuecomment-1596036867

**Comment by binary-husky** [comment]
> 在 PR #797 中有人给出了临时的解决方案：[#797 (comment)](https://github.com/binary-husky/gpt_academic/pull/797#issuecomment-1596036867)

3.43版本已经修改，试试
