### ISSUE TITLE
[Bug]: `websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200` occurs when using newbing

### ISSUE THREAD

**Issue by Sillyringo** [binary-husky/gpt_academic#924]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

I encountered an issue while attempting to connect to newbing even after enabling the proxy. The error message `websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200` occurs at the following code snippet:

```python
  File "./request_llm/edge_gpt.py", line 290, in ask_stream
    self.wss = await websockets.connect(
```

At the time of the error, I was on commit `41c10f5 (HEAD -> master) report image generation error in UI`.

There are two potential factors that may be causing this error. The first one was discussed in this: https://github.com/acheong08/EdgeGPT/issues/584#issuecomment-1615712256. Unfortunately, I am unsure about how to resolve this particular issue. The second factor could be my incorrect proxy setup, as shown below.

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/43462278/2bf526c7-fbcd-4e32-b159-9b1e0b9e18d9)

![image](https://github.com/binary-husky/gpt_academic/assets/43462278/92ba3232-aeb1-43eb-9ec0-838f2dbeb750)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "./request_llm/bridge_newbing.py", line 154, in run
    asyncio.run(self.async_run())
  File "/Users/ringo/miniconda3/envs/gptac_venv/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/ringo/miniconda3/envs/gptac_venv/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ringo/miniconda3/envs/gptac_venv/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "./request_llm/bridge_newbing.py", line 101, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File "./request_llm/edge_gpt.py", line 389, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "./request_llm/edge_gpt.py", line 292, in ask_stream
    self.wss = await websockets.connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ringo/miniconda3/envs/gptac_venv/lib/python3.11/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ringo/miniconda3/envs/gptac_venv/lib/python3.11/site-packages/websockets/legacy/client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "/Users/ringo/miniconda3/envs/gptac_venv/lib/python3.11/site-packages/websockets/legacy/client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

**Comment by binary-husky** [comment]
thank you for reporting this issue, looking into it

**Comment by binary-husky** [comment]
use America http proxy, use cookie：good
use America http proxy, no cookie: good
use America (proxy=proxy), no cookie: good
use HK proxy (proxy=proxy), no cookie: good

**Comment by binary-husky** [comment]
use  sock5 proxy, no cookie：   unhashable type: 'bytearray'

**Comment by binary-husky** [comment]
@Sillyringo hello, I cannot reproduce same problem under same condition

however, I notice that if I use the latest EdgeGPT.py from https://github.com/acheong08/EdgeGPT, 
I end up with same error : server rejected WebSocket connection: HTTP 200

Nevertheless, in this resp we use old EdgeGPT version and cannot reproduce same error.

additionally, I also tested proxy settings.
It is found that both HK and America proxies work properly.

Anyway, I will keep looking for possible reasons. Please leave any discovery here if there is any progress

**Comment by Sillyringo** [comment]
> 

Can you please provide me with the commit id you used and your proxy configure

**Comment by Sillyringo** [comment]
> @Sillyringo hello, I cannot reproduce same problem under same condition
> 
> however, I notice that if I use the latest EdgeGPT.py from https://github.com/acheong08/EdgeGPT, I end up with same error : server rejected WebSocket connection: HTTP 200
> 
> Nevertheless, in this resp we use old EdgeGPT version and cannot reproduce same error.
> 
> additionally, I also tested proxy settings. It is found that both HK and America proxies work properly.
> 
> Anyway, I will keep looking for possible reasons. Please leave any discovery here if there is any progress

@binary-husky Can you please provide me with the commit id you used and your proxy configure

**Comment by binary-husky** [comment]
1. commit：the latest **master** will do

P.S. :  I have removed the cookie option (no longer needed) in commit https://github.com/binary-husky/gpt_academic/commit/6bc8a78cfe2e54feea2822f41170fa372f10716d minutes ago

2. proxy configure (in fact only the https matters):
```
USE_PROXY = True
proxies = { "http": "http://localhost:10881", "https": "http://localhost:10881", } 
```

3. proxy server
I have tried Hongkong server and America Server, both ok. 
Without proxies (China mainland), I end up with **Exceeded maximum allowed redirects.** error


--------------------------

Additionally, I found that socks proxy setting may cause problem in some computers, but it is probably not relavant as you are using http proxy.

**Comment by Sillyringo** [comment]
The current implementation of newbing is functional. If newbing with cookies is permanently removed, this bug may not occur and the issue could be closed. However, I am curious about the disadvantages of newbing-free compared to newbing with cookies, such as the maximum length of tokens.

**Comment by Skyzayre** [comment]
我7月2日遇到了同样的 `HTTP200` 问题，但今天pull了最新的代码后复现问题却报错 `aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected`，看上去好像是aiohttp不支持socks5代理。我回滚到之前的分支再尝试new bing，却无法再复现`HTTP 200`错误

我是在 vps 上 git clone 后直接 docker build 的，代理用的 v2ray，config 中填写了 cookies，代理填写如下：
```
proxies = {
        "http": "socks5://localhost: 7890",
        "https": "socks5h://localhost: 7890",
    }
else:
    proxies = None
```

在使用 new bing 时报错
```
Traceback (most recent call last):
  File "./request_llm/bridge_newbingfree. py", line 140, in run
    self. newbing_model = NewbingChatbot (proxy=self. proxies_https, cookies=cookies)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llm/edge_gpt_free. py", line 619, in __init__
    _Conversation (self. proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llm/edge_gpt_free. py", line 320, in __init__
    self. session = httpx. Client (
                   ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client. py", line 682, in __init__
    self._mounts: typing. Dict[URLPattern, typing. Optional[BaseTransport]] = {
                                                                            ^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client. py", line 685, in <dictcomp>
    else self._init_proxy_transport (
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client. py", line 739, in _init_proxy_transport
    return HTTPTransport (
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default. py", line 161, in __init__
    raise ImportError (
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.
```

在 docker 中直接执行
```
pip install httpx[socks]
```

重启 docker，再次提问报错
```
Traceback (most recent call last):
  File "./request_llm/bridge_newbingfree.py", line 152, in run
    asyncio.run(self.async_run())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "./request_llm/bridge_newbingfree.py", line 98, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 456, in ask_stream
    self.wss = await self.session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1275, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by QQisQQ** [comment]
I am facing the same issue. My VPS network provider is ColoCrossing, so I use Cloudflare (wireguard-go with reserved) to proxy outbound traffic.
```
Traceback (most recent call last):
  File "./request_llm/bridge_newbingfree.py", line 152, in run
    asyncio.run(self.async_run())
  File "/root/miniconda3/envs/py311/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py311/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py311/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "./request_llm/bridge_newbingfree.py", line 98, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 456, in ask_stream
    self.wss = await self.session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py311/lib/python3.11/site-packages/aiohttp/client.py", line 795, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
```

**Comment by QQisQQ** [comment]
```

``` 

> I am facing the same issue. My VPS network provider is ColoCrossing, so I use Cloudflare (wireguard-go with reserved) to proxy outbound traffic.
> 
> ```
> Traceback (most recent call last):
>   File "./request_llm/bridge_newbingfree.py", line 152, in run
>     asyncio.run(self.async_run())
>   File "/root/miniconda3/envs/py311/lib/python3.11/asyncio/runners.py", line 190, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/py311/lib/python3.11/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/py311/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "./request_llm/bridge_newbingfree.py", line 98, in async_run
>     async for final, response in self.newbing_model.ask_stream(
>   File "./request_llm/edge_gpt_free.py", line 676, in ask_stream
>     async for response in self.chat_hub.ask_stream(
>   File "./request_llm/edge_gpt_free.py", line 456, in ask_stream
>     self.wss = await self.session.ws_connect(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/root/miniconda3/envs/py311/lib/python3.11/site-packages/aiohttp/client.py", line 795, in _ws_connect
>     raise WSServerHandshakeError(
> aiohttp.client_exceptions.WSServerHandshakeError: 200, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')
> ```

it dose work for me:
https://github.com/binary-husky/gpt_academic/pull/965/commits/0c8c539e9b6e683aa851cc57798fa6ca30eb0b99

**Comment by glaw1984** [comment]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
server rejected WebSocket connection: HTTP 200

美国服务器，一用new bing机器人就是这个错误
