### ISSUE TITLE
[Bug]: [Local Message] 异常

### ISSUE THREAD

**Issue by zangqiourun** [binary-husky/gpt_academic#930]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

突然不能用了  报错如下，不知道什么情况
Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 189, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Screen Shot | 有帮助的截图

![360截图20230705095838178](https://github.com/binary-husky/gpt_academic/assets/130052096/0ed0c757-5bb9-4a5d-9ccf-e455cb401f14)

**Comment by binary-husky** [comment]
账户异常

 通过免费的反向代理接入openai chatgpt
https://github.com/binary-husky/gpt_academic/issues/900
