### ISSUE TITLE
[Bug]: `Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.` occurs when using newbing

### ISSUE THREAD

**Issue by Sillyringo** [binary-husky/gpt_academic#931]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

After configuring gpt_academic on one of my mac devices and successfully using newbing, I tried to reproduce it on another mac device but encountered the `Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.` bug. Both devices use the same config.py and the same proxy.

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/43462278/2f55675c-a300-42de-a600-021f8f6debf3)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "./request_llm/bridge_newbingfree.py", line 152, in run
    asyncio.run(self.async_run())
  File "/Users/huangyunlei/miniconda3/envs/gptac_venv/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/huangyunlei/miniconda3/envs/gptac_venv/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/huangyunlei/miniconda3/envs/gptac_venv/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "./request_llm/bridge_newbingfree.py", line 98, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "./request_llm/edge_gpt_free.py", line 567, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by binary-husky** [comment]
https://github.com/acheong08/EdgeGPT/issues/586

**Comment by Administor123** [comment]
> [acheong08/EdgeGPT#586](https://github.com/acheong08/EdgeGPT/issues/586)

你好，请问这两段代码需要加在项目的哪个位置呢
`def getCookies(url):
    import browser_cookie3
    browsers = [
        # browser_cookie3.chrome,
        # browser_cookie3.chromium,
        # browser_cookie3.opera,
        # browser_cookie3.opera_gx,
        # browser_cookie3.brave,
        browser_cookie3.edge,
        # browser_cookie3.vivaldi,
        # browser_cookie3.firefox,
        # browser_cookie3.librewolf,
        # browser_cookie3.safari,
    ]
    for browser_fn in browsers:
        # if browser isn't installed browser_cookie3 raises exception
        # hence we need to ignore it and try to find the right one
        try:
            cookies = []
            cj = browser_fn(domain_name=url)
            for cookie in cj:
                cookies.append(cookie.__dict__)
            return cookies
        except:
            continue`
`bot = EdgeGPT.Chatbot(cookies=getCookies('.bing.com'))`

**Comment by Administor123** [comment]
你好，请问你解决了吗

**Comment by Sillyringo** [comment]
> 你好，请问你解决了吗

没喔，感觉必应好不稳定，啥 bug 都有，我懒得折腾了
