### ISSUE TITLE
[Bug]: [Local Message] 不能加载Newbing组件。

### ISSUE THREAD

**Issue by yinjiashu** [binary-husky/gpt_academic#934]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

3.41版本无法使用newbing，更新3.43后仍然无法使用。已更新newbing的cookie。
除下方报错，还命令行还出现如下提醒：
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000206251DBBD0>

Traceback (most recent call last):
  File ".\request_llm\bridge_newbingfree.py", line 152, in run
    asyncio.run(self.async_run())
  File "D:\chatgpt_academic\gptac_venv\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File ".\request_llm\bridge_newbingfree.py", line 98, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 456, in ask_stream
    self.wss = await self.session.ws_connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\site-packages\aiohttp\connector.py", line 1275, in _create_proxy_connection
    resp = await proxy_resp.start(conn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/116946335/7b86b738-f21d-4ea5-af68-e2c232d81c64)

**Comment by binary-husky** [comment]
把socks代理改成http代理试试

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/issues/924

**Comment by yinjiashu** [comment]
> 把socks代理改成http代理试试

更换http后，出现下列报错。
Traceback (most recent call last):
  File ".\request_llm\bridge_newbingfree.py", line 152, in run
    asyncio.run(self.async_run())
  File "D:\chatgpt_academic\gptac_venv\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic\gptac_venv\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File ".\request_llm\bridge_newbingfree.py", line 98, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 567, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

**Comment by for3ever3** [comment]
> 
这个根据最后一句话好像是你需要验证验证码，你需要登陆那个账户，去bing/chat那里发一句话，他会弹出一个验证码，等你验证了之后，你再复制那个cookie替换就行了

**Comment by for3ever3** [comment]
> > 把socks代理改成http代理试试
> 
> Traceback (mostcentre call last): File ".\request_llm\bridge_newbingfree.py", line 152, in run asyncio.run(self.async_run()) File "D:\chatgpt_academic\gptac_venv \Lib\asyncio\runners.py”，第 190 行，运行中 返回 runner.run(main) ^^^^^^^^^^^^^^^^^ 文件“D:\chatgpt_academic\gptac_venv\Lib\asyncio \runners.py”，第 118 行，在运行中 返回 self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^ 文件“D:\chatgpt_academic\gptac_venv\Lib\asyncio\base_events.py”，第 653 行，在 run_until_complete 返回 future.result() ^^^^^^^^^^^^^^^^ 文件“.\request_llm\bridge_newbingfree.py”，第 98 行，在 async_run 中 最终异步，在 self.newbing_model.ask_stream 中响应（ 文件“.\request_llm\edge_gpt_free.py”，第 676 行，ask_stream 异步在 self.chat_hub.ask_stream（ 文件“.\request_llm\edge_gpt_free.py”，行中响应） 567，在ask_stream中 引发异常（ 异常：CaptchaChallenge：用户需要解决验证码才能继续。

这个根据最后一句话好像是你需要验证验证码，你需要登陆那个账户，去bing/chat那里发一句话，他会弹出一个验证码，等你验证了之后，你再复制那个cookie替换就行了

**Comment by yinjiashu** [comment]
> > > 把socks代理改成http代理试试
> > 
> > 
> > 回溯（最后一次调用）：文件“.\request_llm\bridge_newbingfree.py”，第 152 行，运行 asyncio.run(self.async_run()) 文件“D:\chatgpt_academic\gptac_venv \Lib\asyncio\runners.py” ，第190行，运行中 返回 runner.run(main) ^^^^^^^^^^^^^^^^^^^ 文件“D:\chatgpt_academic\gptac_venv\Lib\asyncio \runners.py”，第118行，在运行中返回 self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^文件“D:\chatgpt_academic\gptac_venv\Lib\asyncio\base_events.py”，第 653 行，在 run_until_complete 返回 future.result() ^^^^^^^^^^^^^^^^^ 文件“.\ request_llm\bridge_newbingfree.py”，第 98 行，在 async_run 中最终异步，在 self.newbing_model.ask_stream 中响应（文件“.\request_llm\edge_gpt_free.py”，第 676 行，ask_stream 异步在 self.chat_hub.ask_stream（文件“.\request_llm\edge_gpt_free.py”，行中响应）567，在ask_stream中引发异常（异常：CaptchaChallenge：用户需要解决验证码才能继续。
> 
> 根据这个最后一句话要求是你需要验证验证码，你需要登陆那个账户，去bing/chat那里发一句话，他会弹出一个验证码，等你验证了之后，你再复制那个cookie替换就行了

感谢，已经解决。
