### ISSUE TITLE
[Bug]: 无限等待

### ISSUE THREAD

**Issue by LuShouPeng** [binary-husky/gpt_academic#937]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

发送消息后无限等待

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/56241399/f76e8244-c939-4b5d-aabe-b42714921dca)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

观察Log后发现：
INFO:httpx:HTTP Request: POST http://localhost:1707/reset "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: POST http://localhost:1707/reset "HTTP/1.1 200 OK"
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='ycl8klxiawn_18' coro=<Queue.process_events() done, defined at /usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 4096, 'gp...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing>
Traceback (most recent call last):
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/python3.10/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 4096, 'gp...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
INFO:httpx:HTTP Request: POST http://localhost:1707/reset "HTTP/1.1 200 OK"
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='ycl8klxiawn_12' coro=<Queue.process_events() done, defined at /usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 4096, 'gp...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing>
Traceback (most recent call last):
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/python3.10/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, 4096, 'gp...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
INFO:httpx:HTTP Request: POST http://localhost:1707/reset "HTTP/1.1 200 OK"
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='ycl8klxiawn_19' coro=<Queue.process_events() done, defined at /usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, []]...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing>
Traceback (most recent call last):
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/python3.10/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [None, None, []]...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
INFO:httpx:HTTP Request: POST http://localhost:1707/reset "HTTP/1.1 200 OK"
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='ycl8klxiawn_5' coro=<Queue.process_events() done, defined at /usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing>
Traceback (most recent call last):
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/python3.10/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/usr/local/python3.10/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': 'ycl8klxiawn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
INFO:httpx:HTTP Request: POST http://localhost:1707/reset "HTTP/1.1 200 OK"

**Comment by binary-husky** [comment]
pip install pydantic==1.10.11

**Comment by LuShouPeng** [comment]
谢谢大佬，已经解决
