### ISSUE TITLE
[Bug]:  【无法使用newbing】Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.

### ISSUE THREAD

**Issue by river7816** [binary-husky/gpt_academic#941]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Newbing 请求失败，报错信息如下. 如果是与网络相关的问题，建议更换代理协议（推荐http）或代理节点
Traceback (most recent call last):
  File ".\request_llm\bridge_newbingfree.py", line 152, in run
    asyncio.run(self.async_run())
  File "D:\miniforge3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\miniforge3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File ".\request_llm\bridge_newbingfree.py", line 98, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 567, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
我已经挂上了节点，本地电脑也能使用newbing，但无法调用此模型

### Screen Shot | 有帮助的截图

<img width="1919" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/114122443/6e4b1cd4-b136-4b10-b934-3efd14efd5d3">
<img width="860" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/114122443/97705f4a-9eb5-49a5-9cd2-7b3114867102">

**Comment by zdevc** [comment]
打开官方聊天窗口，随便说几句，完成人机验证，再回到gpt_academic的窗口对话

**Comment by river7816** [comment]
> Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue. 微加了新的验证机制 打开官方聊天窗口，随便说几句，完成人机验证，再回到gpt_academic的窗口对话

<img width="1914" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/114122443/91061f10-e16a-4058-b80a-3586df0e90bf">
```
Traceback (most recent call last):
  File ".\request_llm\bridge_newbingfree.py", line 152, in run
    asyncio.run(self.async_run())
  File "D:\miniforge3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\miniforge3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File ".\request_llm\bridge_newbingfree.py", line 98, in async_run
    async for final, response in self.newbing_model.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 676, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File ".\request_llm\edge_gpt_free.py", line 567, in ask_stream
    raise Exception(
Exception: CaptchaChallenge: User needs to solve CAPTCHA to continue.
```
我已经打开了官方聊天窗口，但是仍然存在`User needs to solve CAPTCHA to continue.`这个问题

**Comment by zdevc** [comment]
在bing搜索主页的聊天栏聊，然后更新下cookie

**Comment by river7816** [comment]
> 在bing搜索主页的聊天栏聊，然后更新下cookie

<img width="1915" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/114122443/946947db-576d-44ee-91b6-3213324bf2d8">
我已经尝试
1. 在bing搜索主页聊天聊
2. 清除cookie
仍然报错

**Comment by zdevc** [comment]
更新cookie：
把此时可以正常回答问题bing AI网页的当前cookie复制出来，复制到config.py指定位置，重启gpt_academic

**Comment by river7816** [comment]
> 更新cookie： 把此时可以正常回答问题bing AI网页的当前cookie复制出来，复制到config.py指定位置，重启gpt_academic

<img width="1908" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/114122443/51ba4c2d-0459-4d95-abed-a1e602ea4b5b">
1. 将cookies导出为JSON格式
<img width="845" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/114122443/3c2bb490-6317-4db6-ad52-ceffae2a0666">
2. 粘贴到`NEWBING_COOKIES`下
3. 重启gpt_academic
4. 仍然无法使用

**Comment by binary-husky** [comment]
related issue https://github.com/binary-husky/gpt_academic/issues/931

**Comment by shanjilove** [comment]
如果想使用selenium 模仿请求 bing  生成cookie 呢？也需要验证码，有人遇到过吗

**Comment by Administor123** [comment]
你好，请问你解决了吗
