### ISSUE TITLE
[Bug]: [Local Message] 不能加载Newbing组件。

### ISSUE THREAD

**Issue by youkown000** [binary-husky/gpt_academic#959]
Traceback (most recent call last):
  File ".\request_llm\edge_gpt_free.py", line 343, in __init__
    self.struct = response.json()
  File "C:\Users\19453\AppData\Roaming\Python\Python310\site-packages\httpx\_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "D:\Miniconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\Miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\request_llm\bridge_newbingfree.py", line 140, in run
    self.newbing_model = NewbingChatbot(proxy=self.proxies_https, cookies=cookies)
  File ".\request_llm\edge_gpt_free.py", line 619, in __init__
    _Conversation(self.proxy, cookies=cookies),
  File ".\request_llm\edge_gpt_free.py", line 345, in __init__
    raise Exception(
Exception: Authentication failed. You have not been accepted into the beta.

**Comment by youkown000** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/49897005/bebc0a03-b47a-43a1-bddf-d3b874db78df)
