### ISSUE TITLE
[Feature]: 可以支持 key+api端点模式吗？以使用第三方提供的GPT4服务

### ISSUE THREAD

**Issue by WangShuXian6** [binary-husky/gpt_academic#977]
### Class | 类型

None

### Feature Request | 功能请求

第三方提供的服务示例：
OPENAI_API_KEY: "vSwpi"
OPENAI_API_BASE: "https://api.xxx.xx/v1"

本项目的使用方式：
API_KEY = "此处填API密钥"
API_BASE = “此处填API地址”

**Comment by binary-husky** [comment]
如果api-key符合官方格式 或者azure格式
解释：apikey满足格式 `sk-123456789xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx123456789` 即可

```
API_KEY = 'sk-123456789xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx123456789'
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"https://xxxx.yyyy.zzzz/v1/chat/completions"}
LLM_MODEL = "gpt-3.5-turbo"
```

**Comment by fancl117** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/135203044/252d5d04-3e79-432d-a931-4ec89ad09931)
国内转发key，是支持的

**Comment by someway22** [comment]
> 更新：第三方API‐KEY接入指南
> 
> https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97
> 
> 你可以把这个wiki链接发给相关方的客服

咱们这个项目难道只需要用 chat completions API endpoint? 上下文问答不是得 embeddings 么

**Comment by weisong82** [comment]
OPENAI_API_KEY: "fk-xxxxx"
API_URL_REDIRECT = {"https://api.openai.com/v1": "http://47.x.x.x:18088/v1"} 改写api地址

试过配置了，超时。
`requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x13a1d8fd0>, 'Connection to api.openai.com timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/gradio/blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/gradio/utils.py", line 336, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/gradio/utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weisong/anaconda3/envs/gptac_venv/lib/python3.11/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/weisong/code/AI/gpt_academic/toolbox.py", line 82, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "/Users/weisong/code/AI/gpt_academic/request_llm/bridge_all.py", line 540, in predict
    yield from method(inputs, llm_kwargs, *args, **kwargs)
  File "/Users/weisong/code/AI/gpt_academic/request_llm/bridge_chatgpt.py", line 168, in predict
    if retry > MAX_RETRY: raise TimeoutError
                          ^^^^^^^^^^^^^^^^^^
TimeoutError`

**Comment by dfmjndm** [comment]
第三方很多KEY不满足48位的，比如说sk-863这种，这种情况下应该给一个不用检查直接跑的选项
