### ISSUE TITLE
[Bug]: [Local Message] 不能加载Newbing组件。

### ISSUE THREAD

**Issue by crd2333** [binary-husky/gpt_academic#980]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我是用的 wsl2 搭建的服务，proxy 配置参照了“ https://github.com/binary-husky/gpt_academic/wiki/%E4%BD%BF%E7%94%A8WSL2%EF%BC%88Windows-Subsystem-for-Linux-%E5%AD%90%E7%B3%BB%E7%BB%9F%EF%BC%89%E9%83%A8%E7%BD%B2 ”，只是把端口改成我的 7890
AzureAPI 的配置参照 use_azure.md
Newbing cookies 配置参照 #620
使用 AzureAPI 能正常工作（第一个你好），但是 Newbing 不行（第二个你好）
报错看起来是网络配置原因，但是 Azure 都能用啊，这啥情况

### Screen Shot | 有帮助的截图

![1](https://github.com/binary-husky/gpt_academic/assets/113617021/29946e7b-c1c1-4f67-b7ea-59a8a39d3ac4)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crd233/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/crd233/Projects/gpt_academic/request_llm/bridge_newbingfree.py", line 147, in run
    raise RuntimeError(f"不能加载Newbing组件。")
RuntimeError: 不能加载Newbing组件。

**Comment by binary-husky** [comment]
Newbing似乎不能用某些代理协议。在azure可用的情况下，推荐优先选择azure

**Comment by charkpol** [comment]
> Newbing似乎不能用某些代理协议。在azure可用的情况下，推荐优先选择azure

请问这个提示怎么解决呢？
![image](https://github.com/binary-husky/gpt_academic/assets/108885950/1892c516-31a2-4f57-b063-9cff8db5651e)
