### ISSUE TITLE
KeyError: 'serialized_input'

### ISSUE THREAD

**Issue by aoteman-z** [binary-husky/gpt_academic#982]
### Class | 类型

None

### Feature Request | 功能请求

[PROXY] 网络代理状态：已配置。但是报错：KeyError: 'serialized_input'，具体如下
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    main()
  File "main.py", line 179, in main
    stopBtn2.click(fn=None, inputs=None, outputs=None, cancels=cancel_handles)
  File "C:\Users\86132\miniconda3\lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "C:\Users\86132\miniconda3\lib\site-packages\gradio\blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "C:\Users\86132\miniconda3\lib\site-packages\gradio_client\serializing.py", line 41, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'

**Comment by aoteman-z** [comment]
#702

**Comment by binary-husky** [comment]
看 readme 第一行
